### ISSUE TITLE
Fail to play url stream

### ISSUE THREAD

**Issue by waxfingers** [clangen/musikcube#107]
On the console I type `play http://chai5she.cdn.dvmr.fr/francemusiqueocoramonde-hifi.mp3` then the log shows _{Stream} open ok, decode failed_
Maybe I'm doing something wrong or missed some config. Musikcube can play URL streams, right? 
BTW love the UI and handeling =)

OSX 10.11.6 - musikbox within iterm

**Comment by clangen** [comment]
Hi! Yeah, while musikcube is capable of playing regular data streams over HTTP, it does not currently support ICECAST/SHOUTCAST streams. This is a known issue and planned for a subsequent release.

**Comment by georgkrause** [comment]
I somehow managed to play a stream:

go to library, use `wget https://stream.url/file.mp3`. This adds a streamed file to your lib which you can playback. Its kinda hacky, but its working :)

**Comment by clangen** [comment]
musikcube is able to stream music from other instances on other computers over HTTP/HTTPS. The other half of the streaming puzzle is internet radio, which is currently not supported, but tracked here: https://github.com/clangen/musikcube/issues/282

**Comment by ketarino** [comment]
> 
> 
> musikcube is able to stream music from other instances on other computers over HTTP/HTTPS. The other half of the streaming puzzle is internet radio, which is currently not supported, but tracked here: #282

how you do this?

**Comment by psvanzan** [comment]
> 
> 
> I somehow managed to play a stream:
> 
> go to library, use `wget https://stream.url/file.mp3`. This adds a streamed file to your lib which you can playback. Its kinda hacky, but its working :)
Can you explain how you do that? I tried but I don't understand how to create the streamed file. Thanks.

**Comment by boedy** [comment]
> Hi! Yeah, while musikcube is capable of playing regular data streams over HTTP, it does not currently support ICECAST/SHOUTCAST streams. This is a known issue and planned for a subsequent release.

@clangen How can regular datastreams be played through musikcube? I'm not able find any references to this. I'm looking for a way to pass streams to musikcube programatically.
