### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [clangen/musikcube#111]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [FlacDecoder](https://github.com/clangen/musikcube/blob/f3829564ca25580543a1fd90875e617c6ac7d2ea/src/plugins/flacdecoder/FlacDecoder.cpp#L54 "Destructor for FlacDecoder")
- [LocalLibrary::Close](https://github.com/clangen/musikcube/blob/cc6e8dbff3600cd0baed3dba1f2cb5deceb821a6/src/core/library/LocalLibrary.cpp#L113 "LocalLibrary::Close function")

**Comment by clangen** [comment]
Fixed for the upcoming release.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/clangen/musikcube/commit/d9a8b17a6f490f44750b2d3056f91f3532ee6a69 "Deletion of a few unnecessary checks").
