### ISSUE TITLE
Display issues - Foreign characters or line breaks? 

### ISSUE THREAD

**Issue by Porco-Rosso** [clangen/musikcube#113]
Hi, first of all great job on the functionality. Considering using it as my music player of choice, however at present there is a major problem with formatting that stops me. 

I imported a few albums, and quickly noticed interface breaks. (I tried both hyper and terminal.app to see if maybe it was hyper's fault, but similar issues persisted):
![screen shot 2017-07-26 at 2 05 46 pm](https://user-images.githubusercontent.com/7024527/28618512-53f4a5fe-720d-11e7-98cb-f39fa603219e.png)
<img width="1137" alt="screen shot 2017-07-26 at 2 06 14 pm" src="https://user-images.githubusercontent.com/7024527/28618513-53f6cd0c-720d-11e7-87f3-2e3c62144e07.png">
At first I thought it might be because not enough albums were imported, and so the first column was not wide enough, I also suspected the japanese characters of breaking fixed length for characters.

![screen shot 2017-07-26 at 2 13 03 pm](https://user-images.githubusercontent.com/7024527/28618510-53f1aea8-720d-11e7-8fba-921b86ce98a0.png)
![screen shot 2017-07-26 at 2 15 08 pm](https://user-images.githubusercontent.com/7024527/28618511-53f485ce-720d-11e7-941a-470b0bb7edf8.png)
![screen shot 2017-07-26 at 2 15 31 pm](https://user-images.githubusercontent.com/7024527/28618514-53f7a790-720d-11e7-84d0-44b8d6c7338c.png)
![screen shot 2017-07-26 at 2 23 29 pm](https://user-images.githubusercontent.com/7024527/28618778-3f722e8e-720e-11e7-8a54-2832b1221f5b.png)

Having added enough albums the issue persisted to my dismay. The leftover characters may indeed be the fault of hyper, but there are still some major formatting errors, as you can see in the last two screenshots. I hope this helps a bit narrow down the issue.

**Comment by Porco-Rosso** [comment]
To follow up, I can confirm these issues do not occur in iTerm2. 
<img width="964" alt="screen shot 2017-07-26 at 2 28 59 pm" src="https://user-images.githubusercontent.com/7024527/28618972-135f672a-720f-11e7-84bc-88b5da22e5f8.png">
<img width="964" alt="screen shot 2017-07-26 at 2 28 11 pm" src="https://user-images.githubusercontent.com/7024527/28618907-ceff9bcc-720e-11e7-8d58-98f3432269b2.png">

**Comment by clangen** [comment]
Looks like it may be related to pull request https://github.com/clangen/musikcube/pull/126

It is strange, however, that iTerm works fine, while the other terminal emulators do not.

**Comment by Porco-Rosso** [comment]
Thanks, this pull request should fix my problem if merged into the master.

**Comment by clangen** [comment]
The fix has been merged into master.
