### ISSUE TITLE
Segfault on reading metadata

### ISSUE THREAD

**Issue by geier** [clangen/musikcube#118]
I have several MP3s that reliably crash musikcube which than looks like this in gdb:
```
Thread 9 "musikcube" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd7fff700 (LWP 1949574)]
0x00007fffe7ce2e20 in TaglibMetadataReader::GetID3v2Tag (this=0xbff2e0,
    uri=0x7fffcc0047e0 "/path/to/mp3/file.mp3", track=0x7fffd6ffc940)
    at /home/cg/code/musikcube/src/plugins/taglib_plugin/TaglibMetadataReader.cpp:229
229                 this->SetTagValue("year", allTags["TDRC"].front()->toString().substr(0, 4), track); 
```

this is on Ubuntu 16.04, uname -a outputs `Linux oberon 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` using bafa0aa701487651d512b74b292de4d97930b8b7. If you are interested, I can send you one of the affected mp3 files.

**Comment by clangen** [comment]
Thanks for the report, @geier. Another user submitted a patch for this crash earlier today. I merged it into `master` a few minutes ago. https://github.com/clangen/musikcube/pull/121
