### ISSUE TITLE
Support for mediakeys on OS X 

### ISSUE THREAD

**Issue by evert** [clangen/musikcube#123]
Hi! I just came across this project and already _LOVE_ it. It's my new default mediaplayer.

Would it be possible to support the system-wide mediakeys from OS/X? Being able to use the play/pause key on my keyboard would be very handy!

Thanks from a new happy user

**Comment by clangen** [comment]
Yeah, I really want to support media keys in macOS at some point in the near future.

**Comment by clangen** [comment]
Better late than never? This is going into 0.61.0. https://github.com/clangen/musikcube/commit/816d4e1894efc3157864e18c67bd27dd555b345d

**Comment by evert** [comment]
I've since switched to Linux haha =) but this ticket got a bunch of likes so some people will be very happy =)

**Comment by skyfaller** [comment]
Media keys were working for me on macOS, but they recently stopped working for me in macOS Catalina version 10.15.5 (19F101) and musikcube stable stable 0.92.1. Any ideas what could have happened? Now whatever I do, it always opens Apple's "Music" app.

For the record, Spotify has the same problem, it can't seem to grab the media keys from the "Music" app anymore, so it's not just musikcube.
