### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [clangen/musikcube#125]
I would like to point out that identifiers like “[`FLAC__STREAM_DECODER_H`](https://github.com/clangen/musikcube/blob/f3829564ca25580543a1fd90875e617c6ac7d2ea/src/plugins/flacdecoder/include/FLAC/stream_decoder.h#L33 "Update candidate")” and “[`__SYNTAX_H__`](https://github.com/clangen/musikcube/blob/f3829564ca25580543a1fd90875e617c6ac7d2ea/src/plugins/m4adecoder/libfaad/syntax.h#L31 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by clangen** [comment]
Ah, this is not in the `musikcube` code base proper, it's in a 3rd party library header. Resolving.

**Comment by elfring** [comment]
Do you care to [fix also companion software components](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") anyhow?
