### ISSUE TITLE
Option to disable calling home to musikcube.com at startup

### ISSUE THREAD

**Issue by alanorth** [clangen/musikcube#127]
I notice that musikcube connects to musikcube.com at startup. Can this be made optional? I'm running version 0.21.1 on macOS.

![screen shot 2017-07-27 at 07 54 55-fs8](https://user-images.githubusercontent.com/191754/28654962-00bdf6b2-72a1-11e7-8e2a-f13f59c8a902.png)

**Comment by clangen** [comment]
Yep, we should do this.

**Comment by clangen** [comment]
This will be in subsequent releases. https://github.com/clangen/musikcube/commit/d4a88e2085e844b9f9c06beeb16ddcf77ed5d430

Resolving.
