### ISSUE TITLE
Problem Compiling from Source

### ISSUE THREAD

**Issue by cmiles74** [clangen/musikcube#130]
I'm running Solus and trying to compile from source.  It builds "taglib" but fails soon after.

```
[  4%] Completed 'taglib'
[  4%] Built target taglib
Scanning dependencies of target musikcore
[  4%] Building CXX object src/core/CMakeFiles/musikcore.dir/debug.cpp.o
clang-4.0: error: no input files
/bin/sh: -std=c++14: command not found
make[2]: *** [src/core/CMakeFiles/musikcore.dir/build.make:63: src/core/CMakeFiles/musikcore.dir
/debug.cpp.o] Error 127
make[1]: *** [CMakeFiles/Makefile2:123: src/core/CMakeFiles/musikcore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I believe I have all the necessary dependencies installed... Do you have any hints on what my issue might be? Thank you!

**Comment by geier** [comment]
This looks similar to what I tried to fix with #129, you might want to try that.

**Comment by clangen** [comment]
FYI, I just merged @geier's change into master. @cmiles74 try to pull and rebuild.

**Comment by cmiles74** [comment]
Yep, that took care of it. Many thanks! :-D
