### ISSUE TITLE
Crash displaying metadata.

### ISSUE THREAD

**Issue by PaszaVonPomiot** [clangen/musikcube#131]
Windows 10
After it has crashed for the first time it's crashing everytime I launch the app.
![image](https://user-images.githubusercontent.com/5560454/28692738-28bb016a-7322-11e7-85a0-4c54909d1263.png)

**Comment by clangen** [comment]
My guess is a strange character encoding issue. Would it be possible for you to send me your `musik.db` file to this ticket? You can find it in the following directory: `C:\Users\<username>\AppData\Roaming\musikcube\1`

I'll load the database into my local installation and hook up the debugger to see if I can figure out what's causing it to crash.

**Comment by PaszaVonPomiot** [comment]
Uploaded

https://ufile.io/ab8jg
Kotopies.12

Will be removed after 7 days.

**Comment by clangen** [comment]
@PaszaVonPomiot thank you. I believe this bug has been fixed in the latest release (0.22.0). Can you please try this build and let me know if it fixes your issue?

https://github.com/clangen/musikcube/releases/tag/0.22.0

**Comment by PaszaVonPomiot** [comment]
Yes it works. Thanks!

**Comment by clangen** [comment]
Resolved.
