### ISSUE TITLE
Albums with various artist

### ISSUE THREAD

**Issue by mkrogh** [clangen/musikcube#132]
If you have compilation albums with various artists, where each track is tagged with the correct artist, and the `Album artist` being e.g. `Various`, then musikcube will split them up in the album filter.

Currently the album view is quite unusable unless you only have albums by single artists.

**Comment by clangen** [comment]
I think I understand what's going on. Right now, albums listed in the browse view are grouped by a combination of Album+Artist. It's done like this so, for example, all "Greatest Hits" albums by different artists don't get treated as a single album.

A straight forward fix may be to group by Album+AlbumArtist instead. I'm going to have to think about this for a bit, but it seems like this should work. Unfortunately it will require a minor database migration, but not the end of the world.

**Comment by mkrogh** [comment]
In the mean time i have found out that ~~using the track view works quite well since that does not use Album+Artist, and lists everything under an album~~. Unfortunately It does not allow you to add the full album, instead only adding the first artist/track to the play queue when adding the album.

A question to think about is if it is a big problem with albums being named the same? How often does it happen? And should it justify splitting by album+artist? Why are albums different than artists in that regard (probaby because there are N albums and M artists, but still).

**Comment by demize** [comment]
> Unfortunately It does not allow you to add the full album, instead only adding the first artist/track to the play queue when adding the album.

~~How are you adding an album to the queue? The only way I can think of to add anything to the queue is to open the context menu and add it that way, but the context menu doesn't open if you have an album selected in track view (or artist/album artist view).~~

~~I could definitely use a way to add select albums to the queue from artist/album artist view. A hotkey for "add to queue" would be perfect; maybe it exists already and I'm missing it.~~

Huh, apparently just Enter, not M-Enter, will open the context menu on an album. I just tried this from track view, and it added the entire album except for tracks with a different artist.

**Comment by clangen** [comment]
I just took a look at the code, I see we're already using Album+AlbumArtist to identify an album. Album artist behavior seems fine on my end, I'm starting to get the feeling that there are certain cases where musikcube isn't parsing (or using) the album artist tags correctly in some cases. See: https://github.com/clangen/musikcube/issues/136

@mkrogh in your case does it look like AlbumArtist is not being parsed/used at all, in any views? In other words, is the list of AlbumArtists (`Library > Browse > 4`) the same list as Artists (`Library > Browse > 1`)?

Also, what format audio files are you using in this case?

**Comment by mkrogh** [comment]
@clangen Hmm, interesting. The two lists seem to be very much alike, which I would not expect given that the AlbumArtists should be a shorter list.

The audio files are flac files, and tags were added in foobar2000 on windows.

**Comment by clangen** [comment]
@mkrogh yeah, I just confirmed we're only properly reading AlbumArtist from ID3V2 tags. I think I have a fix. What platform are you currently running on?

**Comment by mkrogh** [comment]
Running musikcube on MacOS Sierra

**Comment by clangen** [comment]
This should be fixed in build 0.23.0.

https://github.com/clangen/musikcube/releases/tag/0.23.0

**Comment by mkrogh** [comment]
Still got a fragmented list in albums filter view in v0.23.0. Do I need to reindex? If so how do one do that?

Update: Removed the whole library and added it again, and now it does indeed work. However it is not a pretty migration step :)

**Comment by clangen** [comment]
@mkilgore sorry, didn't notice your question. Glad it's working, and apologies the migration was janky. :)

**Comment by simolev** [comment]
~~I'm having~~ I thought I was having this same issue with musikcube 0.60.1 on Ubuntu 18.04. mp3 files with ID3 v2.3 tags. It turned out the files were mistakenly tagged with `AlbumArtist` set the same as `Artist`.
