### ISSUE TITLE
Crashes at 59% tracks processed

### ISSUE THREAD

**Issue by mikeyrayvon** [clangen/musikcube#142]
Installed via Homebrew on Mac OS 10.12.3

I tried adding my iTunes music directory. 4598 files, musikcube crashes at 2709. Each time I run it the same problem. 

`brew uninstall musikcube` doesn't clear the musikcube library. I'd like to do that, so I can then process each folder from the directory individually until I find the offending file.

**Comment by clangen** [comment]
There was a tag parsing bug that was found and squashed in the latest release (just pushed out a few minutes ago). Please try version 0.22.0, as it should fix your issue. https://github.com/clangen/musikcube/releases/tag/0.22.0

If you continue to have problems with 0.22.0, please re-open this ticket.
