### ISSUE TITLE
No CUE Support

### ISSUE THREAD

**Issue by mabushey** [clangen/musikcube#144]
Musikcube does not seem to support single file FLAC's with CUE sheets. Any chance it will be added? I like that it works on a PI and has an Android app. I also like how it lists multiple versions under the title, for instance I have 4 different versions of Megadeth Peace Sells (Original, 2004 re-master, 2011 25th Anniversary, DVD-A). I guess it does that because it doesn't know what to make of CD image Flacs. It doesn't recognize the DVD-A .iso version.

**Comment by Sixardyh** [comment]
Any news on this ? This could be a very useful feature.

**Comment by clangen** [comment]
Duplicate of https://github.com/clangen/musikcube/issues/390, which has more commentary.
