### ISSUE TITLE
Stop hosting dependencies within the project

### ISSUE THREAD

**Issue by diizzyy** [clangen/musikcube#146]
Why are a lot of libraries in this repo instead of linking it externally or am I reading the code wrong?
At least provide a way to use external libs.

sqlite, flac, libfaad, (no)mad, ogg, taglib

As there also a reason why musikcore is static?

**Comment by anhaga** [comment]
Not my project, but what's wrong with bringing them into the repo? These aren't huge libraries.

**Comment by clangen** [comment]
On Linux things are not statically compiled. Instead, they use dynamic libraries from the packages provided by the distribution.

Binary releases for macOS statically link against dependencies to make distribution easier -- we don't have to (1) *require* homebrew or (2) figure out how to relink a bunch of dylibs using relative paths. Also note that if you build from source you can dynamically link everything.

On Windows I simply prefer to have fewer files to distribute, so we statically link where possible. 

One comment on TagLib, specifically: some versions of Ubuntu (and possibly Debian) distributed versions that were missing required symbols, so linking would fail. This may no longer be an issue, but it was as of a year and a half ago, or so.

**Comment by clangen** [comment]
Sweeping through and cleaning up old issues... I don't currently have any plans to change the way third party dependencies are managed.
