### ISSUE TITLE
Musikcube does not run on POCKET C.H.I.P

### ISSUE THREAD

**Issue by LukeeeLupac** [clangen/musikcube#153]
I followed the directions on the Rasberry Pi wiki page to install Musikcube on my Pocket C.H.I.P. Everything installed correctly but I am getting an error when attempting to run.

```
chip@chip:~$ musikcube
/usr/bin/musikcube: line 5:  5803 Aborted                 ./musikcube

```

Sorry if this is a simple fix I am still new at this 👶

**Comment by jlapaix** [comment]
try rebooting

**Comment by clangen** [comment]
@LukeeeLupac unfortunately I do not have one of these devices. What compiler are you using? I had startup crashes using clang++ 3.5.0 on my Raspberry Pi. I didn't spend much time trying to figure out why, as soon as I switched over to g++ (4.9.2 in this case) everything was fine.

**Comment by LukeeeLupac** [comment]
> try rebooting

Okay so I rebooted this morning and my device was booting so slow that I though something broke . I then reflashed a clean OS and only reinstalled musikcube binaries using the .deb and directions on the wiki. I takes a while to boot my OS after installing musikcube and dependencies, and I am still getting the same error after reinstalling and rebooting.

Here is some of my terminal messages form installation that I though could be important.

```
chip@chip:~$ sudo dpkg -i ./musikbox_raspbian_jessie_armhf_0.24.0.deb
[sudo] password for chip:
Selecting previously unselected package musikcube.
(Reading database ... 82206 files and directories currently installed.)
Preparing to unpack .../musikbox_raspbian_jessie_armhf_0.24.0.deb ...
Unpacking musikcube (0.24.0) ...
...
...
0 upgraded, 30 newly installed, 0 to remove and 125 not upgraded.
1 not fully installed or removed.
Need to get 7486 kB of archives.
After this operation, 23.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
...
...
> Get:30 http://ftp.us.debian.org/debian/ jessie/main va-driver-all armhf 1.4.1-1 [9114 B]
> Fetched 7486 kB in 14s (534 kB/s)
> perl: warning: Setting locale failed.
> perl: warning: Please check that your locale settings:
>         LANGUAGE = (unset),
>         LC_ALL = (unset),
>         LANG = "en_US.UTF-8"
>     are supported and installed on your system.
> perl: warning: Falling back to the standard locale ("C").
> locale: Cannot set LC_CTYPE to default locale: No such file or directory
> locale: Cannot set LC_MESSAGES to default locale: No such file or directory
> locale: Cannot set LC_ALL to default locale: No such file or directory
...
...
chip@chip:~$
```

**Comment by jlapaix** [comment]
Hmm strange. I had the aborted issue on my odroid XU4 when installing v21 of musikcube. Rebooting fixed it and haven't had a problem since. I'll try v24.

**Comment by the-eater** [comment]
@LukeeeLupac if I have time tonight I will start a compile job on the C.H.I.P. and see if I have the same issue :)

**Comment by the-eater** [comment]
@LukeeeLupac 

Compiled on a CHIP (with 8GB USB stick as swap 😆 ): http://zt.je/4oXPy.tgz

It's compiled with the prefix `/opt/musikcube` :) so create that directory, cd into it, and untar that file

It only seems to display through tmux tho

**Comment by clangen** [comment]
Seems like this has been working for a while? :)

Closing!
