### ISSUE TITLE
Linux binaries?

### ISSUE THREAD

**Issue by mkrogh** [clangen/musikcube#154]
There are binaries for Windows, OSX  and raspberry pi, but not for linux. I know I can compile it myself, but the wiki entry for e.g. ubuntu is assuming newer versions of e.g. boost than 16.04 has.

So it would be nice with a binary release, bonus points for packages, but at least an official binary release would be nice :+1:

**Comment by fake-fur** [comment]
would that not require the dev to build a statically linked binary?

**Comment by clangen** [comment]
I've been thinking about this for a while now. I was originally going to try to do a single Linux binary with everything statically linked, but I ran into problems statically linking against 64-bit boost libraries.

A better solution may be to get setup with travis.ci, or something, and setup some infrastructure to automatically generate distribution-specific packages for every release. 

I have to admit I'm not nearly as knowledgeable with software distribution on Linux as I am with, say, Windows. If anyone reading this has experience with this sort of thing, I'd love to hear from you. What's a low-maintenance way to automatically generate packages for the most popular distribution?

**Comment by dvdmuckle** [comment]
Mildly related, #164 and #168 aim to fix this to some extent, offering packages for Ubuntu and Fedora, automatically built.

**Comment by mkrogh** [comment]
@dvdmuckle Nice, that will really make it easier for new users. I will close this issue. Feel free to reopen.
