### ISSUE TITLE
(Don't) split ID3 artist/composer tags

### ISSUE THREAD

**Issue by the-eater** [clangen/musikcube#155]
So this is an issue I'm most likely the only one experiencing, but still worth to discuss imo,

Basically the ID3 specification specifies that `/` can be used as splitter, which sounds "fine" but they don't specify any escape character making every artist with `/` in their name invalid or be split in 2 (or 3 even).

ID3v2.4 specifies the splitter should be `0x00` which is way more realistic (as it's a non-human-readable character)

I'm my opinion it shouldn't split ID3 tags with `/` as mostly `,` is used anyway and there are not many other players doing it. but I would like to know your opinion before hand

More context and details: https://github.com/leetreveil/musicmetadata/issues/67

As addition `mpd`'s output:

![](https://zt.je/4zVN4.png)

**Comment by dimayakovlev** [comment]
I just try musikcube and got this issue with group named "25/17". Suppose that is serious problem for the "AC/DC" fans too.

**Comment by clangen** [comment]
Old issue, but we no longer do this. Resolving!
