### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by chrisWhyTea-zz** [clangen/musikcube#156]
Hi, just out of curiosity i use virustotal before trying new software...  that didn't look that good this time :/ ...  

https://www.virustotal.com/#/file-analysis/ZjdhMWEzMThmNzlhZjU0YmE3ZWQ5MDBjMzEwNTU4ZWE6MTUwMzQ0ODIxOA==

https://www.virustotal.com/#/file/568333e7399ca7873b69e3e2aa0f80bbb7d53b404e3378296429e6230f528215/detection

https://www.virustotal.com/#/file/e24dc057155bd9ebbdbb3f6e09d5203cda40d42dcd44ff4e09cd36d262d1c945/detection

**Comment by clangen** [comment]
@chrisWhyTea thank you for bringing this to my attention. 

I'm pretty sure this is a false positive.

I went ahead and downloaded the free edition of `BitDefender` (one of the AV programs that detected a threat), threw it in a virtual machine with Windows 7 and ran a scan against the zip file -- it detected the same thing -- `BTCWare.34`. I then opened the .zip file and scanned each file individually. Every file (including the executable) were fine, except for `m4adecoder.dll`, the M4A audio decoder plugin. That's the file that's causing the warning.

Next, I tested a few older versions of `m4adecoder.dll`, they also came back positive for `BTCWare.34`.

After that I compiled musikcube from scratch on a different computer (one not used for musikcube development), and tested `m4adecoder.dll`. Again, it's flagged as `BTCWare.34`.

All other files are fine.

I'd be surprised if I had some sort of undetected virus on all of my computers that specifically targets `m4adecoder.dll` and nothing else. 

Having said all that, I'm not really sure how to proceed. I'd rather not close the issue yet. Does anyone have any recommended next steps? I was thinking we can have someone else (not me, outside of my network) compile musikcube from scratch using VS2017, then see if BitDefender still detects the file as `BTCWare.34`.

**Comment by chrisWhyTea-zz** [comment]
Well each of these Virus scanners have a way to report false positive files...

For Bitdefender I already reported a it false positive and tada... BitDefender and Ad-Aware is now not reporting false positive anymore:
https://www.virustotal.com/en/file/568333e7399ca7873b69e3e2aa0f80bbb7d53b404e3378296429e6230f528215/analysis/1503466541/

i also submited the false positive to f-secure and gdata for the others not yet (it was already 2 o clock in the morning so.... well i fell asleep ;D)

EDIT:
I also reported the false positive to Cyren and tried to report Cylance, ALYac and AegisLab but AegisLab website is shit and i could not upload the zip so i upladed m4adecoder.dll only... ALYac would require to install a windows "reporting software" (https://en.estsecurity.com/support/report) that i could not use on my mac and Cylance doesnt even provide a way to report a false positive (based on this document https://www.cylance.com/content/dam/cylance/pdfs/white_papers/False_Positive.pdf musikcube beloges to the .000314% of false positive (and they still don't want to provide a way to report false positive) i tried to contact them via twitter... )

EDIT2: Now we are down to 3 false positive :)

EDIT3: Bit more research... fun fact Cylance doesnt care about the m4adecoder.dll file it self ... its just some weird enterprise security software. Additionally i could report the file to TrendMicro as false positive, which leaves ALYac and Cylance the only av where i could not report anything...

EDIT4: And more research (its a kinda interessting thing ^^) I think i found the reason why the heuristic of so many av software was going retardet (beside the fact that most of them used the bitdefender engine... inside the `musikcube/src/plugins/m4adecoder/drms/drms.c` file we have got a DecryptAES function and due to the fact that most ransomeware are using their own implementations of AESencryption/Decryption (like the used vlc stuff) the heuristic is going retardet in some cases ... this is just a presumption but actually sounds plausible...

**Comment by clangen** [comment]
@chrisWhyTea thanks for submitting the false positives, it's great that most antivirus vendors have already confirmed the file is not dangerous and added them to some sort of whitelist! I'm curious to see if they will flag subsequent builds of the dll, when things like version number change. I hope we don't need to file for exceptions whenever a new build is released. :)

**Comment by chrisWhyTea-zz** [comment]
@clangen More good news: one more has marked it as false positive...

ALYac is updating their signatures only once a day thats why it took so long (I was able to commit the file by using wine btw... but it was really annoying, nice to know for the future)

Still no answer from Cyren same thing with Trend Micro (TrendMicro said on twitter that I should follow them and send a DM In case I want support... )... 

regarding Cylance via twitter they said I should write a support ticket on their website... but well you can only write support tickets if you are a paying Cylance customer... and it looks like its a common problem with this pice of software...

Additionally if you scan only the dll on virustotal two more scanners pop up Palo Alto Network and Qihoo-360 I was able to upload the file to Qihoo (even thou the company behind this AV is shady af) but for Palo Alto I could not find a reporting function.

EDIT: More Fun... Contacted the Cylance customer Support
This is what their Sr. Product Support Engineer Tier 3 Guy said:

> -- Hi, 
> 
> I cannot find any account under your name or your company, the file in question has not been 
 found to be effecting any of our customer environments. If one of our customer reports this file as a false positive, impacting business functionality, we will investigate further. Until then, the Cylance score will remain as is. 
> Cylance support cannot work with vendors directly regarding detections seen in VirusTotal, but we would be more than happy to submit this to Threat Guidance if the request is coming from an active, paying customer. Please let us know if the vendor is able to have an active Cylance customer submit this request so it can be processed. 
> If you are our customer please provide me the email address used to login on the Cylance Console. 
> I will close this support request

Well... uhm yeah... do you know anyone who uses Cylance? I don't...


I tried some other stuff to like  unzip and rezip the files this way the Cyren scanner didn't complain anymore...

**Comment by chrisWhyTea-zz** [comment]
I had a nice little conversation with Karl from the VirusTotal Support he mentioned things that can be done:
1)  You should be digitally signing all executables, dlls  installers, etc.
2) Upvote and comment on the samples with information on where the software comes from.  For example  I did so at 
https://www.virustotal.com/#/file/568333e7399ca7873b69e3e2aa0f80bbb7d53b404e3378296429e6230f528215/community
3) Try and keep your reputation clean,  Perhaps upload your builds or automate scans with your API.  Some of the "machine learning"  might learn that your software has a good reputation after seeing it more frequently.  

Another good news is Cyren response to the false positive:
"Following receipt of your False Positive (FP) report, we have identified it to be wrongly detected as a malware. This FP is now fixed, and this file will no longer be detected as malware."

**Comment by clangen** [comment]
No longer an issue! Thanks for all the hard work here! Closing.
