### ISSUE TITLE
Adding all song to the play queue

### ISSUE THREAD

**Issue by alspore** [clangen/musikcube#157]
Is it possible to add all songs to the play queue without manualy selecting "add to end of play queue"?

**Comment by clangen** [comment]
If you don't care about clobbering whatever's in the play queue (sounds like you don't), just switch to track search `ESC` then `T`, and press `ENTER`.

**Comment by clangen** [comment]
Going to resolve this one. Please re-open with more info is the answer is not satisfactory.
