### ISSUE TITLE
VIM Keybindings for navigation

### ISSUE THREAD

**Issue by Benjamin-Connelly** [clangen/musikcube#159]
It would be awesome to have VIM keybindings for navigating the library. My fingers automatically do this instead of reach for the arrows.

**Comment by clangen** [comment]
This has been requested a handful of times now, seems like a good idea to add it.

I'll add the ability for the user to configure keybindings for `UP`, `DOWN`, `LEFT`, `RIGHT`, `PAGE UP`, `PAGE DOWN`, `HOME` and `END` via config. This should easily allow for vim-like bindings.

**Comment by clangen** [comment]
Pushed 0.26.0 that supports rebinding navigation keys. Here's a little wiki write up with info:

https://github.com/clangen/musikcube/wiki/vi-style-navigation-keys
