### ISSUE TITLE
AIF and WAV support

### ISSUE THREAD

**Issue by Benjamin-Connelly** [clangen/musikcube#160]
99% of my files are WAV and AIF. I can not see them in Musikcube after adding a directory. I can't find documentation to let me know I I have done something wrong.

**Comment by Benjamin-Connelly** [comment]
I can see all my FLAC files though.

**Comment by clangen** [comment]
There's currently no WAV or AIF decoder -- mostly because these audio formats don't have metadata, so they won't be imported cleanly into the library. 

That said, at some point it would be nice to have a working decoder for these formats.

**Comment by Benjamin-Connelly** [comment]
Thank you for your reply!

I use AIFF for all of my audio files because it does allow for metadata,
ID3v2 unless I completely misunderstand how images and info are attached to
my .af fles.

https://en.wikipedia.org/wiki/Audio_Interchange_File_Format

Metadata

AIFF files can store metadata <https://en.wikipedia.org/wiki/Metadata> in
Name, Author, Comment, Annotation, and Copyright chunks. An ID3v2 tag
<https://en.wikipedia.org/wiki/ID3v2_tag> chunk can also be embedded in
AIFF files, as well as an Application Chunk with Extensible Metadata
Platform <https://en.wikipedia.org/wiki/Extensible_Metadata_Platform> (XMP)
data in it.[7]
<https://en.wikipedia.org/wiki/Audio_Interchange_File_Format#cite_note-7>


I use Kid3 to edit my AIFF files. The tags say ID3v2.3.0.

I hope this information can lead to having AIFF support musikcube. I will
never again agree to the iTunes EULA.


Best,

Benjamin

Benjamin Connelly
Mobile: 415-917-0763
Email: benjamin.t.connelly@gmail.com
Resume: https://benjamin-connelly.github.io/
LInkedin: https://www.linkedin.com/in/benjaminconnelly

**Comment by clangen** [comment]
Likely already supported by the new(ish) ffmpeg plugin. File extensions probably just need to be whitelisted.

**Comment by clangen** [comment]
WAV and AIF support has been added and will be part of the next app release.
