### ISSUE TITLE
Browse directories

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#161]
Only files containing metadata are listed in the browse view. It would be very nice if there was a "browse by directory" option in the library view.

**Comment by clangen** [comment]
Directory browsing will be available in subsequent releases (anything after 0.40.0); preliminary code was just merged to the `master` branch. Note, however, you'll still need to add your music directories to the indexer search paths so it can build a few data structures that will be required to enable the functionality.

**Comment by ogrim** [comment]
Looking the the release notes for 0.42.0, it seems this is done. Or do you have any plans for further directory features?

**Comment by clangen** [comment]
@ogrim what do you have in mind? :)

**Comment by ogrim** [comment]
I made a small test folder with one track in the root, and more in some nested folders:
![conemu64_2018-09-04_15-48-56](https://user-images.githubusercontent.com/296455/45035329-06a7b700-b05a-11e8-8bbd-dc503b1ebdae.png)

I add only this folder, and when I start musikcube I see this:
![image](https://user-images.githubusercontent.com/296455/45035446-42428100-b05a-11e8-8451-a64457c4b513.png)

I cannot see the track in my root (Günter Wewel). I can see the track in the electronic folder (A.A) and the Bad Television album (Dubmood/Bad Television/)

Now I go into the electronic folder:
![image](https://user-images.githubusercontent.com/296455/45035650-c4cb4080-b05a-11e8-8132-13362f85c79a.png)

I can no longer see the A.A track. I think it would be nice if tracks on the same level could be accessible on the `..` so I could queue them with M-enter. Same goes for the root, I would like to see the Günter Wewel track I have there as well.

I of course find all these tracks with the other views, but that defeats the purpose of the directory view :)

**Comment by Gerodote** [comment]
i'm kinda confused: how to browse through directories? what to press ?
