### ISSUE TITLE
Automated Builds for Ubuntu and Fedora

### ISSUE THREAD

**Issue by dvdmuckle** [clangen/musikcube#164]
I noticed that there are builds for Ubuntu, but no builds for Fedora. They're pretty easy to automate, if you'd like I can create a spec file which can be used with the Copr build system.

**Comment by clangen** [comment]
I think we can probably even use CMake/CPack to generate the rpms like we do for debs. 

https://github.com/clangen/musikcube/blob/master/CMakeLists.txt#L195 

The problem I'm running into at the moment is generating all of the different builds for each release is becoming time consuming. Right now I manually launch different VMs, pull, build, package, then upload. I'm curious how other open source projects supporting different versions of Linux automate this process -- are they using something like Travis CI?

**Comment by dvdmuckle** [comment]
CPack could be used to build RPMs, though Copr has an advantage of providing not only a build system, but hosting for packages as well. With Copr, you basically write what is really a very fancy Makefile that describes your build and runtime dependencies, as well as how to build the package and where all the built stuff ends up being installed. Ubuntu has Launchpad, which offers something similar, but building packages for that is a pain, so you could probably use something like PackageCloud to just host the Ubuntu builds.

[Here](https://travis-ci.org/dvdmuckle/minsh) is an example of using Travis to automate building and pushing packages. This is much smaller than musikcube, so some of the operations like converting an RPM into a .deb are probably not good ideas. The SRPM (Source code + Specfile) gets pushed off to Copr for proper building, while RPMs generated by Travis get converted into  .debs and pushed to PackageCloud.

**Comment by dvdmuckle** [comment]
There's also the possibility of using OpenSUSE's Open Build System, which can build packages for a whole bunch of distros, though I don't have any experience using it.

**Comment by clangen** [comment]
Oh, nice. I'd definitely accept a spec file if you want to make one -- it even looks like CPack can be setup to import the spec file to generate packages, using `CPACK_RPM_USER_BINARY_SPECFILE`. This sounds super useful for me -- I'm a Linux novice (at least, when it comes to packaging and distributing software), and I can keep using the same CMake toolchain i'm used to. Best of worlds.

Also, thanks for the OpenSUSE OBS pointer -- going to spend a bit of time looking into this. It looks comprehensive, but somewhat complicated.

**Comment by dvdmuckle** [comment]
One question, are there any runtime dependencies besides pulseaudio and the like? I believe I saw CMake was statically linking libraries. A better way of phrasing this question, what are the dependencies for the Ubuntu packages?

EDIT: I think I just answered this question myself. Plus Fedora doesn't version the boost libraries, so that will make building and installing for multiple versions easier.

**Comment by clangen** [comment]
The dependencies can be found in the main CMakeLists.txt file. They are also documented here, in the "linux" section: https://github.com/clangen/musikcube/wiki/building.

On Windows and macOS, everything (within reason) is statically linked to make distribution easier. 

On Linux, however, everything is dynamically linked. I had originally considered statically linking everything and just distributing a tarball, but ran into some sort of issue with boost. It's been a while now, I can't remember the specifics.

**Comment by dvdmuckle** [comment]
How integral is the `faad2` library? It's not available in Fedora by default, however it is in RPMFusion. I suppose redistributing it in a Copr repo along with musikcube wouldn't be terrible, but it would be best to avoid that.

**Comment by clangen** [comment]
Without faad2, MP4 playback won't work. Not the end of the world, but not ideal. 

As a side note, at some point we should probably try to spin up an ffmpeg-based decoder to avoid this sort of problem in the future.

**Comment by dvdmuckle** [comment]
I guess the better question would be, will musikcube work if it doesn't find `faad2` at runtime? If we decide to do a Copr build, we can just leave a note that `faad2` and thus the RPMfusion repo would be required for MP4 playback.

**Comment by clangen** [comment]
It _should_ be fine at runtime, but we'll need to test just to make sure. It'll attempt to load the mp4 decoder plugin using `dlopen()`, which will fail because of the missing `faad` library, and the app should just march on happily.

**Comment by dvdmuckle** [comment]
I have a working specfile now, though I still need to do some testing with regards to `faab2`. Also, I looked into CPack's RPM building. It will basically generate a specfile for you given a lot of variable definitions. I'm curious to see if one can just use CPack to build from a given specfile, rather than have it generate one.

**Comment by dvdmuckle** [comment]
Just tested without `faad2`, it works and will play MP3 files, so that's good. Now the issue is on to automated builds of packages. I don't think Copr will work given our needs, as faad2-devel is still needed at compile time, and Copr can't add outside repos for required libraries. I'd suggest using Travis CI to at least automate building of other packages. The issue with using that for Fedora is we'd have to use some variety of Docker image for builds, as Travis builds run in an Ubuntu environment. That's not too much of a problem, however things are complicated by the fact that we do need to add an extra repo at compile time. I'll look to see if there are any Docker images that make this particularly easy to do, else I can create a custom one with the RPMFusion repo.

**Comment by dvdmuckle** [comment]
So I think Travis might not work out so well for us, considering we need to build in multiple environments, and by default Travis uses an Ubuntu Trusty environment. We could use Docker with Travis, but that's a bit of a pain. However, CircleCI is designed to use Docker images in order to build and test things, so we can absolutely get the right library versions and everything that way. I've started writing up a Circle CI. Curious, what commands do you use to package everything? I saw some commands at the top of a CMake file, but they didn't seem to do anything.

**Comment by dvdmuckle** [comment]
I think I got it, deb builds are now automated on CircleCI. I also added a Xenial target, since it is the current stable LTS release.

https://circleci.com/gh/dvdmuckle/musikcube (Let me know if that link doesn't work.)

Only thing left to do is to automate Fedora builds. I've been having trouble with the RPMFusion repo and the current Docker image, so I'm not sure how that will end up working, if at all. I may have to try something else. Either way, Ubuntu builds are now automated!

**Comment by dvdmuckle** [comment]
Fedora builds are now also automated. If you'd like, I can do a PR now for all the changes, or I can set up uploading the packages to some repo like PackageCloud.

**Comment by clangen** [comment]
Holy crap, this is awesome -- thanks for digging into it. I'd love to see the PR (but I may be a bit slow to respond -- just started a new job today so I'll be a bit preoccupied for the next week as I get myself adjusted). 

Circle CI seems to have some sort of basic/free tier -- is that what you're using to build?

**Comment by dvdmuckle** [comment]
Yep, we may have to tweak things so it doesn't build as often, not sure about that. Else, possibly just have manually triggered builds.

**Comment by clangen** [comment]
Automated builds have been up and running for the past couple release, and all of the major kinks have been ironed out. @dvdmuckle did all the heavy lifting, so big thanks to him! I think now's a good time to close this issue!
