### ISSUE TITLE
metadata syncing scans my files several times

### ISSUE THREAD

**Issue by carnager** [clangen/musikcube#166]
Hi, I just installed musikcube from master and am facing this issue. Musikcube scans all my music (and I can see all my albums/tracks in library and browse/play everything just fine.
But as soon as all music is added to library musikcube rescans everything. The library is not reset, but my files still were scanned 4 times until it finally stopped.

Any hints how I can debug this. Would love to help to solve this one.

**Comment by clangen** [comment]
Just noticed this issue... how do you know your files are getting scanned multiple times? Does the banner up top reset to 0 four times? Or do four times as many files show up as counted?

**Comment by carnager** [comment]
It reset to 0 each time. Will have to test again with a nuked database to be sure it's reproducable

**Comment by clangen** [comment]
Closing for now -- I gave this a test on Windows, macOS and Linux (and even my Raspberry Pi) and didn't see anything weird. Please re-open if necessary.
