### ISSUE TITLE
[feature request] replaygain support

### ISSUE THREAD

**Issue by carnager** [clangen/musikcube#167]
Maybe I just haven't found it in documentation, but from what I see musikcube does not support replaygain at the moment?

Some basic info about replaygain: http://wiki.hydrogenaud.io/index.php?title=ReplayGain

**Comment by clangen** [comment]
Yeah, I'm working on getting this into the next release.

**Comment by clangen** [comment]
@carnager I think I have ReplayGain implemented to spec, but it's hard to tell because I don't actually use it regularly. Are you a Windows user, by chance? If so I can give you a pre-release build to test.

**Comment by clangen** [comment]
In 0.35.0 and newer. https://github.com/clangen/musikcube/releases

**Comment by carnager** [comment]
Thanks a lot. I am a linux user though, but happy to test this out :)

**Comment by clangen** [comment]
As of the release, **all** builds fully support ReplayGain (including Linux). If you get a chance please let me know if it seems to be working as expected!

**Comment by clangen** [comment]
Oh, also, ReplayGain is disabled by default. Be sure to enable it in the settings -- look for `preamp and replaygain`
