### ISSUE TITLE
split core from cube?

### ISSUE THREAD

**Issue by carnager** [clangen/musikcube#171]
I would like to propose splitting the actual daemon from the client, like MPD or xmms2 do.
The musikcube client can still autostart the core, if it's not running already.

Main advantage for such an aproach is the ability to have a proper daemon one can start on headless servers without screen/tmux hacks.

**Comment by clangen** [comment]
Yep, musikcube was already designed this way. `core` can already be built separately from `cube`, as a shared library (in fact, that's how it works right now. `cube` just links against `core`). 

And the `server` component is already a plugin, that only depends on the `core sdk`.

The only work required is to spin up a new binary that acts as a daemon (or service, in Windows).

**Comment by clangen** [comment]
A super-basic daemon will be included with the next release of the source code -- but maybe not in binary-form until a subsequent release. Here's the commit: https://github.com/clangen/musikcube/commit/369f9054ba15685bdf36cbd5757fb10bdce46729. It seems to work well on Linux and macOS.

The annoying bit is that the terminal-based musikcube client won't be able to "connect" to it, per se... so starting the terminal client will effectively be a completely fresh/decoupled instance. The Android client, on the other hand, *will* be able to control the daemon. It will also have new features that allow for remote configuration of output drivers and devices, playback mode, and replay gain settings.

**Comment by clangen** [comment]
Released as part of 0.40.0. Run `musikcubed --help` for more info. As of now, the CLI client cannot attach to the daemon -- they run separately, so this is really only useful for the Android client. Hopefully this will be fixed in the future.
