### ISSUE TITLE
Display Title/Artist on terminal title

### ISSUE THREAD

**Issue by AntoineTurmel** [clangen/musikcube#173]
Ability to display the title/artist on the terminal title/tab. Maybe a way to customize the display ?
Like $(artist) - $(title)

**Comment by clangen** [comment]
I believe I looked into this at some point and discovered it was possible, but perhaps not portable or 100% reliable? Will keep this open for now.

**Comment by clangen** [comment]
This will be fixed in the next release!

**Comment by ghost** [comment]
@clangen Hi I just updated musikcube and **I want to turn off this feature**, how do I do it?

**I just want my terminal title to stay as 'musikcube' with no extra info.**

I would also like to add that the title is not updating reliably, it only updates when I go to the settings page.

![Screenshot from 2020-04-27 19-00-20](https://user-images.githubusercontent.com/8528269/80365895-e4138300-88ba-11ea-834c-e65363acb94d.png)
