### ISSUE TITLE
Filter not finding an artist

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#176]
I have some music by a rapper named `G-Eazy` and when I search for his tracks in the filter box they are not showing up.

Here's a link to a flac file you can test with on your end.

https://filebin.pw/9rgkY/

**Comment by clangen** [comment]
So for this particular tag, the first hyphen (the one after `G`) isn't a standard hyphen. It's this unicode character: https://www.fileformat.info/info/unicode/char/2010/index.htm, which is why regular text search isn't matching it.

**Comment by clangen** [comment]
Looks like we may be able to get around this by using SQLITE FTS tables. Will require some more investigation. http://www.sqlite.org/fts3.html#tokenizer

**Comment by ghost** [comment]
I'm not positive why musicbrainz is injecting a utf8 -. I'll sort that out on my end for now.

**Comment by clangen** [comment]
Already have another issue tracking fuzzy search. I believe we can close this now.
