### ISSUE TITLE
After update to 0.35 there is no Pulse output anymore

### ISSUE THREAD

**Issue by carnager** [clangen/musikcube#177]
Just updated to latest release (or rather latest master)
and now I only have Alsa and Null output modules. libpulse header files were available when compiling.
I cant see any relevant output from compiler. Any place I could look to see what caused this?

**Comment by clangen** [comment]
Which operating system are you running?

pulseaudio was disabled by default on non-Linux operating systems (like BSD).

If you're building from source, try adding `-DENABLE_PULSEAUDIO=true` to your `cmake` command, that should force it to be included.

**Comment by clangen** [comment]
Uh, looks like the Ubuntu binaries didn't have pulse included. Replaced the original binaries with `-1` versions in the release page.

**Comment by carnager** [comment]
`-DENABLE_PULSEAUDIO=true` helped, thanks
