### ISSUE TITLE
FreeBSD Fonts/Missing Character issue

### ISSUE THREAD

**Issue by CobaltFluoride** [clangen/musikcube#178]
Using FreeBSD 11.1-Release, the volume and play position characters are not printing correctly.

Fonts attempted:

- DejaVu Mono
- Monospace

Terminal emulators tried:

- lxterminal
- xterm
- terminator
- terminology
- Plain TTY terminal

Desktop environments tried:

- Openbox
- None

Installation method:
- Compiled from source
- Lame compiled from source
- Other dependencies installed with the pkg package manager.

Terminal output:
- None

Screenshot:

![mm](https://user-images.githubusercontent.com/25710899/35256188-950eb0e8-ffc0-11e7-8e29-9b278ef2ec9d.png)

**Comment by clangen** [comment]
Ugh. We really need to figure out these FreeBSD display issues. I wish I could figure out how to reproduce them.

For this particular case, it looks like the terminal session does not support UTF8. 

What does the output of the `locale` command look like?

**Comment by CobaltFluoride** [comment]
looks like LANG is not set. Perhaps that is preventing the characters from being displayed? I don't know why it's not set. I selected the right options during install.
```
$ locale
LANG=
LC_CTYPE="C"
LC_COLLATE="C"
LC_TIME="C"
LC_NUMERIC="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=
$ 
```

**Comment by clangen** [comment]
Oh. Hmm. This is probably expected behavior, then, because we are using unicode characters in some cases. I'm curious -- does configuring your account or machine to use UTF8 fix the issue? Something along these lines: https://www.b1c1l1.com/blog/2011/05/09/using-utf-8-unicode-on-freebsd/

**Comment by CobaltFluoride** [comment]
I have switched to Debian recently and the issues do not occur. I had trouble configuring the machine to have a UTF-8 locale in FreeBSD, but in Linux it just works. Thanks for the help anyhow. I'd like to say for certain that it's because of the locale, but I cannot be sure.

**Comment by clangen** [comment]
Some FreeBSD users also have issues with the scrollbar: 

See: https://github.com/clangen/musikcube/issues/172#issuecomment-353802583

**Comment by clangen** [comment]
I'm going to go ahead and resolve this issue, as the user found a solution (and the root cause seems to be well understood: "wrong: character encoding used in terminal sessions).

**Comment by oxidizingkilometerwildcard** [comment]
Im facing the same issue on Archlinux

~> locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=dv_MV.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

My locale is set correctly. My installation is rather recent. I've checked from konsole and kitty. So I dont understand what might be causing the issue.


![Screenshot_20230926_212952](https://github.com/clangen/musikcube/assets/103893892/5a12e5c9-6391-4ea9-9edf-9713e93f9286)
