### ISSUE TITLE
How do you add a track to the queue

### ISSUE THREAD

**Issue by pca2** [clangen/musikcube#181]
Maybe I'm missing something, but I can't find any documentation on how to add tracks to either the queue or a playlist. Help?

**Comment by pca2** [comment]
Okay, it looks like it's only possible through the 'm-Enter' context menu. That's very helpful, maybe it could be more explicit in the README. Closing my issue.

**Comment by adigitoleo** [comment]
OH that's where it is. This should definitely be mentioned in the user guide wiki at least.
