### ISSUE TITLE
Add setting to sort artist view by release date

### ISSUE THREAD

**Issue by matoro** [clangen/musikcube#182]
Hi, not sure of the correct terminology for this section - but in the browse view, when an artist is selected, it shows their discography in the large panel.  Is there any way to have the album list sorted by the ID3 date tag, rather than alphabetically?  Having the date displayed next to the album name would be a double bonus.  Thanks!

**Comment by Ingvix** [comment]
Was this abandoned or implemented feature? I was wondering about the same feature but couldn't find it in version 3.0.2. Seems a bit weird with all the different sort modes that you can't sort tracks by release date.
