### ISSUE TITLE
Musikdroid cannot stream flac format

### ISSUE THREAD

**Issue by gsora** [clangen/musikcube#184]
On my device (OnePlus3T with Lineage OS 15.1) I cannot stream flac files, they just appear as a 0.00 minutes long song.

After digging in logcat, I found this:

```
Source error.
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:924)
	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:846)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

It seems like exoplayer2 cannot find a flac decoder. 

A little bit of Googling revealed that flac support is now shipped in a separated package: https://medium.com/@andersonk/android-exoplayer-2-flac-extension-part-1-d7df2f8ef911

Are you planning to integrate it in musikdroid?

Thanks for your hard work and support!

**Comment by gsora** [comment]
I've just tried the approach described in the blog post I've linked and I can confirm that it works great.

Since as I understood from the sources, you're using ExoPlayer2 through `DefaultExtractorsFactory`, just dropping the .aar output from the building process described above in Android Studio *just works*.

You can find official ExoPlayer2 instructions [here](https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac) - if you cannot/don't have time to build the .aar file, I can provide an already-built version to you, ready to be embedded in musikdroid.

**Comment by clangen** [comment]
I'll try to get this into the next release, thanks for taking the time to check it out :)

In the mean time, other users can enable transocding (in musikdroid prefs), and the server will convert the FLAC to MP3 on-demand, which will work on just about every device.

**Comment by gsora** [comment]
No problem!

If a pull request with updated project settings and the aar could help, I'd be happy to open one. 

I have a feature request about the on-demand transcoding, I'll open a new issue.

**Comment by m-rzb** [comment]
Sorry to bump this issue, but would the solution for the musikdroid be included in the next release? Enabling transcoding on the server is painful as my NAS does not have the required horsepower :)
Otherwise, musikcube works beautifully. Thank you!

**Comment by gsora** [comment]
Hey, just a quick update.
Musikdroid needs to be updated to use ExoPlayer 2.9.0 to correctly embed their latest FLAC decoder.

I could do a PR with such changes, including a compiled FLAC decoder for all the major architectures.

Would that be okay for you?

**Comment by m-rzb** [comment]
Hey,

I am not involved with the project but would love a Musicdroid with FLAC decoder. Any instructions on how to compile etc would be appreciated.

**Comment by gsora** [comment]
@m-rzb check out some of the links I provided in this thread, they explain the exact procedure to get an .aar file which needs to be included in the "libs" folder of the musikdroid project.

**Comment by m-rzb** [comment]
> @m-rzb check out some of the links I provided in this thread, they explain the exact procedure to get an .aar file which needs to be included in the "libs" folder of the musikdroid project.

Thanks, very much!
I built flac.aar, included it in the libs and amended build.gradle script accordingly. Flac files work like a charm now (on my phone at least)!

**Comment by clangen** [comment]
@gsora apologies, I completely missed the updates in this thread. Pre-compiled binaries would be great. If you want to include them we should probably toss them into the following repo: https://github.com/clangen/musikcube-bin

**Comment by gsora** [comment]
@clangen no problem!
I'm traveling through Italy right now, I'll prepare a PR on musikube-bin later today.

**Comment by gsora** [comment]
@clangen I've created two pull requests:

 - https://github.com/clangen/musikcube-bin/pull/1
 - https://github.com/clangen/musikcube/pull/216

The first one adds the needed `.aar` files to `musikcube-bin` for archival purpose, the second one adds FLAC support to musikdroid directly :)

**Comment by m-rzb** [comment]
@gsora @clangen Thank you both. Great job!

**Comment by gsora** [comment]
Since #216 has been closed and merged I believe this issue can be closed. 

Hope to see the first release of musikcube with FLAC support integrated soon!
