### ISSUE TITLE
How do I obtain metadata from the streaming webserver

### ISSUE THREAD

**Issue by su8** [clangen/musikcube#185]
Hello how do I obtain metadata from the streaming webserver, tried `curl localhost:7905` but nothing shows up (the player was running and playing a song in the background).

**Comment by su8** [comment]
Whenever I call `curl localhost:7905` in the log file it appears the following message: 

```bash
Handshake ended with HTTP error: 426
```

**Comment by clangen** [comment]
Here is some documentation! https://github.com/clangen/musikcube/wiki/remote-api-documentation

In short: there are two servers -- one that uses websockets (default 7905) for metadata, and one that uses http  (default 7906) for audio streams.

**Comment by su8** [comment]
Thanks
