### ISSUE TITLE
Scrobble to last.fm

### ISSUE THREAD

**Issue by hype3** [clangen/musikcube#186]
This is my default music player now on macOS and Linux. The only thing that I am missing now is that I can scrobble my tracks to last.fm. I know this is possible with cmus with a standalone scrobbler or via status display programs. So really hopeful that Musikcube will get this in the future.

**Comment by clangen** [comment]
This has been requested a few times, I'll see about getting it into the next release!

**Comment by clangen** [comment]
Preliminary last.fm scrobbling support has been merged to `master`. It will be part of the next release.

**Comment by hype3** [comment]
Ohh thanks!

**Comment by hype3** [comment]
Sounds really great! Thanks for supporting this.

**Comment by clangen** [comment]
0.50.0 was just released with Last.FM support.
