### ISSUE TITLE
Package Builds for Ubuntu Bionic and Fedora 28

### ISSUE THREAD

**Issue by dvdmuckle** [clangen/musikcube#188]
Both versions have just hit stable, and automating the package builds for both shouldn't be too hard. If you'd like I can send in a pull request for it.

**Comment by dvdmuckle** [comment]
Currently building on Bionic is breaking with:
```
[  4%] Built target taglib
[  4%] Linking CXX shared library ../../../bin/plugins/libpulseout.so
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
src/plugins/pulseout/CMakeFiles/pulseout.dir/build.make:153: recipe for target 'bin/plugins/libpulseout.so' failed
make[2]: *** [bin/plugins/libpulseout.so] Error 1
CMakeFiles/Makefile2:887: recipe for target 'src/plugins/pulseout/CMakeFiles/pulseout.dir/all' failed
make[1]: *** [src/plugins/pulseout/CMakeFiles/pulseout.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
I'm not sure what provides the `crypto` library, and more importantly what changed between `xenial` and `bionic` to cause this error.

**Comment by dvdmuckle** [comment]
Actually, it appears this happens in `xenial` too.

**Comment by dvdmuckle** [comment]
Got it, `libssl-dev` needs to be installed.

**Comment by dvdmuckle** [comment]
`libcurl4` will also have to be installed for `bionic` as well.

**Comment by clangen** [comment]
Sorry, life's currently a bit crazy and I didn't see this one come in! Are we missing a required dependency (`libssl-dev`) in the packaging scripts on Ubuntu?

**Comment by dvdmuckle** [comment]
Sorry for the delay, been busy with things as well. It doesn't need to be installed as a package dependency, but it does need to be installed during build. `libcurl4`, however, will have to be a package dependency for `bionic` builds. Fedora, thankfully, has no such problems, so a build for Fedora 28 would just be adding another job to CircleCI and (IIRC) another version in PackageCloud.

**Comment by clangen** [comment]
Got it. How does this look? https://github.com/clangen/musikcube/pull/191

**Comment by clangen** [comment]
Fixed! Bionic and F28 builds are now distributed with new releases.
