### ISSUE TITLE
Musikdroid notification icon is overpixelated

### ISSUE THREAD

**Issue by adem4ik** [clangen/musikcube#190]
Android 5.1, 1280x720

There is Musikdroid icon in notification which looks too pixelated, seems like it's upscaled from something smaller than it should be.
![image](https://user-images.githubusercontent.com/4707112/40580066-02260c24-6148-11e8-9d75-4104f2f89528.png)
Btw if you let me know where I can replace it, I can try to redraw it.

**Comment by simolev** [comment]
I have this issue on one phone, but on another the icon looks just fine.

**Comment by clangen** [comment]
Weird, is this still an issue? I'm going to close it for now because I can't repro on my phones and I've upgraded the media compat libraries a couple times since this issue was filed.

If it's still a problem please re-open.
