### ISSUE TITLE
small

### ISSUE THREAD

**Issue by Ox16** [clangen/musikcube#192]
Is possible to small set?
no server, no files (only add binary data blob) no sqlbase and no curses?

simple main loop
:volume increase, 
 :pause 
:stop 
:seek forward
:next track, :set track :set playlist

nothing more

**Comment by ghost** [comment]
Maybe you're better server with [cmus](https://cmus.github.io/) or [SoX](http://sox.sourceforge.net/).

**Comment by clangen** [comment]
It's possible to use the `musikcore` library to implement something like this, but it doesn't currently exist and I don't have plans for it. Like ghost mentioned, cmus may be a good alternative for you.
