### ISSUE TITLE
Some strings for Last.fm aren't available for translation

### ISSUE THREAD

**Issue by adem4ik** [clangen/musikcube#195]
1) Open last.fm settings
2) Follow last.fm registration process
![image](https://user-images.githubusercontent.com/4707112/41414835-2b796d14-6ff8-11e8-8c34-c41f5d609388.png)
![image](https://user-images.githubusercontent.com/4707112/41414664-be179c32-6ff7-11e8-9b68-7a9543453ea5.png)

**Comment by clangen** [comment]
Thanks for pointing this out! Fixed in https://github.com/clangen/musikcube/commit/e71ca2f70f04c4517179608fd748b4e4056af2f7.
