### ISSUE TITLE
Command Bar display issue.

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#196]
I am using Arch Linux and I compiled this myself but for some reason the command bar doesnt display properly. Instead of having a slider like bar for the volume and seek bar they just display '~T~@'

**Comment by clangen** [comment]
Hmm. Currently musikcube only supports terminals that support UTF8. 

Are there any other garbled characters besides the slider?

**Comment by ghost** [comment]
I was using URxvt but I also just formatted my PC again and for some reason
when I rebuilt it, it worked correctly.

**Comment by clangen** [comment]
Alright, closing for now. Please re-open if this happens again!
