### ISSUE TITLE
Filter out accents in search

### ISSUE THREAD

**Issue by AntoineTurmel** [clangen/musikcube#199]
Some artists/album strings have accents like "Inüit" for example. It would be nice to be able to find them just by typing "Inuit"

**Comment by clangen** [comment]
Yeah, we should try to support this. It should be pretty straight forward -- we just need to define some sqlite 'collating sequences' and tweak a few queries.

http://www.sqlite.org/c3ref/create_collation.html
https://stackoverflow.com/a/14009341

**Comment by clangen** [comment]
This did turn out to be more complicated than expected, but I'm still planning to get it done at some point.

**Comment by AntoineTurmel** [comment]
I'm not sure it's efficient, but when you search something like: "Aeris" is should search for multiple strings like : "Aëris", "Aerîs", "Aërîs" etc. Or you could also store an "accent-less" string in database for each artist/album.

**Comment by clangen** [comment]
This should be part of the next release. Better late than never, I guess? PR and implementation details here: https://github.com/clangen/musikcube/pull/379

**Comment by clangen** [comment]
Part of 0.95.0, which was just released.
