### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error' when not root

### ISSUE THREAD

**Issue by Steinardo** [clangen/musikcube#200]
**Steps to reproduce**
Run the command  `musikcube` with the privilege of a normal user (not root)

**Expected behaviour**
Musikcube should open.

**Actual behaviour**
Musikcube raise following fault message

```
oliver@raspberrypi:~ $ musikcube
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
/usr/bin/musikcube: line 5:  1571 Aborted                 ./musikcube "$@"
```

When run the program under root, everything start normal without any problems.

**Operating system:**

```
oliver@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

oliver@raspberrypi:~ $ uname -a
Linux raspberrypi 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux
```

**Comment by clangen** [comment]
musikcube can definitely be run without root. It looks like you have some sort of locale issue with this user -- probably related to the UTF8. For now, musikcube requires a UTF8 locale in the current shell to operate properly.

Can you provide the output of the command `locale`, and also what your current user's `LC_ALL`, `LANGUAGE` and `LANG` environment variables are set to?

Here's what I have on my pi:

> pi@musikpi1:~ $ locale
> LANG=en_GB.UTF-8
> LANGUAGE=
> LC_CTYPE="en_GB.UTF-8"
> LC_NUMERIC="en_GB.UTF-8"
> LC_TIME="en_GB.UTF-8"
> LC_COLLATE="en_GB.UTF-8"
> LC_MONETARY="en_GB.UTF-8"
> LC_MESSAGES="en_GB.UTF-8"
> LC_PAPER="en_GB.UTF-8"
> LC_NAME="en_GB.UTF-8"
> LC_ADDRESS="en_GB.UTF-8"
> LC_TELEPHONE="en_GB.UTF-8"
> LC_MEASUREMENT="en_GB.UTF-8"
> LC_IDENTIFICATION="en_GB.UTF-8"
> LC_ALL=

And:

> pi@musikpi1:~ $ env | grep LANGUAGE
> pi@musikpi1:~ $ env | grep LC_ALL
> pi@musikpi1:~ $ env | grep LANG
> LANG=en_GB.UTF-8

**Comment by Steinardo** [comment]
User oliver

```
oliver@raspberrypi:~ $ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

```
oliver@raspberrypi:~ $ env | grep LANGUAGE
oliver@raspberrypi:~ $ env | grep LC_ALL
oliver@raspberrypi:~ $ env | grep LANG
LANG=de_DE.UTF-8
```

**Comment by Steinardo** [comment]
Problem is solved and musikcube run under the normal user.

It seems to be that something went wrong when setting the localisation option in `raspi-config`.
After running the setup process again in `rasp-config`, musikcube can be started under the normal user.

Thanks for the support.
