### ISSUE TITLE
start server at boot?

### ISSUE THREAD

**Issue by misaalanshori** [clangen/musikcube#203]
is is possible to start the music streaming server at boot and have it running in the background?

**Comment by m-rzb** [comment]
Hi,

If you have not figured it out yet, this link should help you:
https://github.com/clangen/musikcube/wiki/raspberry-pi#run-musikcube-on-startup

**Comment by misaalanshori** [comment]
Thanks, this works on non rpi too right? I just need to change pi to my user?

**Comment by misaalanshori** [comment]
I had reopen this because I thought it would work with a normal x86 Ubuntu. But it didn't work.

This is what I put to rc.local
     su - adminispwd -c "tmux new -s musikcube -d musikcube"

My username is adminispwd

**Comment by misaalanshori** [comment]
It works now, it was my fault
