### ISSUE TITLE
Shouldn't download libmicrohttpd on FreeBSD because the package for it exists

### ISSUE THREAD

**Issue by yurivict** [clangen/musikcube#207]
This line: 
https://github.com/clangen/musikcube/blob/master/src/plugins/server/CMakeLists.txt#L31

On FreeBSD, downloading and building external tarballs is exactly the wrong thing to do. FreeBSD has packages for almost everything, and it it doesn't you need to write to ports@FreeBSD.org and ask.

**Comment by clangen** [comment]
Fixed! https://github.com/clangen/musikcube/commit/e01581495bf945dff6170c5d1f399a68f436892c
