### ISSUE TITLE
Do you have a general roadmap for this project?

### ISSUE THREAD

**Issue by dkanada** [clangen/musikcube#208]
I haven't worked with C++ on a large project and I want to see if it's any fun, but I don't want to work on something outside the scope of this application. Do you consider it feature complete, are there any major changes being worked on right now, do you still use it for your music, et cetera. I also just wanted to find out a bit more information about the project's history. I noticed there was a bunch of work on it like a decade ago and then you picked it up about two years ago, was it a dead project or something?

I was thinking of moving the IPlaybackRemote interface into a separate plugin from the general server since they are have different uses, streaming versus remote. They kind of make sense as individual plugins to me, one for the streaming API and another for the remote with two way communication. Do you use http for the music and thumbnails to enable client caching? Technically the metadata queries don't need websockets like the remote does, so they could use http instead.

I am just trying to slice up the server into its separate components to avoid two separate servers running on a plugin that becomes a catchall for any kind of remote usage. I can definitely see a use case where someone just wants to use a simple remote, or listen to the http stream from their browser. In that situation the httpd output should technically be a separate plugin but then it would require a reimplementation of the http server, so maybe moving the http and websockets servers and making them part of the core would work? Plugins that required http access would request usage and then expose just their own functionality. Would be better to not expose unused API endpoints and also better on performance if someone just wanted to use the httpd output and didn't need a websockets server running.

**Comment by dkanada** [comment]
I am working on a quick plugin to cache album art files outside metadata right now because that's how I store covers, but I had a little bit more time to look at the plugin system. The core could have an http server and a websockets server that wouldn't be running unless at least one plugin was enabled. The sdk could add `http` and `wss` interfaces for plugins to hook into the servers and accept requests. The plugins could also implement whatever other interfaces they needed to work, so `IRemote` for the remote plugin and `IOutput` for the http output device. Let me know if that sounds like a terrible idea or won't work at all. It doesn't even really help my main interest here which is getting remote access up and running haha, but it sounds kind of fun.

**Comment by clangen** [comment]
Again, sorry for the slow response times! I don't have tons of free time at the moment. :)

> I haven't worked with C++ on a large project and I want to see if it's any fun

Just FYI, I'm by no means a C++ expert and use it in a very utilitarian way. In other words, this project may not be the best example of elegant C++ code. 

> Do you have a general roadmap for this project?

Not really, no. Life's been keeping me busy the past half year or so, and I expect it'll be the same for at least a few more months.

> Do you consider it feature complete, are there any major changes being worked on right now, do you still use it for your music, et cetera. 

I don't really consider the project feature complete, but it is relatively far along, so I don't envision doing heavy feature development in the short-term.

I have some really boring stuff I want to do next; I wrote a bunch of foundational code as part of this project -- plugin loading, logging, database handling, and a whole curses abstraction. A while ago, I extracted all of this stuff into a couple stand-alone libraries that I'd like to re-integrate into musikcube.

* https://github.com/clangen/f8n
* https://github.com/clangen/cursespp

Some other things I'd like to add:
* Support for streaming services (Spotify, SoundCloud, YouTube, etc)
* Support for other mobile platforms, like iOS
* Remote playback (as discussed in https://github.com/clangen/musikcube/issues/204)

> I also just wanted to find out a bit more information about the project's history. I noticed there was a bunch of work on it like a decade ago and then you picked it up about two years ago, was it a dead project or something?

musikcube has a convoluted history. I started the original project over a decade ago when I was a sophomore in college. I had no idea what I was doing, but somehow managed to cobble together a bunch of gross code into a surprisingly usable media player. After a while it hit a wall -- the code was a house of cards and not maintainable. I started working on what would eventually be called `mC2` with a small group of people, including @onnerby (the most prolific other contributor to the project).

Around that time I accepted an internship with a big e-commerce company, and wound up involved with a few large-scale media player / consumption apps across a bunch of platforms. musikcube was considered a conflict of interest and I was asked to stop contributing... so I did. 

@onnerby continued working on `mC2` and had a working Windows client and server. Jooles cleaned up things around the edges and got things working in Linux. Other people did other stuff. Eventually everyone else moved on to other things and the project died.

I left the e-commerice company, then worked somewhere else for a while... now somewhere else. my non-compete expired. Now I'm working on things again when I have time.

> I was thinking of moving the IPlaybackRemote interface into a separate plugin from the general server since they are have different uses, streaming versus remote. They kind of make sense as individual plugins to me, one for the streaming API and another for the remote with two way communication. 

Hmm, do you mean separating the WebSockets plugin from the HTTP plugin? I don't see any problem with with that off the top of my head.

> Do you use http for the music and thumbnails to enable client caching? Technically the metadata queries don't need websockets like the remote does, so they could use http instead.

Yeah, HTTP is used for music and thumbnails so they can be easily cached by clients. I decided to use WebSockets for metadata queries to avoid the overhead of HTTP connection creation and teardown for each query. This could potentially be mitigated by using persistent HTTP connections.

> [...] I can definitely see a use case where someone just wants to use a simple remote, or listen to the http stream from their browser. In that situation the httpd output should technically be a separate plugin but then it would require a reimplementation of the http server [...]

Yep, that's true. Note right now the plugin allows for disabling the WebSockets server but keeping the HTTP service running, and vice-versa, so users *do* have this sort of control.

> The sdk could add http and wss interfaces for plugins to hook into the servers and accept requests. The plugins could also implement whatever other interfaces they needed to work, so IRemote for the remote plugin and IOutput for the http output device. Let me know if that sounds like a terrible idea or won't work at all. It doesn't even really help my main interest here which is getting remote access up and running haha, but it sounds kind of fun.

Ah, yeah, that's a cool idea! I if I understand correctly, you're proposing implementing a new `IOutput` that streams the audio data over HTTP... and it would hook itself into the HTTP server with a new interface you're proposing. I see no reason this wouldn't work, with a bit of refactoring!

**Comment by davidmucklesonos** [comment]
That last part on streaming audio data over HTTP sounds an awful lot like the main idea in #204.

**Comment by dvdmuckle** [comment]
That last bit about HTTP streaming sounds an awful lot like #204.

**Comment by dkanada** [comment]
@dvdmuckle yup that's what I was describing. I had a look at the core though and it's much more complicated than the plugin interface =D cross platform support makes things absolutely crazy.

**Comment by zais** [comment]
> Support for streaming services (Spotify, SoundCloud, YouTube, etc)

That would be most welcome

**Comment by dvdmuckle** [comment]
@zais Not to detract from development on this project to add those things, but you may want to try out Mopidy for something like that.
