### ISSUE TITLE
Improve track list in Android app

### ISSUE THREAD

**Issue by user-51** [clangen/musikcube#209]
Hello!

Awesome app, i finally found a lightweight alternative to airsonic for streaming music to my phone.
I have lots of audio files without ID3 tags (Podcasts...). In this case the full path to the file is shown in the track list. Finding a file is difficult if the path is longer than the display space on the smartphone, since only the first characters of the path are visible.

Possible solutions to this Problem: 

- Truncate the start of the path instead of the end, so the filename is always visible
- Show the filename only
- Break the text string to multiple lines
- Marquee the text string, if the length exceeds display space

I don´t know which solution is the easiest to implement...

**Comment by clangen** [comment]
Got you covered -- the next build will have a setting where you can specify the title ellipsis mode. https://github.com/clangen/musikcube/commit/3fb7882d89643bc9ac6af598a2883bc100686b64
