### ISSUE TITLE
"Build failed"

### ISSUE THREAD

**Issue by edrumm** [clangen/musikcube#217]
![musikcube](https://user-images.githubusercontent.com/45878916/50011010-d190f600-ffb2-11e8-85b2-1d1436b0b5cb.PNG)
![image](https://user-images.githubusercontent.com/45878916/50011393-e1f5a080-ffb3-11e8-8ca9-cfdc3fc4c018.png)

Have tried multiple times but build always seems to fail, unsure why

(Microsoft Visual Studio 2017, Windows 10 Home 64 bit)

**Comment by edrumm** [comment]
Got it working now!

**Comment by clangen** [comment]
For anyone who happens upon this issue, it was very likely caused by not checking out the `musikcube-bin` submodule. Something like `git submodule update --init --recursive` in the `musikcube` source directory should take care of things.
