### ISSUE TITLE
Quickly find an option within a list

### ISSUE THREAD

**Issue by jchook** [clangen/musikcube#218]
Hey, really love Musikcube.

I think we could really improve navigation of lists by having some kind of global "jump to list item" feature.

For example:

1. Press <kbd>?</kbd> to load hotkeys
2. Desire to access the `navigate_library_filter` option
3. Press <kbd>DOWN</kbd> key **17 times**

Instead what if I could...

3. Press <kbd>/</kbd> then <kbd>f</kbd>

Where pressing forwardslash would open a small "jump to" context menu that used fuzzy search to jump my cursor to the first matching item in the list. 

In the example above, `navigate_library_filter` matches `f` because it's the first item in the list containing an `f`. If I wanted to reach `playback_seek_forward` I could have typed `/fo` to further qualify my fuzzy search string and skip farther down the list.

I dream of this feature working on virtually all lists in MusikCube.

**Comment by clangen** [comment]
Agreed, this would be awesome, but non-trivial to implement. I'm going to keep this ticket open and continue to think about a way to get it implemented, but it probably won't happen right away.

**Comment by clangen** [comment]
A version of this was implemented recently, and activated using `^F` in browse view.
