### ISSUE TITLE
Modifying currently immutable hotkeys, and global hotkeys available for windows users.

### ISSUE THREAD

**Issue by gagsays** [clangen/musikcube#219]
I was ecstatic to find this nifty player, but sadly it turns out that it is not compatible with my setup (and might be true for others too). Let me explain - I use Visual Studio 2017 with VsVim (with custom key bindings), and Visual Assist X for programming. Furthermore, I also have a few global keybinding through a AutoHotkey script. 
Now, as you can tell I am an avid keyboard user, and I understand that with those many applications running concurrently one is bound to run into an issue or two, but still everything worked nicely until I threw musikcube into the mix. Now I will randomly (for lack of a better word) get stuck Ctrl key (not physically obviously), and it makes the entire typing and UI experience very frustrating.

I have tried disabling AutoHotkey and Visual Assist X one at a time with no joy, and if I exit of muzikcube everything returns to normal except for that I don't have musikcube anymore! This made me wonder if musikcube's keybinding could be the culprit, here. I have already modified all the mutable keybindings to not rely on the ctrl key, but there are a few which are hardcoded to use ctrl key such as- Ctrl-D for exit which can interfere with Ctrl-D for page down in vsvim, almost all of the global hotkeys, available to windows users, also use ctrl key albiet rctrl, etc.

So I would like to request the capability to modify all type of keybinding, or at least the ability to opt out of global hotkeys for windows users.

PS: The reason I keep saying "global hotkeys for windows users" is that according to the user-guide they are only available to the windows users.

**Comment by clangen** [comment]
Hello!

> ... there are a few which are hardcoded to use ctrl key such as- Ctrl-D for exit which can interfere with Ctrl-D for page down in vsvim

Yeah, this has been requested a couple times. For whatever reason, I hard-coded `CTRL+D` very early in the project and just never got around to making it customizable. I'll look into fixing that for the upcoming release.

> ... almost all of the global hotkeys

Ah, you're in luck here. While you can't customize the global hotkeys right now, you can turn them off. They are implemented as a plugin, so you can either disable the plugin (`settings > configure plugins > win32globalhotkeys > [spacebar to uncheck]` > restart app) or just close the app and delete the `win32globalhotkeys.dll` entirely (it's in the `plugins` subdirectory of install directory).

**Comment by clangen** [comment]
Here's a change that allows customization of the quit key: https://github.com/clangen/musikcube/commit/c06c774bd7a69a4a20a2b3662e365699dead06bd

from the commit message:

> Allow for customizing the quit key via `settings.json` using the `AppQuitKey` property.
>
> Right now there's no UI for it, and it may stay this way because it's an uncommon use case and I have some concerns about users accidentally binding it to an important key and making the app difficult to start/navigate.

**Comment by gagsays** [comment]
Just disabling the global hotkeys did the trick, thanks.

**Comment by clangen** [comment]
Great, closing this issue as the feature request will be addressed in the next release.
