### ISSUE TITLE
Please allow to use the external taglib

### ISSUE THREAD

**Issue by yurivict** [clangen/musikcube#220]
There is already a ```taglib``` installed:
```
$ pkg info | grep taglib
taglib-1.11.1_2                Library for manipulating ID3 tags and Ogg comments
```
Repology shows that ```taglib``` is available on virtually all systems now: https://repology.org/metapackage/taglib/versions , so there should be no need to bundle it.

It's not a show-stopper, but external packages should be used when possible. Otherwise everything will bundle everything else, and there'll be hundreds of copies of the same things in the system. -)

**Comment by clangen** [comment]
I'll give this a shot later today! I'm going to guess it'll be fine to use the external library on FreeBSD -- this hack currently exists because certain older versions of Ubuntu had a version of the library that was incorrectly/incompletely compiled and was missing some symbols we depended on.

**Comment by yurivict** [comment]
You should create a cmake variable, ex. ```USE_BUNDLED_TAGLIB```, with default ```OFF```. People who need it bundled will be able to turn it ```ON```.

**Comment by clangen** [comment]
Yep, did just that. Changes are in the `master` branch. Should be good to go now!

**Comment by yurivict** [comment]
Thank you!
