### ISSUE TITLE
Add install instructions.

### ISSUE THREAD

**Issue by simolev** [clangen/musikcube#222]
Please add some simple install instructions so beginners are not put off because they don't know what to do. On Ubuntu I had to:

* Download the .deb file corresponding to the Ubuntu version (Artful, Bionic, Cosmic, ...) from the [releases page](https://github.com/clangen/musikcube/releases).
* run `sudo dpkg -i <file.deb>` to install musikcube.
* run `sudo apt-get -f install` to install all needed dependencies.
* run `/usr/bin/musikcubed` to start the server daemon.
* run `/usr/bin/musikcube` to start the program interactively.
* select the directory containing the music files and press `<spacebar>`.

To create a service:
`sudo touch /etc/systemd/system/musikcube.service`
`sudo systemctl edit --full musikcube.service`

Service definition (replace `<user>` with your username):
```
[Install]
WantedBy=network-online.target

[Unit]
Description=MusikCube Audio Streaming Server
Before=multi-user.target
Before=graphical.target
Before=shutdown.target
After=local-fs.target
After=remote-fs.target
After=network-online.target
After=nss-lookup.target
Wants=network-online.target
Conflicts=shutdown.target

[Service]
Type=forking
User=<user>
ExecStart=/usr/bin/musikcubed --start
ExecStop=/usr/bin/musikcubed --stop
```

Auto start the service on system startup:
`systemctl enable musikcube`

**Comment by clangen** [comment]
This is great! Thank you for taking the time to show ho to make a systemd service definition. I'll make sure to add these instructions before the next release, which will probably drop within the next couple weeks!

**Comment by clangen** [comment]
First crack at the installation guide: https://github.com/clangen/musikcube/wiki/installing
