### ISSUE TITLE
Linux: Binary and library files installed to wrong location

### ISSUE THREAD

**Issue by the-eater** [clangen/musikcube#227]
Since I don't have to run a custom musikcube build anymore, I tried to get it into my distro's repo, but I've hit an issue, currently all binaries and libraries are installed to `$PREFIX/share/musikcube` but they should be installed to `$PREFIX/bin` and `$PREFIX/lib`. Architecture specific files shouldn't be in `/usr/share` on Linux. (See https://github.com/void-linux/void-packages/pull/6731)

To mitigate this I've currently added a patch which puts everything in the correct location: https://github.com/void-linux/void-packages/pull/6731/files#diff-8af90d64825362985a0b9eede26328cd

It would be nice if musikcube could do this by default

**Comment by duskmoss** [comment]
Why was this closed as completed? The situation appears to be the same to me.
