### ISSUE TITLE
segfault in 0.60.1 on FreeBSD

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#228]
Getting a segfault in FreeBSD 12-stable with the newly created musikcube port. I just compiled and installed it and this is the backtrace I'm getting.

![2019-01-08-055006_797x1014_scrot](https://user-images.githubusercontent.com/980/50826367-74663700-1309-11e9-9dbc-a69289c84a64.png)

https://www.freshports.org/multimedia/musikcube/

**Comment by yurivict** [comment]
This is a regression, musikcube-0.51.0.46 didn't crash.

**Comment by clangen** [comment]
Oh man, the infamous FreeBSD scrollbar issue is back. We saw this about a year ago and I was never able to repro. That was in an older release of FreeBSD, so I decided to re-enable the code in 0.60.0. Looks like the problem is still there. 

There's a lengthy discussion here that I'll re-review this evening: https://github.com/clangen/musikcube/issues/172

Again, if you guys have any idea how I can repro this on my end, please let me know.

**Comment by clangen** [comment]
I don't think I ever asked this before -- what type of hardware are you seeing this issue on? You said the processor was 64-bit, but what type of processor is it? I've only ever tested on x86-64, but not arm64 or sparc64. Maybe I we have an endianness problem somewhere.

**Comment by ghost** [comment]
This is a amd ryzen system that i'm on. @yurivict can you look over issue #172 it was a discussion about a bug we were having with a ncurses feature I guess long ago before you created the port.

**Comment by yurivict** [comment]
> You said the processor was 64-bit, but what type of processor is it?

For me it is amd64: Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz

**Comment by yurivict** [comment]
I don't really have resources to debug this at this time.

**Comment by clangen** [comment]
Yeah, no worries. I'll likely end up disabling the scrollbars again until I can figure out how to repro.

**Comment by yurivict** [comment]
> until I can figure out how to repro.

How to reproduce:
1. Install FreeBSD in the VM
2. Install musikcube in it (cd /usr/ports/multimedia/musikcube && make install)
3. Observe the crash

Better disable it now, then reproduce and fix it, then reenable it again.

**Comment by clangen** [comment]
Yeah, I did a fresh install of FreeBSD about two weeks ago with VirtualBox and can't repro. I also tried a fresh install of TrueOS, no problems there either. :thinking:

**Comment by yurivict** [comment]
2 weeks ago it worked on FreeBSD. Try now with the port as it is now.

**Comment by clangen** [comment]
Yeah, two weeks ago it had the problematic code commented out. I just recently added it back.

I've been installing FreeBSD from the prefab VM images provided on the website. I'll do an installation from scratch this evening and see if I can repro that way -- maybe that's the missing piece of the puzzle!

**Comment by ghost** [comment]
I hope we can get this figured out, let me know if I can do anything to help. What about a digitalocean droplet would that surface in figuring it out? I could spin up a FreeBSD 12 droplet for a day or two and let you use it for debugging, give you root. Just send me a public key if you want me to do that.

**Comment by clangen** [comment]
Still not having any luck reproducing -- this is a fresh OS -> straight to ports dir -> make install:

![image](https://user-images.githubusercontent.com/2031666/50908690-186de200-13df-11e9-9d6a-8f4f88c506b9.png)

This is one of the more frustrating bugs I've worked on in a while :)

I may take you up on your droplet offer -- I can email you my public key this evening. I also completely rewrote the section problematic code from scratch last night using some more appropriate curses APIs I found while re-reading the manpages. If you have a few minutes, it may be worth re-building from source against the `master` branch to see if it's fixed once and for all.

**Comment by ghost** [comment]
Good news, I just compiled master and it's working as it should. Could you release a bug fix release so we can get this into FreeBSD?

![2019-01-09-204802_1668x1014_scrot](https://user-images.githubusercontent.com/980/50940690-eb0d4c80-144f-11e9-81e0-310a25dcae0d.png)

**Comment by clangen** [comment]
Great news! Just pushed a new release:

https://github.com/clangen/musikcube/releases/tag/0.60.2

**Comment by clangen** [comment]
Resolving this issue!

**Comment by barracuda156** [comment]
> I don't think I ever asked this before -- what type of hardware are you seeing this issue on? You said the processor was 64-bit, but what type of processor is it? I've only ever tested on x86-64, but not arm64 or sparc64. Maybe I we have an endianness problem somewhere.

@clangen Has it been tried on a BE system reasonably recently? Crashed for me on PowerPC.
Would be nice to have it working.
