### ISSUE TITLE
Streaming to another PC's instance of musikcube

### ISSUE THREAD

**Issue by kastidad** [clangen/musikcube#229]
I think I misundestood when I read the project description or maybe it is a feature that I don't know how to use.

I mean is the main way I plan to use musikcube is to use my local instance of it to receive the stream from another PC's instance of musikcube (media server with all the files).

I think similar behavior to the android app but between Windows/Linux instances in different PCs.

Otherwise, how can we use the server? Hope you can clarify.

Thanks and BTW awesome project!

**Comment by bleuge** [comment]
Me and some friends are also looking for this info, as I read the description, but don't know the exact features right now, thanks!

**Comment by clangen** [comment]
This is something we want to support eventually. It should be totally possible, but will require a substantial amount of changes to the app. There's another thread with a bunch of info, including history about how we wound up in this situation:

https://github.com/clangen/musikcube/issues/204

https://github.com/clangen/musikcube/issues/204#issuecomment-433681135

Happy to answer any other questions related to this.

**Comment by clangen** [comment]
Closing in favor of https://github.com/clangen/musikcube/issues/204
