### ISSUE TITLE
Please add missing #include <functional>

### ISSUE THREAD

**Issue by yurivict** [clangen/musikcube#230]
Every time ```std::function```, ```std::hash``` or any other class or function from ```<functional>``` is used it should be included. For example, ```src/core/library/ILibrary.h``` uses ```std::function``` and doesn't have ```<functional>``` included.

Please make sure it is included where used.

**Comment by yurivict** [comment]
Also, src/plugins/sndioout/SndioOut.cpp uses ```std::unique_lock``` and deosn't have ```<mutex>``` included.

**Comment by clangen** [comment]
Pushed a fix. `<mutex>` is included in `SndioOut.h`, where the mutex var is defined so that should be fine! :)

**Comment by yurivict** [comment]
```src/musikcube/app/overlay/LocaleOverlay.cpp``` also uses ```std::function``` and doesn't have the include.
