### ISSUE TITLE
Run musikcubed in foreground

### ISSUE THREAD

**Issue by hectorm** [clangen/musikcube#231]
Hi, I'm trying to run musikcubed with runit for a Docker container, but this [requires that the process be kept in the foreground](http://smarden.org/runit/faq.html#create).

Is there any way to do this? It seems that this feature is not yet implemented.

**Comment by clangen** [comment]
Just added it -- will be available in the next release:

https://github.com/clangen/musikcube/commit/f67f310cdca12353e2dd19e84459061610704c14

You'll be able to do: `musikcubed --foreground`

**Comment by hectorm** [comment]
That was fast. Thanks!

**Comment by hectorm** [comment]
Hi, I just wanted to say that I tried the new version and it works perfectly. I have already updated the [Docker container](https://github.com/hectorm/docker-musikcube).

**Comment by clangen** [comment]
This is awesome, thanks for reporting back! :)
