### ISSUE TITLE
Adding F1 help with every valid key in that moment.

### ISSUE THREAD

**Issue by bleuge** [clangen/musikcube#238]
I think I've not coded C++ last 20 years :D, but I can read it and I can code in other languages. 

I want to add some kind of help in every screen, I love the functionality as is, but adding some contextual help would make it a really lot easy to use for new users. For example I suggested it to a friend and he told me the same I thought, It's great but very strange to use, don't know how to use all the features.

So, could you point me in the right direction in the source to look for ways to do this?, of course I could read it entirely, I just want some first indications :D

**Comment by clangen** [comment]
You can press `?` in most places to get keyboard help now.
