### ISSUE TITLE
Allow playing music while metadata is syncing

### ISSUE THREAD

**Issue by bleuge** [clangen/musikcube#239]
Many users have pretty big collections, 
maybe syncing metadata could be run in another thread, so you can play music while?

thanks for reading!

**Comment by clangen** [comment]
This is already supported across all platforms and all output drivers -- it's tested regularly on Windows, Linux, macOS and FreeBSD. What platform are you having problems with? :)

**Comment by bleuge** [comment]
You are right, it must be another bug. This happened to me yesterday, when syncing finished (160.000mp3s), I tried again but no music played, the interface worked, but double clicking, enter or space in the playlist didn't starting playing. I thought a problem with playing engine. 
Restarted musikcube and it played perfectly.
I don't know if I can check any debug log or whatever to look for more info about this kind of unknown problems. Thanks!!

**Comment by clangen** [comment]
Hmm, strange. Out of curiosity, how do you find performance with 160k files? Does the app seem to handle things reasonably well? I've only tested this many songs artificially, so I'm curious how well it works in the real world.

**Comment by bleuge** [comment]
It works perfectly, everything is fast, once synced. No problems navigating folders or whatever.
Do you want me to put 10-20K mp3s in the same folder to see how it works?
Thanks!

**Comment by bleuge** [comment]
I've checked cache, musik.db is 753 and thumbs folder is 4.7GB.
Do you think is needed to cache covers?, they are already in my folders and inside my mp3s. 
Also, i've to check it but, could I have cache in a definable drive/folder? I prefer this to be out of my SSD system drive.

**Comment by clangen** [comment]
That's great to hear it performs well at that scale! Hmm, yeah, we should probably (1) add the ability to disable thumbs extraction, and (2) allow the user to specify the data directory. I'm surprised that 753 thumbnails is 4.7GB though. Perhaps a big chunk of that is the size of the metadata database itself? We do some pretty aggressive indexing to keep things snappy, but it will definitely increase the size.

For now you can move the `~/.musikcube` directory to a different drive, then symlink it and the app should still be happy. Something like:

1. stop musikcube
2. `mv ~/.musikcube /mnt/wheverever/musikcube`
3. `ln -s /mnt/wherever/musikcube ~/.musikcube`
4. start musikcube

**Comment by bleuge** [comment]
I am using it in Windows10 full updated, with an external Topping D10 DAC

No, I meant, musik.db file (nice you used sqlite), is 753MB, the thumbs subfolder contains 8176 images occuping 4.9GB (I added more music yesterday :D)

Thanks!

**Comment by bleuge** [comment]
Now it seems I got a real bug in syncing :D 
Basically, i can move in the panels, but only the selected entry is showed, strange... 
Attached some screenshots
![musikcube](https://user-images.githubusercontent.com/26274092/52356402-0d34c300-2a2c-11e9-8b27-ddd0fc38959b.png)

**Comment by clangen** [comment]
This should be fixed in the most recent builds, I believe. If you're still using musikcube and still see this issue, please re-open.

**Comment by bleuge** [comment]
ok, thanks!, I'll delete de DBs and check again with my collection, regards!
