### ISSUE TITLE
Ogg Opus Files Dont Show

### ISSUE THREAD

**Issue by ibrokemypie** [clangen/musikcube#240]
On macOS Mojave, installed via homebrew. MP3 files show fine, but the majority of my library which is in ogg opus just doesnt show in the library viewer.

**Comment by ibrokemypie** [comment]
Actually it seems they do get added and do play, they just dont get sorted in the library by their tags

**Comment by clangen** [comment]
Oh, I see, tag parsing failed? That's possible, I don't have tons of Opus files. Is there any way you can share a file with tags that don't seem to be working?

**Comment by ibrokemypie** [comment]
sure, try this one
[01 Tree Village.ogg.zip](https://github.com/clangen/musikcube/files/2820101/01.Tree.Village.ogg.zip)

**Comment by clangen** [comment]
Ah! So... `taglib` (our tag parsing library) sees the `.ogg` extension and assumes it's a `vorbis` file, then fails when it's not. When this happens, we should probably detect the error and then check to see if it's an `opus` file.

Are there any other file formats that commonly have an `.ogg` extension that may not be `vorbis`? :thinking:

**Comment by ibrokemypie** [comment]
yeah, ogg is a container and can really contain any formats (mp4, aac, mp3 etc), though usually contains opus, vorbis, flac or speex
would probably make more sense to query the audio encoding from the file than to have a predetermined list of encodings based on extension

⁣Get TypeApp for Android ​

**Comment by clangen** [comment]
Got it. I modified the `taglib` parser reader plugin so it can detect `opus` files in an `ogg` container -- your example file seems to parse fine now! I also made it such that as soon as I can get examples of other formats in `ogg` containers it should be trivial to add support to them as well.

**Comment by ibrokemypie** [comment]
seems to be fixed after re-adding the library on latest head, thanks!

**Comment by clangen** [comment]
Thanks for confirming the fix!
