### ISSUE TITLE
Option to sort by AlbumArtist instead of Artist

### ISSUE THREAD

**Issue by ibrokemypie** [clangen/musikcube#242]
It would be very very helpful to be abel to switch to albumartist sorting a the artist field often contains things such as "feat" or "with" other artists, splitting up albums over multiple "artists", something that albumartist remedies

**Comment by clangen** [comment]
You're talking about the category list in the left pane, right? You can switch to album artists by pressing the `4` key when in browse view. `1` through `5` are predefined, and `6` shows you a list of possible categories, minus playlists.

**Comment by ibrokemypie** [comment]
ah i see, sorry!
