### ISSUE TITLE
Unable to rescan

### ISSUE THREAD

**Issue by ogrim** [clangen/musikcube#243]
I created a new subfolder into my music folder. My music folder is added to the musikcube indexed paths from before. The new subfolder appeared in directory view. Then I added one track to this subnew folder, but musickube didn't find the track.

It seems since last I updated (some releases ago) the console has gone away, so I cannot issue a rescan myself anymore. The track only appeared after restarting musikcube.

Is there still any option to issue the rescan manually?

I am running 0.62.0.0

**Comment by clangen** [comment]
Yep! Pressing `CTRL+r` will pop up a menu that allows you to "scan for changes" (only add new files or update files that seem to have changed) or "rebuild library" (forces a refresh of all music).

Closing this issue -- please re-open if you're still having problems.

**Comment by ogrim** [comment]
Fantastic, thank you 👍
