### ISSUE TITLE
musikdroid freezes when playing some songs

### ISSUE THREAD

**Issue by hectorm** [clangen/musikcube#250]
Probably in other situations the issue will also occur, but in my case I need to take the following steps:
1. Enable "random" in musikdroid.
2. Make a search that returns exactly 2 results.
3. Try to play the first result.
4. musikdroid freezes and I have to kill the app.

I am using version 0.63.0 of musikcube and musikdroid, my smartphone has Android Pie and I do not see any error in logcat.

**Comment by clangen** [comment]
Wow, this is apparently a super old bug. Thanks for reporting it. #https://github.com/clangen/musikcube/commit/07ec3fcce98228f67bcf7d1bc7a651610c07590b

This will be part of 0.64.0, which will likely be released within the next couple days!

**Comment by hectorm** [comment]
Thanks for fixing the problem.

I have a musikcube instance on my home server and I use musikdroid daily for over a year and I am very happy with this project. Keep up the good work!
