### ISSUE TITLE
Tray icon isn't shown when minimize to tray is enabled

### ISSUE THREAD

**Issue by adem4ik** [clangen/musikcube#251]
**Preconditions:**
- Windows 10 x64
- musikcube 0.64.0
- "minimize to tray" is enabled

**Steps:**
1) Start Musikcube
2) Minimize it window

**Result:** Musikcube is minized to tray, but there is no icon.
![Screenshot_1](https://user-images.githubusercontent.com/4707112/54666549-77e51e00-4b03-11e9-8334-705567e028f9.jpg)

**Expected result:** Musikcube is minized to tray, its icon is shown as it was in 0.51.0.
![Screenshot_2](https://user-images.githubusercontent.com/4707112/54666546-7582c400-4b03-11e9-8824-39be7b1d9424.jpg)

**Extra info:**
- The last working version is 0.51.0. Since 0.60.0 till 0.63.0 minimizing to tray didn't worked at all. Since 0.64.0 minimizing is started to work.

- Also it may be related to another issue:
0.51.0
![Screenshot_3](https://user-images.githubusercontent.com/4707112/54666925-897af580-4b04-11e9-908d-a6d3a0c0a2de.png)
0.64.0
![Screenshot_4](https://user-images.githubusercontent.com/4707112/54666929-8e3fa980-4b04-11e9-8910-feaf2e4cebf0.png)

**Comment by clangen** [comment]
Yikes. Just published 0.64.1, which should fix the issue. Thanks for reporting! :)

**Comment by adem4ik** [comment]
Thanks, fix is confirmed.

**Comment by skygate2012** [comment]
@clangen This issue is occurring again on the latest version (0.96.7)

**Comment by clangen** [comment]
Got it, this has been fixed and will roll out in the next release.
