### ISSUE TITLE
Tags from AAC files are not recognized

### ISSUE THREAD

**Issue by zais** [clangen/musikcube#252]
Example of metadata extracted from file: [here](https://www.get-metadata.com/result/8805ce74-3318-42d5-9c2b-8621faa5b09e)
In musikcube this track shown just as filename.

**Comment by clangen** [comment]
This is totally my fault, but the link is dead and I can't repro the issue with any of my AAC files. Closing this for now. Please re-open if you can re-upload a broken file.
