### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by mohsenmgr** [clangen/musikcube#253]
When I try to install musicKube on my MX-Linux via the deb package it gives me these errors:
musikcube : Depends: libboost-thread1.63.0 but it is not installable
             Depends: libboost-system1.63.0 but it is not installable
             Depends: libboost-filesystem1.63.0 but it is not installable
             Depends: libev4 but it is not going to be installed

These unmet dependencies are wrong because libboost is not currently on version 63.0 they are on version 62.0 so these dependencies are wrong.

**Comment by clangen** [comment]
Hmm, we don't explicitly support that Linux distro, but it looks like the Ubuntu `Zesty` deb uses boost 1.62.0. Have you tried that? https://github.com/clangen/musikcube/releases/download/0.65.0/musikcube_0.65.0_ubuntu_zesty_amd64.deb
