### ISSUE TITLE
musikcube_win32_0.64.1 VCRRuntime140.dll not found.

### ISSUE THREAD

**Issue by benoit-pereira-da-silva** [clangen/musikcube#254]
Release : musikcube_win32_0.64.1
On a fresh new Windows 10

Cannot run the musikcube. VCRRuntime140.dll not found.

<img width="418" alt="win10_VCR" src="https://user-images.githubusercontent.com/963307/56902846-68120f80-6a9b-11e9-8a73-883ee75dbe74.png">

**Comment by benoit-pereira-da-silva** [comment]
I got the same issue with musikcube_win32_0.64.0.

**Comment by benoit-pereira-da-silva** [comment]
Installing [v_redist.x86](https://www.microsoft.com/en-us/download/details.aspx?id=52685) did fix it

**Comment by clangen** [comment]
@benoit-pereira-da-silva thank you for bringing this to my attention. While your fix works, it is not my intention to require installation of the Visual C++ redist library. I'll try to remove this dependency in the next release of musikcube.

Re-opening this ticket for tracking purposes.

**Comment by clangen** [comment]
https://github.com/clangen/musikcube-bin/commit/b825e6066d88535aad8c27d9131632f88e90510c
https://github.com/clangen/musikcube-bin/commit/31cd7109785075fc18ddb6319440c5cbb305e702
https://github.com/clangen/musikcube/commit/34e383bb2cad38f195da8bac93fdfd372798426f
https://github.com/clangen/musikcube/commit/9bbd1f01405578d8fa73705aa22a88c7219f0856
