### ISSUE TITLE
Get currently playing song via CLI

### ISSUE THREAD

**Issue by Re4ctor** [clangen/musikcube#256]
There is a way to know the current playing song from cli?

**Comment by M1ndo** [comment]
Any New Updates On This Request?

**Comment by Barbaross93** [comment]
You could use playerctl: https://github.com/altdesktop/playerctl . Musikcube reports to MPRIS, so you should be able to not only query info, but also pause/play, next track, etc. At least this is true on Linux, not sure about Mac or Windows.

**Comment by clangen** [comment]
Depends on the platform -- but on Linux you can use `playerctl` like @loki7990 suggested.

**Comment by Else00** [comment]
How can i get it on macOS? becase musikcube is not registering the playback on MPNowPlayingInfoCenter, so I cannot get the song info or control it using nowplaying-cli
