### ISSUE TITLE
Possible to hide command bar?

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#257]
Wondering if its possible to hide the command bar on the bottom.

**Comment by clangen** [comment]
Looked into this at some point, ultimately decided against it. Need to go back and remember why. Will keep the issue open for now until I can provide more context.

**Comment by clangen** [comment]
The problem was that it was confusing when actually in command mode; but I think there's a good compromise where the command bar only becomes visible when command mode is on. I'll add a new setting for this as part of the next release.
