### ISSUE TITLE
Config from file

### ISSUE THREAD

**Issue by majkinetor** [clangen/musikcube#259]
It would be highly needed to be able to configure musikcube via config.

I am using WIndows version and it looks like stuff is in Registry. This prevents me to have multiple copies of musikcube, each with its own library, lastfm user etc. 

Furthermore, this is great for testing.

**Comment by clangen** [comment]
Hello! `musikcube` doesn't use the registry for configuration -- all config data can be found in `c:\Users\username\AppData\Roaming\musikcube`.
