### ISSUE TITLE
Wiki Addition

### ISSUE THREAD

**Issue by n8ta** [clangen/musikcube#266]
I think an explanation of how to turn off mission controls override of ^UP and ^DOWN on macOS would be useful to add to the userguide. I think most users will find that ^UP and ^DOWN are not triggered (at least in iTerm2) unless the macOS shortcut is disabled.

I wrote a quick explanation (line 3) here:
```
    - `M-UP` (`^UP` on macos) move the selected track up
    - `M-DOWN` (`^DOWN` on macos) move the selected track down
      - On macOS you may need to disable mission control's keyboard shorcuts in System Preferences > Mission Control > Keyboard and Mouse Shortcuts for `^UP` and `^DOWN` to work
    - `DEL` (`BACKSPACE` on macos) in the tracks pane: delete the selected track
- `d` browse by directory
- `x` jump to playing artist/album/genre in browse view

```

**Comment by clangen** [comment]
Nice! Thanks for the addition, and apologies for the delay adding this change. 

https://github.com/clangen/musikcube/wiki/user-guide
