### ISSUE TITLE
MPRIS support (Linux only)

### ISSUE THREAD

**Issue by brunosmmm** [clangen/musikcube#267]
Hello, I've just started using musikcube and I really enjoy the feature set and simplicity. However, a minor thing that I'm missing is MPRIS (https://specifications.freedesktop.org/mpris-spec/latest/) support; most players in linux that I've encountered before implement MPRIS. I do use this interface for both control & information and would expect that many other users would benefit from it.
Was there ever any plans for this functionality? (didn't see any mentions in issues). I'd be willing to contribute and implement such functionatlity, however, looking at the project hierarchy I'm not 100% positive in which of the major component such functionality should go.

**Comment by clangen** [comment]
Hey! MPRIS support would be great -- I didn't even realize it was a thing. Support for this sort of thing would probably be best implemented as a plugin. We have an `IPlaybackRemote` interface, which is useful for two things:

1. You can use it be notified when playback state changes
2. It can supply your plugin with an `IPlaybackService` interface, which can be used to control playback.

Creating a plugin is slightly convoluted, but not terrible if you've used `CMake` before. The most straight forward example of `IPlaybackRemote` is probably in the server plugin, here: https://github.com/clangen/musikcube/blob/master/src/plugins/server/main.cpp

First, you'll need to define and export an `IPlugin` interface that describes your plugin, for example:

1. https://github.com/clangen/musikcube/blob/master/src/plugins/server/main.cpp#L152
2. https://github.com/clangen/musikcube/blob/master/src/plugins/server/main.cpp#L172

Next, you need to register as a playback remote. To do that you implement the `IPlaybackRemote` interface, and export it as above:

1. https://github.com/clangen/musikcube/blob/master/src/plugins/server/main.cpp#L59
2. https://github.com/clangen/musikcube/blob/master/src/plugins/server/main.cpp#L176

After that, your `IPlaybackRemote` will receive a pointer to an `IPlaybackService` that can be used to control playback, via this method you'll need to implement:

1. https://github.com/clangen/musikcube/blob/master/src/plugins/server/main.cpp#L95

After you have your plugin.cpp created, you'll need to make a `CMakeLists.txt` for it. You should be able to pattern match an existing plugin, then register the plugin in the app-wide `CMakeLists.txt` so it gets included in the build:

1. https://github.com/clangen/musikcube/blob/master/CMakeLists.txt#L85

A couple other links that may be helpful:

1. IPlaybackService.h: https://github.com/clangen/musikcube/blob/master/src/core/sdk/IPlaybackService.h
2. IPlaybackRemote.h: https://github.com/clangen/musikcube/blob/master/src/core/sdk/IPlaybackRemote.h

**Comment by brunosmmm** [comment]
Thanks for the detailed explanation!
I'll start looking into it
