### ISSUE TITLE
Installation not explained well enough on Linux, not at all user friendly.

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#272]
I am relatively new to the CLI, and I am slowly moving from beginner to intermediate, so I thought that I would try using CLI programs, to further improve my understanding. This program looks looks great, but the explanation of how to do the installation on Linux, is quite literally all over the place.

Whilst MacOS, Windows, FreeBSD, and Raspberry Pi have obvious sections close at hand, there is no section listed for Linux. There are in fact additional steps with the Linux installation that are not very well explained, and a further process of discovery which is not at all transparent.

If this program IS cross-platform, then the process for installing it on all platforms should be explained simply, and in the same place.

**Comment by clangen** [comment]
Sure, happy to help try to bridge some gaps in the documentation, but I think you'll need to provide me with a little bit more information about what specifically you had problems with.

The installation guide has quick instructions for many commonly used distributions -- just find the "Linux" section: https://github.com/clangen/musikcube/wiki/installing

For distributions that we don't provide binaries for, you'll need to build musikcube yourself. There are relatively detailed instructions for many popular operating systems and Linux distributions here: https://github.com/clangen/musikcube/wiki/building ... you should be able to adapt these to fit your distribution with a little bit of research.

**Comment by MarkusReynolds1989** [comment]
I really appreciate this tool so I don't want anyone to think I'm ungrateful, but I think that the inclusion of all the dependencies required might be a huge benefit. I'm trying to install it right now but I'm missing a ton of packages (I had to install lib boost and libev).

**Comment by clangen** [comment]
Thanks for the feedback! The list of dependencies is already listed in the instructions I posted above: https://github.com/clangen/musikcube/wiki/building

> install the following libraries and their development packages: `cmake boost libogg vorbis ffmpeg ncurses zlib asound pulse libcurl libmicrohttpd libmp3lame libev4 taglib`

It's starting to sound like while the requested information is already available, it's difficult to discover. Do you have any suggestions for better ways to surface this information so it's easier to find? That is, where should the information live and how should it be formatted for maximum discoverability?

**Comment by MarkusReynolds1989** [comment]
Hey Clangen, thanks so much for the feedback. Is there anyway you could put that in the readme next to the Ubuntu installation instructions? I actually gave up earlier and just used snap to get a different app but I am going to go back and try now that I saw that. I apologize I didn't look closely at your response.
