### ISSUE TITLE
tlist.h missing (Make issue)

### ISSUE THREAD

**Issue by Darquedante** [clangen/musikcube#273]
Building on a 32bit MX Linux (stretch)
I fully expect that I'm doing something stupid somewhere.
----
Found it outside of its call location, going to copy it over and attempt to build again.
My embarrassment lead me to edit the post prior to seeing if the fix worked.

still saying the same thing even if I spray the file everywhere. I am doing something wrong.

-----
Scanning dependencies of target taglibreader
[ 22%] Building CXX object src/plugins/taglib_plugin/CMakeFiles/taglibreader.dir/stdafx.cpp.o
[ 23%] Building CXX object src/plugins/taglib_plugin/CMakeFiles/taglibreader.dir/taglib_plugin.cpp.o
In file included from /home/demo/Projects/musikcube/src/plugins/taglib_plugin/taglib_plugin.cpp:36:0:
/home/demo/Projects/musikcube/src/plugins/taglib_plugin/TaglibMetadataReader.h:48:30: fatal error: taglib/tlist.h: No such file or directory
     #include <taglib/tlist.h>
                              ^
compilation terminated.
src/plugins/taglib_plugin/CMakeFiles/taglibreader.dir/build.make:86: recipe for target 'src/plugins/taglib_plugin/CMakeFiles/taglibreader.dir/taglib_plugin.cpp.o' failed
make[2]: *** [src/plugins/taglib_plugin/CMakeFiles/taglibreader.dir/taglib_plugin.cpp.o] Error 1
CMakeFiles/Makefile2:295: recipe for target 'src/plugins/taglib_plugin/CMakeFiles/taglibreader.dir/all' failed
make[1]: *** [src/plugins/taglib_plugin/CMakeFiles/taglibreader.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by clangen** [comment]
Hello! Happy to try and help. Which Linux distribution are you using?

Generally I recommend installing taglib using your distribution's package manager, but there are a couple older versions of Ubuntu that ship with an incompatible version of taglib, so it's also included in the musikcube source base for these cases. Yeah, sorta confusing.

I'd first recommend making sure taglib and its headers are already installed on your system. For example, on Ubuntu you should be able to do `sudo apt install libtag1-dev`.

If after installing taglib you still have issues, you can try to force usage of the bundled taglib, but that will require some minor surgery to CMakeLists.txt. Let me know if you're still having problems and I can help you set that up.

**Comment by Darquedante** [comment]
I was using MX Linux 18.3 which is a custom distro based on Debian Stretch, but Systemd-free. libtag1-dev was not installed at the time of attempted compile.

Started fresh. MX Linux 19 Beta 3 amd64 build.
Worked fine with the libtag1-dev install prior

Please add libtag1-dev to the required lib and dev packages

"
linux and bsd

    install the following libraries and their development packages: cmake boost libogg vorbis ffmpeg ncurses zlib asound pulse libcurl libmicrohttpd libmp3lame libev4 taglib 

"

**Comment by clangen** [comment]
Fixed in the docs.
