### ISSUE TITLE
Raspberry Pi 4: Compiling issue

### ISSUE THREAD

**Issue by LukeZBaker** [clangen/musikcube#274]
I am trying to compile the source code on a Raspberry Pi 4 running Raspbian Buster. The reason I'm trying to compile is because musikcube_0.65.0_rpi_stretch_armhf.deb won't install with the Raspberry Pi 4, as it's built against different libraries than the supplied Pi 4 Raspbian uses.

I've got all the necessary libraries installed on the Pi 4. Running make gets right to 99% but fails at the linking CXX executable stage with the following error:

/usr/bin/ld: ../../bin/libmusikcore.so: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../bin/libmusikcore.so: undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../bin/libmusikcore.so: undefined reference to `__atomic_exchange_8'
collect2: error: ld returned 1 exit status
make[2]: *** [src/musikcube/CMakeFiles/musikcube.dir/build.make:982: bin/musikcube] Error 1
make[1]: *** [CMakeFiles/Makefile2:190: src/musikcube/CMakeFiles/musikcube.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Any help in getting the source to compile would be great! musikcube would be awesome on the Pi 4.

**Comment by clangen** [comment]
Oh man, we absolutely need to support the RPI4. I don't have one yet, but am planning to get one soon. I did a bit of searching around -- can you try something for me?

In the root directory of the repo there's a file called `CMakeLists.txt`. In there, on line 50, is this line:

```
set (musikcube_LINK_LIBS ${BOOST_LINK_LIBS} dl curl pthread crypto)
```

Can you try to change it to the following, then re-compile and see if it works?

```
set (musikcube_LINK_LIBS ${BOOST_LINK_LIBS} dl curl pthread crypto atomic)
```

**Comment by LukeZBaker** [comment]
Absolutely marvellous, with that line change and following your Linux wiki instructions, musikcube works on the RPI4!

On the RPI4 it's definitely worth running the make command with say make -j4 so that it uses all the cores when compiling. I know there's a lot of folk out there who forget about the -j flag (maybe worth a mention in the wiki notes?).

I've now got to figure how to get musikcube playing to my Bluetooth speaker. Installing Pulseaudio on the RPI4 makes sound only go through HDMI (at least it does on my RPI4). I know musikcube lets you change the output driver to AlsaOut rather than Pulseaudio, but I need to find the right output device. But that's a different matter, and something I'll try to work out.

**Comment by clangen** [comment]
Awesome to hear that small tweak helped it compile successfully! Instead of updating the wiki, I'll figure out how to fix it properly so there aren't any additional steps for the RPI4 and just release a new version. I ordered one tonight, and it should show up next week sometime.

As for output device selection -- Pulse *should* support Bluetooth speakers in most cases. Below `output driver` in the settings screen there is an `output device` selector -- in theory your Bluetooth speaker should show up there and be selectable.

**Comment by clangen** [comment]
https://github.com/clangen/musikcube/commit/0d150424830b36eb83c8081925f729dbd4ebde1f -- we'll now link against `atomic` for Linux builds across all platforms. No special setup necessary for RPI4 any longer. Thanks for bringing this to my attention!
