### ISSUE TITLE
[Request] Able to rate songs in the library

### ISSUE THREAD

**Issue by githubdevuser** [clangen/musikcube#276]
I have tons of musics, it will be great it there is a rate column (1-5) to rate the songs and to list the songs by rating.

**Comment by clangen** [comment]
This will be part of the next app release.

**Comment by githubdevuser** [comment]
Sorry, but I don't remember how to rate a song... ? And I don't see this possibility in the actions track? Could be great to add it?

**Comment by githubdevuser** [comment]
Ok, I found it, if anybody needs it:
- ability to rate tracks via **r shortcut** in all track list views.
