### ISSUE TITLE
[Playlist] Easy way to access

### ISSUE THREAD

**Issue by githubdevuser** [clangen/musikcube#277]
I discover I can add songs to playlist but how I can launch playlist, in the main window, it will be great to have a place to display the playlist, I don't see anything about playlist in the Wiki.

**Comment by n8ta** [comment]
Press the number 5 it will jump to the playlist area.

**Comment by githubdevuser** [comment]
Thank you! I find out it was written in the wiki: https://github.com/clangen/musikcube/wiki/user-guide:

in the library view:

    b browse view
    n show play queue
    f show album/artist/genre search
    t show track search
    1 browse by artist
    2 browse by album
    3 browse by genre
    4 browse by album artist
    5 browse by playlist
        M-n create a new empty playlist
        M-s save the currently selected playlist
        DEL (BACKSPACE on macos) in the playlists pane: delete the selected playlist
        M-r rename the selected playlist
        M-UP (^UP on macos) move the selected track up
        M-DOWN (^DOWN on macos) move the selected track down
        DEL (BACKSPACE on macos) in the tracks pane: delete the selected track
    d browse by directory
    x jump to playing artist/album/genre in browse view
    M-ENTER show a context menu for the currently selected item (album, artist, genre, track)
    SPACE pause/resume



but it's curious it's not accessible via main link on the app. I use  playlists very often. Thank you !!

**Comment by n8ta** [comment]
@githubdevuser any reason this can't be closed?
