### ISSUE TITLE
If necessary, update FLAC to 1.3.3 and other dependencies

### ISSUE THREAD

**Issue by Some1NamedNate** [clangen/musikcube#279]
The git commit for the FLAC release can be found [here](http://git.xiph.org/?p=flac.git;a=commit;h=f764434a39e8a8715d5871bb263189e5a7298280). New versions for other dependencies (libogg, libvorbis, etc.) should be checked as well.

**Comment by clangen** [comment]
FLAC playback is now handled by the `ffmpeg` decoder. `libvorbis`, `libogg` and other dependencies (including ``ffmpeg`) were upgraded as part of the 0.70.0 release.
