### ISSUE TITLE
[0.70.0] Playback control on Linux failed to register Pause key

### ISSUE THREAD

**Issue by PythonTryHard** [clangen/musikcube#280]
**OS**: `KDE Neon 5.17.1 64-bit` (based on `Ubuntu 18.04 LTS`). System fully updated.
**Release**: v0.70.0 (`musikcube_0.70.0_ubuntu_bionic_amd64.deb`)

**Terminal used**: `Konsole 19.08.2`
**Describe the issue**: `musikcube` does not register the Pause key while registering the Previous and Next key. No logs found in internal log. (Settings -> Logs)

**Comment by clangen** [comment]
Annoyingly, I can't reproduce this issue on either of my Linux installs. Going to keep the issue open for now, but I'm not quite sure what the issue could be. Does the pause key work for you in other apps?

I use the `playerctrl` command; here's a snippet from my i3 config that issues `playerctl play-pause` whenever the `XF86AudioPlay` button is pressed. 

```bindsym XF86AudioPlay exec --no-startup-id playerctl play-pause```

**Comment by PythonTryHard** [comment]
Solved by installing `playerctl`. I didn't have that before, and now it's working properly. Should this be added to FAQ just in case?

**Comment by PythonTryHard** [comment]
Closed by mistake, the pause key works properly for `vlc` which is the only thing I have aside from `musikcube`

**Comment by PythonTryHard** [comment]
Yup, that worked, but since I'm not on `i3` I'm making do with this instead. Some delay but it works
![image](https://user-images.githubusercontent.com/31789326/72239210-d6d7ce80-3612-11ea-9978-7a42069b1f7d.png)
