### ISSUE TITLE
[request] resume playback on startup

### ISSUE THREAD

**Issue by azev** [clangen/musikcube#284]
[request] resume playback on startup

**Comment by gyoza** [comment]
Would love this - or something to remember where you last were in each track -- would make this a joy to use for podcasts.

**Comment by clangen** [comment]
Alright, finally got around to adding this -- it'll be available in the next release as an "advanced" option in the settings screen called "ResumePlaybackOnStartup". Relevant commit: https://github.com/clangen/musikcube/commit/6fd0c537b4f94534c8f2ca41b555593d87288459

**Comment by gyoza** [comment]
<3

**Comment by clangen** [comment]
0.96.6 has been released.
