### ISSUE TITLE
Window size not restored on launch for win32/win64 builds. (Position is OK)

### ISSUE THREAD

**Issue by azev** [clangen/musikcube#287]
[request] remember window position and size

**Comment by clangen** [comment]
This should already be implemented and working on Windows, but it's possible a recent PDCurses upgrade messed it up.

**Comment by azev** [comment]
It remembers the X and Y coordinates but does not remember the width and height.

**Comment by clangen** [comment]
Fixed for the next release. https://github.com/clangen/musikcube/pull/295/commits/1504e48680806f2558d62fe1429ca06d2416401c
