### ISSUE TITLE
Lyrics aren't showing

### ISSUE THREAD

**Issue by smhmd** [clangen/musikcube#294]
I have `navigate_lyrics` mapped to `ctrl+l` (default).

![image](https://user-images.githubusercontent.com/46059092/70913236-ec5ad800-2015-11ea-8b9c-22828b33e642.png)

I also have tracks with embedded and external lyrics (synchronized `.lrc` files), but `ctrl+l` does nothing; even the console, it does not output anything.

![mpv-shot0002](https://user-images.githubusercontent.com/46059092/70914091-925b1200-2017-11ea-84aa-6c7919f8387c.jpg)

**Comment by clangen** [comment]
Thanks for reporting, this will be fixed in the next release! https://github.com/clangen/musikcube/pull/295/commits/3d9549905a7dd967e26d7ac7e3cd8aa37c1ebda5

**Comment by smhmd** [comment]
Sadly, `^l` still does not do anything. Could you send a screenshot on how "navigate lyrics" is supposed to look like? Nothing happens in the slightest. I'm on the latest version.

**Comment by chermy** [comment]
> Sadly, `^l` still does not do anything. Could you send a screenshot on how "navigate lyrics" is supposed to look like? Nothing happens in the slightest. I'm on the latest version.

Agreed, still not work for me, both Ubuntu and Windows with same filename .lrc files.

**Comment by chermy** [comment]
> Sadly, `^l` still does not do anything. Could you send a screenshot on how "navigate lyrics" is supposed to look like? Nothing happens in the slightest. I'm on the latest version.

My friend helped me with this, check this https://newreleases.io/project/github/clangen/musikcube/release/0.90.0
It shows "added a way to add an audd.io API key, if you have one, to fetch lyrics", and Auddio charges: 0+ requests per month - $5 per 1000 requests
So I gave up on this. This tip may help.
