### ISSUE TITLE
Monkey's Audio files fail to decode

### ISSUE THREAD

**Issue by sans-c** [clangen/musikcube#298]
musikcube 0.70.0 on Windows fails to decode/play .ape-files for me. The files decode just fine with other players, mpv-git for example which at the time of writing used ffmpeg version: git-2019-12-15-9fe07908.

Note: I got only one album in this format, maybe .ape in general is fine but there is some weird glitch with this encode in particular. But then again, mpv's ffmpeg doesn't complain...

Here is the relevant stuff from the logs:
> 23:06:57 [info] [LocalFileStream] opening file: somefile.ape
23:06:57 [info] [ffmpegdecoder] parsing data stream...
23:06:57 [info] [ffmpegdecoder] found audio stream!
23:06:57 [info] [ffmpegdecoder] resolved codec: Monkey's Audio
23:06:57 [info] [Streams] found a decoder for somefile.ape
23:06:57 [warning] [ffmpegdecoder] avcodec_decode_audio4() failed
...
23:06:57 [warning] [ffmpegdecoder] av_read_frame() failed: End of file
23:06:57 [info] [ffmpegdecoder] finished decoding.

If you need any more info, let me know. :)

**Comment by clangen** [comment]
This sounds like a good candidate for the next release -- I've already been messing with the ffmpeg stuff so it's pretty fresh in my head. I _may_ have fixed it already, but I'm not sure. Any chance you can provide a sample file that is failing? :)

**Comment by sans-c** [comment]
> Any chance you can provide a sample file that is failing? :)

I invited you to a private repo. Let me know when you got the file and thanks for the quick response.

edit: and a happy new year of course, maybe in advance ;)

**Comment by clangen** [comment]
Got the file, thanks! Unfortunately it still is failing to decode after my recent changes. I'll try to dig a bit in the next couple days to see if I can figure out what's going on. Thanks, and happy holidays! :)

**Comment by clangen** [comment]
Alright, I think I managed to figure out what's going on and have a fix in progress in this PR: https://github.com/clangen/musikcube/pull/300 -- it has the added benefit of upgrading the decoder to use newer, non-deprecated libav (ffmpeg) APIs, which is definitely a bonus. 

I'm currently targeting this for next release, but seem to have a small memory leak I'm struggling to track down; hopefully I'll be able to figure it out soon.

Edit: memory usage seems to be asymptotic, which leads me to believe it's just memory fragmentation. Old versions have the same behavior. This is probably close to good for release.

**Comment by clangen** [comment]
This will be fixed as part of the next release!
