### ISSUE TITLE
"show dotfiles in directory browser" makes mounted drives disappear

### ISSUE THREAD

**Issue by Strappazzon** [clangen/musikcube#299]
## Description

Ticking **show dotfiles in directory browser** makes all mounted drives disappear from the directory browser.

![](https://user-images.githubusercontent.com/19752093/71648733-6672a880-2d08-11ea-8d90-ad0895bdda29.gif)

This does not happen if the option is ticked while browsing other folders.

![](https://user-images.githubusercontent.com/19752093/71648983-337de400-2d0b-11ea-9ca5-af024cc09470.gif)

Restarting musikcube will make them reappear.

## Reproduction steps

1. Open musikcube
2. Go to settings
3. Browse to My Computer
4. Tick **show dotfiles in directory browser**

---

### System information

- Windows 10 x64
- musikcube 0.70

**Comment by clangen** [comment]
Thanks for the report, this has been fixed and will be released in the next version!
