### ISSUE TITLE
Cannot play music on Ubuntu 18.04

### ISSUE THREAD

**Issue by hectorm** [clangen/musikcube#308]
Since 0.80.0, on Ubuntu 19.10 music plays fine when I press the spacebar, however on Ubuntu 18.04 nothing happens.

**Comment by clangen** [comment]
`SPACEBAR` is used to `pause` or `resume` playback. If playback is stopped you need to hit `ENTER` to start. Do you observe the same problem when pressing `ENTER`?

**Comment by clangen** [comment]
I see what's going on -- it looks like I removed an initialization call that's only required in older versions of FFMPEG. I'm going to be releasing a new version tonight or tomorrow to fix a nasty first time run bug, and will include a fix for this.

**Comment by clangen** [comment]
Should be fixed in 0.82.0. Thanks for the report and apologies for the inconvenience -- supporting lots of different versions of different distros can be a pain sometimes. :)

**Comment by hectorm** [comment]
That was fast. I've been using musikcube and musikdroid almost daily for more than two years and I'm very thankful for your project :smile:
