### ISSUE TITLE
Opus no longer recognized (Linux)

### ISSUE THREAD

**Issue by saildata** [clangen/musikcube#309]
When I upgraded last week from `(0.70.0-1 -> 0.80.0-1)` on Arch Linux, my playlists and library shrunk due to missing opus files which are not shown anymore. I checked again today, building from git source/[AUR](https://aur.archlinux.org/packages/musikcube-git/), and confirmed that it is still not working as of `0.82.0` 
 
Is there a feature that I've possibly missed or checkbox to re-enable this support? 
 
Thanks for the project and continued support. I've used it for several years now and it is my favorite music player!

**Comment by clangen** [comment]
Thanks for reporting this! 0.80.0 was a pretty massive release, and it looks like I broke something in a Makefile that caused the tag reader to not recognize some formats on some platforms. I'll try to fix this today to get you back up and running. Apologies for the inconvenience!

**Comment by clangen** [comment]
Fix is here: https://github.com/clangen/musikcube/commit/dbf64775ccee19f60bb78f75dcf90793f2e12312

The release process takes a bit of time, unfortunately.

**Comment by clangen** [comment]
New version published. Thanks again for the report!
