### ISSUE TITLE
Seperate Config File For State

### ISSUE THREAD

**Issue by smhmd** [clangen/musikcube#312]
I try to version control my settings, but it seems that the settings file holds long-lasting, user-configured settings and state that can be changed almost every time you open `musikcube`.

![staging a hunk in git that I always ignore](https://user-images.githubusercontent.com/46059092/73584397-66490280-4498-11ea-8d4a-460962b80c1b.png)

Things like `"LastBrowseCategoryType": "album_artist"` that also do not stick (this setting irritatingly, changes if you close `musikcube` on the filter pane, reopened it, and switch to library) are not settings since they change so easily out of the user's control.

`local`, `theme`, `indexed paths`, and so on, on the other hand, can be moved around from system to system, as well as reason about.

**Comment by clangen** [comment]
Yeah, I like this idea. I'll pick this up as part of one of the next releases.

**Comment by clangen** [comment]
Fixed in https://github.com/clangen/musikcube/commit/b88909d148b8ee852bf478db648a5e905ec96817 -- will be part of the next release.

**Comment by clangen** [comment]
Fixed as part of 0.90.0
