### ISSUE TITLE
musikcubed: running multiple instances 

### ISSUE THREAD

**Issue by kac-** [clangen/musikcube#318]
Probably fastest way would be to make `LOCKFILE` and `/tmp/musikcubed.log` of `musikcubed/main.cpp` relative to `$HOME`.

`env HOME=/tmp/h0 musikcubed` works fine and lets customize listening ports.

I'm having trouble putting together a dev environment so no PR.

---
BTW: thanks for this superb project!

**Comment by clangen** [comment]
Hmm, interesting -- is it common for daemons to run on a per-user basis? In this case I had planned on restricting it to one daemon in the entire system; if multiple daemons are trying to use the same ports, only one will work anyway. 

Maybe a better solution would be to default the `LOCKFILE` to the temp directory, but allow override via environment variable? 

Something like: `env LOCKDIR=/home/clangen/.config/musikcube`

Also, curious what was failing with your dev environment -- happy to try to help debug that. :)

**Comment by clangen** [comment]
This will be part of the next release. You can override the lockfile path via:

`MUSIKCUBE_LOCKFILE_OVERRIDE=/path/to/lockfile musikcubed`

**Comment by kac-** [comment]
Hi,
I somehow missed your previous comments, sorry for that.
Dev environment: IIRC some library, it's ok now.
Environment variable is more appropriate I think.

**Comment by clangen** [comment]
Fixed as part of 0.90.0
