### ISSUE TITLE
isLangUtf8 is incorrect

### ISSUE THREAD

**Issue by tobbez** [clangen/musikcube#324]
Quoting `locale(7)`:

>       If the second argument to setlocale(3) is an empty string, "", for the
>       default locale, it is determined using the following steps:
>
>       1. If there is a non-null environment variable LC_ALL,  the  value  of
>          LC_ALL is used.
>
>       2. If  an  environment variable with the same name as one of the cate‐
>          gories above exists and is non-null, its value  is  used  for  that
>          category.
>
>       3. If there is a non-null environment variable LANG, the value of LANG
>          is used.

Specifying a UTF-8 locale in either of these should be sufficient:

1. `LC_ALL`
2. `LC_CTYPE` (with `LC_ALL` unset)
3. `LANG` (with `LC_ALL` and `LC_CTYPE` unset)

This means that musikcube will refuse to start for some adequate environments (cases 1 and 2 above), and will start but produce incorrect output in some inadequate (e.g. if started with `LANG=en_US.utf-8 LC_CTYPE=C`).

**Comment by clangen** [comment]
Thanks for the bug report and information! I believe I have fixed the bug in this commit: https://github.com/clangen/musikcube/commit/374bbd3452e291058edc1969f38e3e642d729c78
