### ISSUE TITLE
m4a playback & aac and wma track duration display - Linux

### ISSUE THREAD

**Issue by Laetgark** [clangen/musikcube#329]
Hello!

I'm a new user and first of all, I want to say thank you for developing and maintaining such amazing software!

While using musikcube, I encountered 2 issues that I wanted to bring to your attention:

I can't play any m4a file whatsoever. I've tried with several examples, from my own collection of music files and from sample files downloaded online, and nothing worked.

Regarding aac and wma, I found that the track duration information didn't display properly in the play queue, browse or tracks screens, is 0:00 no matter the length of the track. Here's a screenshot:

![Screenshot](https://user-images.githubusercontent.com/63529230/79060764-6e26df00-7c5f-11ea-887d-1a76a6ccb682.png)

I'm using Linux Mint 19.3 and installed musikcube from the .deb package

Thank you for your time!

A little update: I installed musikcube in Archlinux (Manjaro) and reproduced the same issues.

**Comment by clangen** [comment]
I upgraded to a new version of taglib, which may fix this issue in subsequent releases. Would it be possible for me to get a copy of one of these files to test?

**Comment by clangen** [comment]
musikcube 0.93 was just released and contains an updated tag scanner that may fix these issues. Please re-open (and attach a sample file if possible) if this is still an issue.
