### ISSUE TITLE
Musikcube win32 crashes on connection from Musikdroid

### ISSUE THREAD

**Issue by adem4ik** [clangen/musikcube#332]
**OS:** Win10 x64 Pro 1909
**Musikcube:** musikcube_win32_0.90.0
**Musikdroid:** musikdroid_0.90.0.apk
**Connection:** LAN

1) Install Musikdroid, setup connection (IP, port, password, etc) and close
2) Start Musikcube on Windows
3) Start Musikdroid on Android

**Result:** Musikcube crashes.

**Additional info:**
- It happens only in win32 version starting from 0.70.0 to 0.90.0. 
- win32 <=0.65.0 & all win64 versions don't have such issue.

**Comment by clangen** [comment]
Whoa, wild. I can't repro in debug builds, either, which makes me think we're relying on some sort of uninitialized variable. Will continue digging into it.

**Comment by clangen** [comment]
OK, this appeared to be caused by an incorrectly-compiled version of zlib for the Win32 release build. I just released 0.90.1 that should fix this issue. Thanks for the heads up!

**Comment by adem4ik** [comment]
Thank you, issue is fixed now in 0.90.1 win32.
