### ISSUE TITLE
Strip fails in out-of-source build

### ISSUE THREAD

**Issue by yurivict** [clangen/musikcube#335]
https://github.com/clangen/musikcube/blob/master/CMakeLists.txt#L377

```strip-nix.sh``` assumes that the binaries are in ```${CMAKE_SOURCE_DIR}``` but in case of out-of-source build they are not there.

**Comment by clangen** [comment]
Should be fixed by this commit, thanks for the report! https://github.com/clangen/musikcube/commit/836120f02903d4212121d824de6bddf2a2fbe906

**Comment by clangen** [comment]
Released: https://github.com/clangen/musikcube/releases/tag/0.92.0
