### ISSUE TITLE
XF86 Keyboard Symbols Support

### ISSUE THREAD

**Issue by sabrehagen** [clangen/musikcube#337]
Hi,

I'd like to make a feature request: could you please add support for the [XF86 media key symbols](http://wiki.linuxquestions.org/wiki/XF86_keyboard_symbols) for each of the [system-wide hotkeys](https://github.com/clangen/musikcube/wiki/user-guide#system-wide-hotkeys)? The `RCTRL` + `RALT` + `F` combinations change the virtual terminal on Ubuntu and can't be used to control musikcube.

P.S. Thanks for an amazing application. It's the best of its class.

**Comment by clangen** [comment]
Hello! This is already supported in a somewhat roundabout way. 

Right now you can use the included `mpris` plugin, which will be automatically loaded when `musikcube` starts if you have the `libsystemd` package installed on your system.

Using the `mpris` plugin you can control musikcube via `dbus`. Many desktop environments (e.g. KDE) should support this out of the box, but if you're using something like `i3` you can use a program called `playerctl` to control `musikcube` when the media keys are pressed.

For example, here's what I have in my i3 config:

```
 bindsym XF86AudioPlay exec --no-startup-id playerctl play-pause
 bindsym XF86AudioNext exec --no-startup-id playerctl next
 bindsym XF86AudioPrev exec --no-startup-id playerctl previous
 bindsym XF86AudioStop exec --no-startup-id playerctl stop
```

Does this help? :)

**Comment by sabrehagen** [comment]
Yes, this is perfect. I am using `i3` so your config is very helpful. Thank you!
