### ISSUE TITLE
musikdroid crash on attempt to play FLACs under certain transcoding options

### ISSUE THREAD

**Issue by PythonTryHard** [clangen/musikcube#338]
**Version affected**: `musikdroid v0.90`, tested against `musikcube v0.90.1` on Windows 10 (64-bit, `1903`, build `18362.778`). Both binaries are obtained from the respective latest releases.

**Steps to reproduce**:
1. Load up some non-null FLACs into `musikcube`'s library (to prevent surprises)
2. Setup musikcube server and `musikdroid` such that a connection is established.
3. Switch `musikdroid` to streaming mode. Play the FLAC(s).

**Expected behavior**: Files play as normally

**Actual behavior**:
For some settings, `musikdroid` will crash, or will not play. For the sake of convenience, I'll be putting the settings as `(transcoder_bitrate, transcoder_format)`. All logcat logs are obtained from running `logcat *:F` as I have absolutely no experience on how to properly use `logcat`
+ `(*, flac)`: Hard crash

+ `(disabled, mp3)`: Hard crash
+ `(non-disabled, mp3)`: No crash, however file does not play, and length reported as `0:00`

+ `(disabled, opus)`: Hard crash
+ `(non-disabled, opus)`: Normal, file plays, correct length

+ `(disabled, ogg)`: Hard crash
+ `(non-disabled, ogg)`: Normal, file plays, correct length

+ `(disabled, acc)`: Hard crash
+ `(non-disabled, acc)`: Normal, file plays, correct length

All logcat dumps can be found [here](https://gist.github.com/PythonTryHard/6d7537bf2cd6047ade84066429c3fc73)

**Comment by PythonTryHard** [comment]
Issue also occur when server is ran on `KDE neon 5.18.4`

**Comment by clangen** [comment]
Looks like FLAC decoding was completely broken due to recent ExoPlayer ABI changes. I recompiled the FLAC decoder it seems to be working again. https://github.com/clangen/musikcube/commit/f796f6169fde7135d7d903115de7bc3ba240d172

**Comment by clangen** [comment]
Released: https://github.com/clangen/musikcube/releases/tag/0.92.0

**Comment by PythonTryHard** [comment]
Awesome! Thank you!
