### ISSUE TITLE
[request] make execution of strip-nix.sh optional on release builds

### ISSUE THREAD

**Issue by aanderse** [clangen/musikcube#339]
https://github.com/clangen/musikcube/blob/6d04397dd771afc7b28f19936d3037ec0865ae21/CMakeLists.txt#L377

Some Linux distros already manage stripping the binaries so it would be nice if there could be a flag to conditionally disable this.

**Comment by clangen** [comment]
You can now use `cmake ... -DDISABLE_STRIP=true ...` to disable stripping conditionally. 

Commit: https://github.com/clangen/musikcube/commit/c5e1ed8220674c0db8bd10ac02a70d49cec84c2a

**Comment by aanderse** [comment]
Thank you very much @clangen!
