### ISSUE TITLE
Music appears to be corrupted after being downloaded using musikdroid

### ISSUE THREAD

**Issue by PythonTryHard** [clangen/musikcube#340]
**Affected version**: same as #338 

**Step to reproduce**
1. Get some non-null FLACs into `musikcube`'s library.
2. Set transcoding option at `(disabled, flac)` on `musikdroid` 
3. Download the FLAC(s) using `musikdroid`.
4. Playback the resulting file(s) using any music player on the phone.

**Expected behavior**: File(s) plays as normal
**Actual behavior**: File(s) while still being recognized as FLACs by music players, despite being named as `{original_file_name}.flac-local-{number}-{more_number}.mp3`, contains multiple silence/skips.

**Comment by PythonTryHard** [comment]
Tested against some MP3. They too are affected.

**Comment by clangen** [comment]
Sounds bad -- can you tell me what operating system (and version) you're running the server on? Do you have the same problem when simply streaming audio and not explicitly downloading it?

**Comment by PythonTryHard** [comment]
`winver` returns version 1903, build 18362.778. Sorry for getting back to you late, college takes a lot of time.

Same problem does not occur when streaming.

**Comment by PythonTryHard** [comment]
Music is also corrupted if the server is ran on Linux ([64-bit-release of v0.90.0 for Ubuntu `bionic`](https://github.com/clangen/musikcube/releases/download/0.90.0/musikcube_0.90.0_ubuntu_bionic_amd64.deb)). Corruption this time is white/pink noise instead of skips like Windows 10 1903 build 18362.778.

**Comment by clangen** [comment]
This commit should fix the issue, and will be part of the next release: https://github.com/clangen/musikcube/commit/3fa42daba67121d091d46bcfee9e8a32606366c9

**Comment by clangen** [comment]
Released: https://github.com/clangen/musikcube/releases/tag/0.92.0
