### ISSUE TITLE
Erratic behavior of musikdroid on file name/directory when downloading an untagged music file

### ISSUE THREAD

**Issue by PythonTryHard** [clangen/musikcube#341]
**Affected version**: same as #338 and #340 

**Step to reproduce**
1. Get some music files without proper tagging into `musikcube`'s library
2. Download the files using `musikdroid`.
3. Check the download file's name

**Expected behavior**: Only the file name is present
**Actual behavior**: The full path leading to the file is visible ie. `E:\Music\{filename}.{ext}`.

**Comment by PythonTryHard** [comment]
I tested when the server is running on Linux (edit: `KDE neon 5.18.4`) as well, except this time the directory is not escaped, resulting in musikcube making sub-directory after sub-directory until it's "happy" ie. If the untagged file's full directory on the server is `/mnt/Music/subdir1/subdir2/subdir3/filename.ext`, musikcube will download the file to `Download/musikdroid/mnt/Music/subdir1/subdir2/subdir3/filename.ext`

**Comment by clangen** [comment]
Oops, accidentally closed. Re-opening...

**Comment by clangen** [comment]
Fixed in this commit https://github.com/clangen/musikcube/commit/9ff959536d50fb346a19ffbc8cadcd699c10a7b4

Thanks for the report!

**Comment by PythonTryHard** [comment]
Issue is confirmed to be fixed. Thank you!
