### ISSUE TITLE
[Feature request] Dedicated play button?

### ISSUE THREAD

**Issue by lochlainn** [clangen/musikcube#342]
Is there a dedicated button to "play" the selected track? I.e. go to the start of the song that is currently selected/playing, and start play if it isn't already started.

I have been trying to get musikcube to emulate the playback style of winamp/cmus, and this is the last piece I can't find. This is achieved with the "x" key in both of those programs.

Is this already implemented? If not I'll happily take a shot at it myself.

**Comment by clangen** [comment]
Hmm, from the description it sounds like you just need to press `ENTER` to start playback of the selected item, but I get the feeling that's not what you're talking about. Can you describe how what you're requesting is different? :)

**Comment by lochlainn** [comment]
Sure thing. It's probably best described by a couple examples:

Revolution 9 paused -> press play -> play the song from the current point
Currently playing Revolution 9 -> press play -> replay the song from the top
No song selected -> press play -> play the *first item* of whatever view you're in

Basically it's not at all dependent on your current highlighted item, but entirely on what is currently *playing*. I'd be more than willing to take a shot at implementing this, but any pointers you could give me of where to look would be awesome!

**Comment by clangen** [comment]
1. Revolution 9 paused -> press play -> play the song from the current point
    * You should be able to use `CTRL+P` to pause/resume the current song from anywhere in the app. In most contexts `SPACE` will work as well, but may not (for example, if an input field is focused).
2. Currently playing Revolution 9 -> press play -> replay the song from the top
    * If the song is highlighted you can press `ENTER` to restart it from the top. Otherwise you can press `j` (unless you're in an input field, in which case you can press `ESC`, then `j`).
3. No song selected -> press play -> play the first item of whatever view you're in
    * Hmm, interesting. This doesn't exist right now, let me give this a bit of thought.

Just for my reference, setting (3) aside, do (1) and (2) work for you for the other requirements?

**Comment by lochlainn** [comment]
Yes, (1) and (2) are excellent, thank you for pointing them out to me! I'll try playing with those keybindings today.

**Comment by clangen** [comment]
Great! I just added support for this request in this commit, along with a couple other new hotkeys: https://github.com/clangen/musikcube/commit/e4141fb220c6872af73b15f8087b19672724a0c1

It will tentatively be `M-P` (`Alt+Shift+p` on most platforms) while in library browse mode, directory browse mode, or the play queue.

**Comment by clangen** [comment]
Released: https://github.com/clangen/musikcube/releases/tag/0.92.0
