### ISSUE TITLE
[Feature request] (Shuffle) play library

### ISSUE THREAD

**Issue by thriveth** [clangen/musikcube#344]
I really love the Musikcube, but it lacks one feature that I use heavily: Playing (optionally on shuffle) the entire music library. 

My use pattern in players that support it (e.g., Rhythmbox or cmus): I find the songs I want to listen to, queue them up, then when finished playing the queue, the player picks next (optionally random) song from my full library library, and so on till I actively choose otherwise. This allows me to be re-discover and be reminded of music I have not listened to in a while without having to scroll through and pick and choose. I imagine this could be a simple on/off switch (e.g., "continuous") like "shuffle" or "repeat". 

I think Musikcube has the absolutely most beautiful interface of any terminal based player, and a very nice feature set. Adding this feature would allow me to switch to it as my main player.

**Comment by chucku** [comment]
This is also a must-have for me.  
I terms of UI implementation I think it is very useful to be able to see what has just been played as well as what is coming up.  Some implementations of shuffle play jump all over the place and don't allow you to see that.  
A nice-to-have would be something like Clementine's "dynamic random mix" where you don't need to create an "everything" playlist beforehand which can be slow if you have a very large and frequently updated library.

**Comment by clangen** [comment]
While there's currently no dedicated feature to do it you can emulate it with a couple keystrokes:

* `esc` > enter command mode
* `t` > go to all tracks/songs view
* `enter` > start playback
* `,` > shuffle the play queue

It's hard to find a dedicated key binding for each individual action, so I'm curious if that sequence of keystrokes is sufficient for you guys.

**Comment by thriveth** [comment]
@clangen Thanks for your reply,  I missed it when you wrote it. This doesn't seem to cover what I described, though, as it uses the play queue so it doesn't allow me to queue up a few songs and have it continue to play random songs after.

**Comment by crowmagnumb** [comment]
First off, great player, wow.
But like the others here this is how I listen to my collection 95% of the time. Random over everything. So not only is this solution a bit awkward, you also are then stuck with it playing the first track automatically every time. Sure you could skip it but that just makes it extra awkward. Seems like it would be a pretty easy solution to have a key that just started playing the whole collection at random, but haven't looked at the code either.  :) Any +1 for this too.  :)

**Comment by crowmagnumb** [comment]
On the other hand, the queuing in the middle of the random play does seem to work. I queued up something, it played it, and went back to random. But I second the "it would be great to see the songs played". Many times I wonder who is the artist for a song and I have to rush to read the terminal before the song finishes.
