### ISSUE TITLE
[question] Is there plugins or extensions with extra features?

### ISSUE THREAD

**Issue by paulolimac** [clangen/musikcube#345]
Has musikcube some plugins or repositories with (extended) functions?

I'm looking for specific features, like:
- _time strech_ (ie. speed up or slow down without affects pitch)
- _resume_ (ie. to restart and to play at the same last point played when the player was closed)

I looked at https://en.wikipedia.org/wiki/Comparison_of_audio_player_software but musikcube hasn't many informations in this wikipage.

**Comment by clangen** [comment]
Yep, documentation is a bit lacking, but a bunch of example plugins can be found here: https://github.com/clangen/musikcube/tree/master/src/plugins
