### ISSUE TITLE
A way to select specific milkdrop2 presets?

### ISSUE THREAD

**Issue by fadelm0** [clangen/musikcube#347]
Hi,

I saw in the milkdrop2 plugin presets folder there's a lot of presets. Is there a way to select specific presets from within musikcube? It would be nice to select specific ones that we like instead of it just cycling through them automatically.

**Comment by clangen** [comment]
You should be able to press the `L` button in the Milkdrop window to bring up the preset selector. You can press `F12` to get a list of common hotkeys.

**Comment by clangen** [comment]
![image](https://user-images.githubusercontent.com/2031666/82110767-9fc71600-96f5-11ea-804f-4b4e19d4d0f9.png)

**Comment by clangen** [comment]
Closing for now. Please re-open if this doesn't address your issue!
