### ISSUE TITLE
Add option to disable the title/artist on the terminal title/tab

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#348]
Linux Mint 19.3 Cinnamon (based on 18.04)
musikcube 0.90.0
tilda terminal 1.4.1
zsh 5.4.2 (IDK if this is relevant, including it anyway)

@clangen Hi I just updated musikcube and I want to turn off the title/artist on the terminal title/tab, how do I do it?

![Screenshot from 2020-04-27 19-00-20](https://user-images.githubusercontent.com/8528269/80365895-e4138300-88ba-11ea-834c-e65363acb94d.png)

**I just want my terminal title to stay as 'musikcube' with no extra info.**

___

Just an additional note, the title is not even updating properly, it only updates when I go to the settings page.

- change song
- look at title (still the previous song)
- go to another view/page (in my case, the settings page)
- look at title (already shows the current song)

**Comment by clangen** [comment]
Seems like a reasonable request. I'll look into it for the next release. 

Side note: I have also noticed a couple terminal emulators that don't reliably update the title, and I have no idea why.

**Comment by clangen** [comment]
Added an advanced setting called `DisableWindowTitleUpdates` in this commit: https://github.com/clangen/musikcube/commit/6972a1df47e37b4a39d78601e689e245ea5f31b7

This will be in the next release.

**Comment by clangen** [comment]
Released: https://github.com/clangen/musikcube/releases/tag/0.92.0

**Comment by ghost** [comment]
Thank you very much.
