### ISSUE TITLE
Can't play .MP3 files

### ISSUE THREAD

**Issue by caltaojihun** [clangen/musikcube#349]
Musikcube won't play files with .MP3 extension (all caps), but can play .mp3 files just fine! Press enter on the file, nothing happens. Same to .WAV vs .wav

Also if you rename .MP3 to .mp3 then the file will show up in the library twice, one playable and one unplayable. Rebuilding the index doesn't help, I have to remove the folder then adding it again.

I'm using Windows 10, musikcube v0.90.1

**Comment by clangen** [comment]
Yikes, that's an embarrassingly bad bug that I can't believe no one has ever reported before. I'll see if I can get a new release out sometime this weekend. Thanks for the report.

**Comment by clangen** [comment]
Fixed in https://github.com/clangen/musikcube/commit/aefb02ba3cf1126acf31d1cb1315eeaf1ee23e11

**Comment by clangen** [comment]
Released: https://github.com/clangen/musikcube/releases/tag/0.92.0

**Comment by RayyanNafees** [comment]
cant find .mp3 files listed in the local library folder
