### ISSUE TITLE
not all directories are shown in the directory browser (linux)

### ISSUE THREAD

**Issue by spylacopa** [clangen/musikcube#350]
installation via snap on opensuse Tumbleweed,
musikcube 0.92

can't add music dirs since not all dirs are shown in the directory browser.

**Comment by chriztheanvill** [comment]
I have the same issue with Fedora.
I can not add from my second hdd the /media/some_hdd/ dir.

**Comment by clangen** [comment]
Snaps are somewhat sandboxed from the host operating system, so sometimes gymnastics are required to view files mounted on certain parts of the filesystem.

@chriztheanvill in your case the device may be considered `removable-media` based on the mount point... you may need to grant musikcube explicit permission to access that class of devices. You can do that with the following command: `snap connect musikcube:removable-media`

If you do the above, and restart musikcube, can you now view the files?

For reference: https://snapcraft.io/docs/removable-media-interface

**Comment by chriztheanvill** [comment]
Thank you, but I does not worked.

$ snap connections musikcube
Interface        Plug                       Slot              Notes
alsa             musikcube:alsa             -                 -
audio-playback   musikcube:audio-playback   :audio-playback   -
desktop          musikcube:desktop          :desktop          -
home             musikcube:home             :home             -
mpris            -                          musikcube:mpris   -
network          musikcube:network          :network          -
network-bind     musikcube:network-bind     :network-bind     -
pulseaudio       musikcube:pulseaudio       -                 -
removable-media  musikcube:removable-media  :removable-media  manual


$ snap connections
Interface        Plug                       Slot              Notes
audio-playback   musikcube:audio-playback   :audio-playback   -
desktop          musikcube:desktop          :desktop          -
home             musikcube:home             :home             -
network          musikcube:network          :network          -
network-bind     musikcube:network-bind     :network-bind     -
removable-media  musikcube:removable-media  :removable-media  manual

**Edit**: I removed the Snap package and install the rpm package ( I did not noticed ) and works excellent.

**Comment by clangen** [comment]
Glad the RPM version worked out for you in the end! I removed snap support from future versions of the app due to problems like this one. https://github.com/clangen/musikcube/commit/2ad8c17461188f74bd219e40eef96e970e14bc38
