### ISSUE TITLE
How to install on openSUSE

### ISSUE THREAD

**Issue by Nano-Ocelot** [clangen/musikcube#351]
Running Tumbleweed and I've installed all dependencies. But I can't seem to find anywhere that shows how to actually build and install it. The guide just lists the dependencies for building and never elaborates more than that. Any help would be appreciated.

**Comment by clangen** [comment]
I just realized the build instructions were missing a section header, so the build instructions got lumped together in the dependency install section in a strange way. I just updated the docs to make it more clear: https://github.com/clangen/musikcube/wiki/building

Here's a copy/paste:
- `git clone https://github.com/clangen/musikcube.git --recursive`
- `cd musikcube`
- `cmake -G "Unix Makefiles" .`
- `make`
- `sudo make install`
- `musikcube`
