### ISSUE TITLE
Visualizations don't work when using the new Windows Terminal

### ISSUE THREAD

**Issue by jdarias** [clangen/musikcube#356]
No visualization window appears when using the new Windows Terminal console, you can select either gdivis or milkdrop but no window will appear after that... bummer :(

**Comment by clangen** [comment]
Huh, interesting, it seems to work on my end:

![image](https://user-images.githubusercontent.com/2031666/85097763-5a42b080-b1ad-11ea-9645-4b1583630871.png)

Do you have the same problem with the regular (non-cmd.exe) executable?

**Comment by jdarias** [comment]
i'm using -cmd version on windows terminal. 
The non cmd works fine (but opens in its own window) and -cmd works if i double click the exe (it opens in the regular cmd).
I'm on Windows Terminal Version: 1.0.1401.0 downloaded from the windows store
Maybe it's because my windows is in spanish?
Here's my windows terminal profile i've set:
```javascript
{
		"guid": "{f79b116e-f550-be63-2a71-63af5ae4f2c9}",
		"name": "musikcube",
		"commandline": "C:\\tools\\musikcube\\musikcube-cmd.exe",
		"icon": "D:\\aaa Webs\\Recursos\\fugue-icons-3.4.1\\icons\\music-beam-16.png"
},
```

**Comment by jdarias** [comment]
Oh please disregard, i'm a silly person...
the visualization window opened behind my maximised console window and i didn't see it
:(

**Comment by clangen** [comment]
Phew, that's good news, because after a bit of debugging I was all out of ideas. :)

**Comment by clangen** [comment]
Closing!
