### ISSUE TITLE
Linking Volume to System Volume

### ISSUE THREAD

**Issue by hussein-esmail7** [clangen/musikcube#357]
Would it be possible to link the volume inside Musikcube to the system volume? (at least for macOS). Thanks!

**Comment by clangen** [comment]
Can you explain a bit more what you mean by this? Do you mean that you want the system-wide volume keys on your keyboard to control musikcube's volume? :)

**Comment by hussein-esmail7** [comment]
> Can you explain a bit more what you mean by this? Do you mean that you want the system-wide volume keys on your keyboard to control musikcube's volume? :)

Yes, that's what I mean. Sorry for not being clear.

**Comment by clangen** [comment]
You can do this on Linux using the `mpris` plugin that is automatically loaded if you have systemd on your system. On Windows this is accomplished via the `win32globalhotkeys` plugin, and on macOS via `macosmediakeys` plugin. These are all now included in default installations.
