### ISSUE TITLE
Fails to build in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Nano-Ocelot** [clangen/musikcube#361]
When running 'make' I get this error

> 
> [ 27%] Building CXX object src/plugins/server/CMakeFiles/server.dir/HttpServer.cpp.o
> In file included from /home/user/Git/musikcube/src/plugins/server/HttpServer.cpp:35:
> /home/user/Git/musikcube/src/plugins/server/HttpServer.h:60:16: error: ‘MHD_Result’ does not name a type
>    60 |         static MHD_Result HandleRequest(
>       |                ^~~~~~~~~~
> /home/user/Git/musikcube/src/plugins/server/HttpServer.cpp: In member function ‘bool HttpServer::Start()’:
> /home/user/Git/musikcube/src/plugins/server/HttpServer.cpp:325:26: error: ‘HandleRequest’ is not a member of ‘HttpServer’
>   325 |             &HttpServer::HandleRequest,                 /* request handler callback */
>       |                          ^~~~~~~~~~~~~
> /home/user/Git/musikcube/src/plugins/server/HttpServer.cpp: At global scope:
> /home/user/Git/musikcube/src/plugins/server/HttpServer.cpp:359:1: error: ‘MHD_Result’ does not name a type
>   359 | MHD_Result HttpServer::HandleRequest(
>       | ^~~~~~~~~~
> make[2]: *** [src/plugins/server/CMakeFiles/server.dir/build.make:96: src/plugins/server/CMakeFiles/server.dir/HttpServer.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:658: src/plugins/server/CMakeFiles/server.dir/all] Error 2
> make: *** [Makefile:150: all] Error 2

I have all the dependencies as well. Though all the 'libboost' pkgs listed in dependencies are a bit older than the ones provided by Tumbleweed. Tumbleweed has version 71, not 68. Doubt that's relevant, but I figured I'd mention it.

**Comment by clangen** [comment]
Yep, looks like I got this line wrong: https://github.com/clangen/musikcube/commit/e8e9dbd30822be13a8b15a0e705ecee2c76eadd6#diff-c381f47b5a1c83dc019b1ab41a30e7c3R46

I'll try to get this patched up this evening or tomorrow. Thanks for the report!

**Comment by clangen** [comment]
Fixed https://github.com/clangen/musikcube/commit/ae1b2ee233cc6870294190ac57056d799470a431
