### ISSUE TITLE
Lossless audio playing as loud static

### ISSUE THREAD

**Issue by BubbleSpurStarJar** [clangen/musikcube#364]
The OST to the game Redout (specifically the Steam release, more specifically the lossless .wav version that comes included along with the .mp3 version which plays normally) is playing as loud static, while other .wav files play just fine. Perhaps it could be the encoding? Not having this issue with any other of the weirdly large amount of audio players I have installed.

**Comment by PythonTryHard** [comment]
Can you upload the file(s) that are affected, or at least 2 of the affected? That should help the developer.

**Comment by BubbleSpurStarJar** [comment]
I debated doing this, but the music in question is copyrighted and not free, so uploading its files publicly probably wouldn't be a great idea. I will share the files with the developer in private if they ask.

**Comment by RvNovae** [comment]
I can confirm that this consistently happens with lossless formats.

For me it only plays static when starting a track or seeking though.

**Comment by PythonTryHard** [comment]
@clangen Finally found some `wav` file that trigger this behavior on release `0.96.4`. [Here's one of them for debugging (uploaded in good faith).](https://anonfiles.com/b0Z410D9p9/01_Aliesrite_-_brandnew_Wave_wav)

Additional notes: Static plays during the first 2 seconds or so of the track, afterward it plays normally **except** if playback is seeked static will play again then restart to the beginning while the timer continues as if nothing happened.

**Comment by clangen** [comment]
Sorry it took so long to get around to this one, real life got busy for a while. After a ton of debugging, I believe this will fix the issue: https://github.com/clangen/musikcube/commit/1230315a4e9c4cdd75dbf390757688c9914eb018 ... it'll be included in the next release, which should go out before the end of the month.

Edit: follow up commit that seems to work better: https://github.com/clangen/musikcube/commit/e35d11715691c17c8ac5e5db451ddbb860984196

**Comment by PythonTryHard** [comment]
Confirmed to be fixed on my end

**Comment by clangen** [comment]
Fixed in 0.96.6

**Comment by BubbleSpurStarJar** [comment]
Thanks for fixing a poorly diagnosed and explained bug. I'll be more professional about my research in future. Your work is appreciated!
