### ISSUE TITLE
Is musikcube systemd-dependent? 

### ISSUE THREAD

**Issue by smhmd** [clangen/musikcube#365]
I'm on [Artix Linux](https://artixlinux.org/) using `runit` instead of `systemd`. Installing `musikcube` through the AUR (`yay -S musikcube`) and [building from scratch](https://github.com/clangen/musikcube/wiki/building#build-musikcube) both results in the following error:

```make
Scanning dependencies of target mpris
[  0%] Building CXX object src/plugins/mpris/CMakeFiles/mpris.dir/mpris.cpp.o
In file included from /tmp/musikcube/src/plugins/mpris/mpris.cpp:2:
/tmp/musikcube/src/plugins/mpris/mpris.h:10:14: fatal error: systemd/sd-bus.h: No such file or directory
   10 |     #include <systemd/sd-bus.h>
      |              ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/plugins/mpris/CMakeFiles/mpris.dir/build.make:82: src/plugins/mpris/CMakeFiles/mpris.dir/mpris.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:900: src/plugins/mpris/CMakeFiles/mpris.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

I'm not a c/c++ developer, sadly. So, I don't know what to make of this.

(note: you might want to change [AUR command](https://github.com/clangen/musikcube/wiki/installing#arch) to use `yay` instead of `yaourt` which is _dead_.)

**Comment by the-eater** [comment]
musikcube no (we at VoidLinux also have it in the repo: https://github.com/void-linux/void-packages/blob/master/srcpkgs/musikcube/template)

the MRPIS plugin is https://github.com/clangen/musikcube/tree/master/src/plugins/mpris
you might have some luck replacing it with dbus includes instead

**Comment by clangen** [comment]
musikcube should not be strictly dependent on `systemd`. If `systemd` exist on the system it'll build an MPRIS plugin so other apps can remote control playback.

Here's the detection logic: https://github.com/clangen/musikcube/blob/master/CMakeLists.txt#L135

It looks like perhaps you have some systemd libraries installed, but not the header files? Hmm, maybe there's a better way to do this check -- perhaps with `pkg-config` or something? 

In the mean time if you build from source you can simply supply a command line flag to force disabling the plugin as follows:

`cmake -DENABLE_MPRIS=false .`

**Comment by ghost** [comment]
@smhmd  I just have the same issue on artix too, and I solve it by:
1. `find / -name sd-bus.h 2>/dev/null`  output :  
/usr/include/elogind/sd-bus.h
/usr/include/elogind/systemd/sd-bus.h
2. so "/usr/include/elogind" is where you need to tell cmake to find that sd-dbus.h file, I'm install it by aur, so I edit PKGBUILD
 file (under ~/.cache/youraurhelper/musikcube/), add 
_-DCMAKE_CXX_FLAGS=-isystem\ /usr/include/elogind_ 
in cmake line (before the compile path, ie. .)
3. run ` makepkg -i ` to compile it manually.  cheers! now you have musikcube on your artix! 🍉

**Comment by ghost** [comment]
> 



> @smhmd I just have the same issue on artix too, and I solve it by:
> 
> 1. `find / -name sd-bus.h 2>/dev/null`  output :
>    /usr/include/elogind/sd-bus.h
>    /usr/include/elogind/systemd/sd-bus.h
> 2. so "/usr/include/elogind" is where you need to tell cmake to find that sd-dbus.h file, I'm install it by aur, so I edit PKGBUILD
>    file (under ~/.cache/youraurhelper/musikcube/), add
>    _-DCMAKE_CXX_FLAGS=-isystem\ /usr/include/elogind_
>    in cmake line (before the compile path, ie. .)
> 3. run `makepkg -i` to compile it manually.  cheers! now you have musikcube on your artix! watermelon

-DCMAKE_CXX_FLAGS=-isystem\ /usr/include/elogind
that's a backslash key, a space key, and I don't know about this weird cmake syntax.
