### ISSUE TITLE
Changing output driver --> resume paused playback

### ISSUE THREAD

**Issue by Tokariew** [clangen/musikcube#367]
Could we get setting for not resuming audio playback after changing output driver, or change in behaviour? What i mean

- pause playback
- change output driver
- audio is resumed --> I think it should be still paused if possible…

**Comment by PythonTryHard** [comment]
Reproducible. Affects both `0.93.1` and d56fc11 freshly built.

**Comment by clangen** [comment]
Thanks for the report! Fixed here: https://github.com/clangen/musikcube/commit/95b928665d1046ddd1a5897e62122398ae6fc6db
