### ISSUE TITLE
Regex or wildcard in the album/artist/genre search view

### ISSUE THREAD

**Issue by dbogdanov** [clangen/musikcube#377]
Add support for regex or wildcards for easier search inside the album/artist/genre search view.

Some example use-cases: 
- See all artists with names starting on `K`
- See all artists with names starting with `The `
- See all albums including multiple words.

Somewhat related to https://github.com/clangen/musikcube/issues/268.

**Comment by clangen** [comment]
Yeah, this has been on my mind for quite a while. Today I spent some time working on an implementation, and got it working a couple hours ago. I need to do more extensive testing, but am hopeful to make it into the next release. 

The PR is here: https://github.com/clangen/musikcube/pull/379

**Comment by clangen** [comment]
Part of 0.95.0, which was just released. To use: focus a search field and press `M-m` to toggle between regular and regex "match modes." The search field will be highlighted in blue when regex mode is enabled, and highlighted in red for standard search/filter.
