### ISSUE TITLE
[0.94.0][Fedora 33] Segmentation fault after modifying connection settings

### ISSUE THREAD

**Issue by Travisyard** [clangen/musikcube#381]
Hello, this is the first time I've ever submitted an issue through GitHub so hopefully this is all correct.

I have been running Musikcube on my server and streaming to Musikdroid for years now. With the latest 0.94.0 release, I saw that you can now connect to and stream from a remote instance of Musikcube from the terminal app. So I upgraded my server to the latest 0.94.0 release and downloaded the correct release to my local machine. However, whenever I attempt to connect, the client segfaults.

About my server
OS: Ubuntu 18.04 in LXC container on Proxmox
Musikcube version: 0.94.0, running headless through musikcubed
Local IP address: 192.168.2.106
Metadata port: 57905
Audio port: 57906
Using TLS?: No
Password?: Yes

About my proxy
Local IP address: 192.168.2.102
DNS record: musikcube.[redacted].xyz
Metadata port: 57905
Audio port: 57906
Using TLS?: Yes, Letsencrypt certs

About my client
OS: Fedora 33
Musikcube version: 0.94.0

I can reliably reproduce the issue:
1. Launch musikcube
2. Press 's' to enter the settings
3. Enter one of the following configurations in (all are valid and will work when I input them into Musikdroid)

(Local or remotely)
    hostname: musikcube.[redacted].xyz
    metadata port: 57905 [x] use tls
    audio port: 57906 [x] use tls
    password: *******

(Local through Nginx)
    hostname: 192.168.2.102
    metadata port: 57905 [x] use tls
    audio port: 57906 [x] use tls
    password: *******

(Local straight from the server)
    hostname: 192.168.2.106
    metadata port: 57905 [ ] use tls
    audio port: 57906 [ ] use tls
    password: *******

4. press 'a' to return to library
5. The application crashes and leaves behind "Segmentation fault (core dumped)"

Things I have tried:
1. Rebooting both server and client
2. Launching through gui instead of terminal
3. Whitelisting ports in firewall
4. Disabling firewall entirely
5. VPN to outside world (to test the remote configuration from outside)

**Comment by clangen** [comment]
Thanks for the report! I took a quick look at this during lunch and found I have an edge case parsing high port numbers, I'm passing around a `short` that should be `unsigned short`, which means high number ports are getting converted to negative numbers. Oops. I'll get a fix for this checked in tonight and get some new builds spun up, because this is pretty bad.

In the mean time using a port number lower than 32,767 should fix the issue. Sorry for the inconvenience.

**Comment by Travisyard** [comment]
Thank you for reviewing this issue. I will try again when the new builds are up :)

**Comment by clangen** [comment]
Sure thing! I just posted some new builds, feel free to give them a go. You're probably one of (if not) the first people other than myself to test remote libraries in the terminal client, so we'll have to see if you run into any more bugs. :)

https://github.com/clangen/musikcube/releases/tag/0.95.0
