### ISSUE TITLE
No Milkdrop?

### ISSUE THREAD

**Issue by orazdow** [clangen/musikcube#385]
I am using the latest w32 [release](https://pastebin.com/UV9czqiH) with Milkdrop, but I haven't been able to find it in the package or use it. When I hit `v` a menu with one selection shows up for GdiVis, but no Mildrop.

Is there a way to enable it, or is it not available in this release?

**Comment by clangen** [comment]
Oops, looks like the latest version didn't compile cleanly with the latest MSVC compiler, and I didn't notice while packaging the release. I just fixed it here: https://github.com/clangen/milkdrop2-musikcube/commit/994ad4c39c28fec947d4dc253eda5bd518756719 ... it'll be part of the next release, which I'm planning to roll out in the next couple days with a couple of other unrelated fixes.

**Comment by orazdow** [comment]
Ah cool.
