### ISSUE TITLE
Fails to build in RHEL7

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#386]
I haven't lucky building with git clone so I decided do build from "musikcube-0.95.0.tar.gz". 

```
[  1%] Built target ffmpegdecoder
[  1%] Building CXX object src/musikcore/CMakeFiles/musikcore.dir/support/Auddio.cpp.o
In file included from /home/persona/musikcube-0.95.0/src/musikcore/sdk/HttpClient.h:35:0,
from /home/persona/musikcube-0.95.0/src/musikcore/support/Auddio.cpp:38:
/home/persona/musikcube-0.95.0/src/musikcore/sdk/HttpClient.h: In member function ‘musik::core::
sdk::HttpClient<T>& musik::core::sdk::HttpClient<T>::Run(musik::core::sdk::HttpClient<T>::Callback)’:
│/home/persona/musikcube-0.95.0/src/musikcore/sdk/HttpClient.h:254:32: error: ‘CURLOPT_XFERINFODATA’ was not declared in this scope
curl_easy_setopt(curl, CURLOPT_XFERINFODATA, this);
                               ^
/home/persona/musikcube-0.95.0/src/musikcore/sdk/HttpClient.h:254:32: note: suggested alternative: ‘CURLOPT_WRITEDATA’
/home/persona/musikcube-0.95.0/src/musikcore/sdk/HttpClient.h:255:32: error: ‘CURLOPT_XFERINFOFUNCTION’ was not declared in this scope
curl_easy_setopt(curl, CURLOPT_XFERINFOFUNCTION, &CurlTransferCallback);
/home/persona/musikcube-0.95.0/src/musikcore/sdk/HttpClient.h:255:32: note: suggested alternative: ‘CURLOPT_WRITEFUNCTION’
make[2]: *** [src/musikcore/CMakeFiles/musikcore.dir/build.make:850: src/musikcore/CMakeFiles/musikcore.dir/support/Auddio.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:419: src/musikcore/CMakeFiles/musikcore.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
I've comment all files that contains "CURLOPT_XFERINFODATA" and  "CURLOPT_XFERINFOFUNCTION". I was able to build after those changes.

cmake3 version 3.17.3
g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

**Comment by clangen** [comment]
Looks like in older versions of `libcurl` use these different names:
* `CURLOPT_XFERINFODATA` is called `CURLOPT_PROGRESSDATA`
* `CURLOPT_XFERINFOFUNCTION` is called `CURLOPT_PROGRESSFUNCTION`

Should be easy enough to conditionalize this based on the version of `libcurl` on the system.

I'll try to get this into the next release, which I'm hoping to roll out this weekend (or next) with a couple other unrelated fixes.

**Comment by clangen** [comment]
Fixed in this commit: https://github.com/clangen/musikcube/commit/c44343712df6dc75b1fbb857433faacfcd1bde75

It'll roll out with the next release that I'm working on wrapping up.

**Comment by clangen** [comment]
Released -- hopefully this fixes the issue. I don't have RHEL7 to test against. https://github.com/clangen/musikcube/releases/tag/0.96.0

**Comment by clangen** [comment]
Apologies, after releasing 0.96.0 I found another couple potential issues with older versions of libcurl. Here is an updated release that should correct those problems: https://github.com/clangen/musikcube/releases/tag/0.96.1
