### ISSUE TITLE
Server version troubles on arm64

### ISSUE THREAD

**Issue by Travisyard** [clangen/musikcube#387]
I am experiencing a version mismatch error where the Musikcube client cannot connect to my server. The verbage is "error: incompatible server version". However, I am certain that they should be compatible versions.

I suspect this might an edge case from an unusual setup. This is only happening after building the Musikcube client on Mobian (Debian 10) on my Pine64 PinePhone. There are no releases compiled for arm64 (The RaspberryPi armhf release is incompatible) so I compiled it myself following [these instructions on the project wiki](https://github.com/clangen/musikcube/wiki/building) exactly.

Perhaps when compiling for arm64 the version number changes? Maybe something breaks and it cannot correctly detect the version number of the server? Something I did notice is that the wiki page doesn't specifically call for version 1.71 of the many libboost dependencies but that is what is available in the Debian software repositories.

I am experiencing this issue after cloning the repo today. My server is upgraded to the latest release (0.95.0) on an Ubuntu 18.04 x86 box. I am able to connect to the server using the same settings on my Fedora x86 laptop (0.95.0) and using Musikdroid on my Android phone (0.9**4**.0).

As an aside, I cannot find a way to actually find out what version of Musikcube I am running after having installed it. There is an option to check for updates which just returns "no updates found at this time." and the standard `--version` argument doesn't work. In a future release maybe include a way to retrieve the version number? I think printing it in the lower corner of the settings page would be sufficient.

**Comment by clangen** [comment]
Sorry you're having issues, hopefully I can help you.

First, apologies you're having problems finding the version. There are two ways to check:
1. You can ask the daemon, as it's a more traditional command line app. `musikcubed --version` should dump the version.
2. In `musikcube` itself by using M-` anywhere in the app (modifier key + backtick -- apologies, I'm struggling to escape that sequence in a code block in github's Markdown)

Is the version you built from source using the current code in the `master` branch? If so, that's probably the issue -- I rev'd the version earlier this week in preparation for the upcoming release, which is likely causing the mismatch. 

If you're feeling adventurous you can modify the version code in the header and rebuild, here: https://github.com/clangen/musikcube/blob/master/src/musikcore/version.h#L40 ... just change `96` to `95`, and `0.96.0` to `0.95.0`. However, a simpler solution would be to build using the archived `0.95.0` release version source, found here: https://github.com/clangen/musikcube/archive/0.95.0.tar.gz

I'll see about adding a better error message that includes both the client version and server version in the next release, which I'll be rolling out this weekend (or next), depending on the number of bugs I can work through tomorrow.

**Comment by Travisyard** [comment]
Thank you for the help! I was able to determine that the installed version was 0.96.0. Rebuilding using the archive succeeded and it solved my problem. I learned a lesson about building from the current repo vs an archived release tarball.

As for finding the version number, modifier + backtick is a little esoteric. I think having it displayed in grey in the corner of the settings page would be nice, or including a "about" section of the settings.

And I agree that something like "error: incompatible server version (0.95.0 =/= 0.96.0)" or "error: server version (0.95.0) incompatible with client (0.96.0)" would be a useful addition that would have helped me figure this out.

**Comment by clangen** [comment]
Awesome to hear you're up and running!

```As for finding the version number, modifier + backtick is a little esoteric. I think having it displayed in grey in the corner of the settings page would be nice, or including a "about" section of the settings.```

Agreed. I'm going to go ahead and re-open this issue so I don't forget to get the two changes discussed in this ticket into the next release.

**Comment by clangen** [comment]
Also, I'm going to add an "advanced" setting that allows user to disable that version check. The check is overly-aggressive right now because remote libraries in the terminal client are a new feature, but the reality is the functionality that backs them is pretty stable and should generally be compatible between releases.

**Comment by clangen** [comment]
* Setting to disable version mismatch error: https://github.com/clangen/musikcube/commit/dff519ee8767f5944537d91f01f7441c525b29df
* Server version in error message: https://github.com/clangen/musikcube/commit/ad09b30b1879109791377fc8a9d7b098718d9868
* App version on settings screen: https://github.com/clangen/musikcube/commit/f001a48b4376975c6d5d0bc50fa4a9d7b5432281

**Comment by clangen** [comment]
Released: https://github.com/clangen/musikcube/releases/tag/0.96.0
