### ISSUE TITLE
Proper XDG Base Directory support

### ISSUE THREAD

**Issue by 0xJes** [clangen/musikcube#389]
Currently Musikcube uses `$HOME/.config` to store its config folder, but does not follow `$XDG_CONFIG_HOME`.

I'm a user of a custom `$XDG_CONFIG_HOME` and I knowledge that its not very common, but following  `$XDG_CONFIG_HOME` envar would be nice, so please consider implementing it.

**Comment by clangen** [comment]
Good call, I'll try to get this into the next release. Seems like we should just check to see if `$XDG_CONFIG_HOME` is defined, then fall back to `$HOME` if it's not? (Apologies, I'm a novice Unix developer)

**Comment by clangen** [comment]
I think this commit will address the issue: https://github.com/clangen/musikcube/commit/7fbed0513588f57e0a9f42e7363f122f643bd842

**Comment by 0xJes** [comment]
> Good call, I'll try to get this into the next release. Seems like we should just check to see if `$XDG_CONFIG_HOME` is defined, then fall back to `$HOME` if it's not? (Apologies, I'm a novice Unix developer)

I think that will do it.
The specification states that:

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 

You can read the whole specification [here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by clangen** [comment]
Added in 0.96.3. https://github.com/clangen/musikcube/releases/tag/0.96.3

**Comment by amcooper** [comment]
Reopening this thread. I'm running 0.96.6 on Arch Linux. I recently started using the XDG Base Directory Specification. This caused, upon the next launch of musikcube, a config directory to be created at `$HOME/.config/.config/musikcube/` (so it behaved as a fresh launch, not knowing where the audio files were located. And that seems to be what's going on in `/src/musikcore/support/Common.cpp`. I think [the extra `".config"`](https://github.com/clangen/musikcube/blob/master/src/musikcore/support/Common.cpp#L88) is not needed (and hence the whole `if` block).
