### ISSUE TITLE
Hotkey to clear queue

### ISSUE THREAD

**Issue by sorjgdojbodjhdo** [clangen/musikcube#392]
Hi,

I looked at the list of hotkeys and it seems that there is currently no shortcut  to clear the queue. Sure I can delete each tracks individually but when I have 9 albums queued up this is needlessly inefficient.

Is this feature implemented? If not this is a feature request. 

Thanks for your amazing work. The software is great.

**Comment by clangen** [comment]
Sounds good! Added it in this commit -- by default you press `Shift+X` in the play queue mode to clear it. https://github.com/clangen/musikcube/commit/fbbaea0beb5e4eba017e9e11e1f20d0fe5230e67

**Comment by clangen** [comment]
Added in 0.96.3. https://github.com/clangen/musikcube/releases/tag/0.96.3
