### ISSUE TITLE
Package requirement not listed in Wiki

### ISSUE THREAD

**Issue by Magicrafter13** [clangen/musikcube#394]
When trying to compile on Manjaro (Arch), I got this output.

```
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at /usr/share/cmake-3.19/Modules/FindPkgConfig.cmake:609 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  /usr/share/cmake-3.19/Modules/FindPkgConfig.cmake:741 (_pkg_check_modules_internal)
  src/plugins/mpris/CMakeLists.txt:6 (pkg_check_modules)
```

Had to install `pkg-config`. Granted, this is pretty simple to figure out since the package is literally mentioned in the output, but should still be added to the wiki for the sake of completeness.

**Comment by clangen** [comment]
Arch build instructions are listed on the wiki here: https://github.com/clangen/musikcube/wiki/building

Additionally, musikcube is available in aur: https://aur.archlinux.org/packages/musikcube/

**Comment by Magicrafter13** [comment]
I know, the build instructions are what I'm referring to; they state these are the package requirements for building on Arch:

- arch: `sudo pacman -S libogg libvorbis libmicrohttpd ffmpeg lame cmake ncurses boost pulseaudio libpulse alsa-lib curl libev taglib libopenmpt`

However, `pkg-config` is not listed here, and I'm suggesting that it should be since it appears to be required to build.

**Comment by clangen** [comment]
Oh, sorry, I misunderstood. Instructions updated! Thanks for the suggestion!
