### ISSUE TITLE
Support for editing Tags/metadata

### ISSUE THREAD

**Issue by g0josh** [clangen/musikcube#397]
Is there a way to edit tags or metadata? Or how can I integrate another tag editor?

**Comment by clangen** [comment]
There is currently no way to edit metadata. The original, Windows-only version of musikcube supported this functionality, but I never got around to adding it to the current, cross-platform version. The reason being is that some tag formats -- especially id3v2 -- have tons of edge cases and compatibility requirements; I thought I'd rather focus on the playback/streaming/cross-platform features and leave tag editing/writing to other dedicated apps that specialize in that stuff.

What platform are you running on? I may be able to recommend an open source (or free) external app you can use instead.

**Comment by g0josh** [comment]
I'm on Pop OS 20.04. I'll be grateful if you could  recommend a work around

**Comment by clangen** [comment]
So on Linux I personally like using the `kid3` tag editing app. It has both CLI and QT-based frontends, and is very nice for casual use. See here: https://kid3.kde.org/

I just tossed Pop OS on a VM -- you should just be able to do `apt-get install kid3` (or install it from the Pop! Shop frontend), start the app, then edit your tags.

After you've finished editing metadata, just restart `musikcube` (or press CTRL+R on the library screen, and select `scan for changes`), and your metadata should be updated in musikcube.

Let me know if you have any more questions!

**Comment by g0josh** [comment]
Is there a way to launch the tag editor from musiccube itself?
