### ISSUE TITLE
Option to not reopen to the state where the app was when closed [feature request]

### ISSUE THREAD

**Issue by sorjgdojbodjhdo** [clangen/musikcube#398]
Hi,

I noticed that when I close the app and then reopen it, it takes me to the page I was on when I closed Musikcube. For a project I'm building I would love to have the option to disable that feature.

This could be added as an option in advanced settings for example. Sadly I don't know C/C++ enough to implement the feature myself so I guess I can only ask but I would be happy to help however I can.

Thank you for your work.

**Comment by clangen** [comment]
If I understand the request properly, this feature already exists. You can just turn off "save session on exit" in the settings screen. 

![Screenshot from 2020-12-28 15-24-14](https://user-images.githubusercontent.com/2031666/103248724-c94d4e80-4920-11eb-979c-5791f8576c1b.png)

**Comment by sorjgdojbodjhdo** [comment]
> If I understand the request properly, this feature already exists. You can just turn off "save session on exit" in the settings screen.
> 
> ![Screenshot from 2020-12-28 15-24-14](https://user-images.githubusercontent.com/2031666/103248724-c94d4e80-4920-11eb-979c-5791f8576c1b.png)

What an idiot I am. I went to advanced settings without looking for the options on the main page. You understood my request correctly indeed and the feature already exists. I've closed the issue.
