### ISSUE TITLE
Incorrect latest release reported, or crash when manually checking for latest release

### ISSUE THREAD

**Issue by PythonTryHard** [clangen/musikcube#399]
**Affected version**: Release `0.95.0` and Release `0.96.2` (from my limited scope of testing), both on Windows (have not tested on my Ubuntu machine, will get around to it)

**Steps to reproduce**:
(The latest release as of opening of this issue is `0.96.3`
1. Open `musikcube`, either wait for new release notification or force a manually update check from Settings

**Expected behavior**: Both releases correctly report back that the latest release is `0.96.3`

**Actual behavior**:
`0.95.0`: Reported back `0.96.2` as latest release
![musikcube_2UGZ6VKs1Y](https://user-images.githubusercontent.com/31789326/103255088-8475f600-49ba-11eb-8ed3-ec190ab97ef4.png)
![musikcube_hE56WTor0H](https://user-images.githubusercontent.com/31789326/103255090-85a72300-49ba-11eb-8f56-ccab53a31aec.png)
`0.96.2`: No automatic new release notification. Attemps to force a manual instead of returning the notification after a reasonable amount of time (usually 4 seconds), returns nothing. By forcing a 2nd manual check after the 1st one `musikcube` will crash. No logs has been found (thus far)

**Comment by clangen** [comment]
Thanks for the report!

You're right, I completely broke the update check mechanism in 0.96.2, and it will crash the app when run manually. 🤦 I fixed it in 0.96.3.

I also forgot to update the "latest version" on the website to 0.96.3 -- I just updated it, so that should be fixed now!

**Comment by PythonTryHard** [comment]
Checked again and everything is normal again, thank you!
Happy (early) New Year too!
