### ISSUE TITLE
[feature request] Mouse wheel scrolling?

### ISSUE THREAD

**Issue by featherfurl** [clangen/musikcube#401]
I tend to use a combination of keyboard and mouse interaction for the terminal apps I use most frequently, and I often find myself trying to mouse scroll through longer playlists / album lists on musikcube without success. There's already a fair bit of support for mouse interaction, and adding wheel scrolling would make interacting with musikcube a bit more natural feeling for those of us who often use the mouse as well as the keyboard in terminal applications.

**Comment by clangen** [comment]
Whoa, I totally forgot I never implemented this on Unix platforms, thanks for the reminder! Just checked in a fix here: https://github.com/clangen/musikcube/commit/10a3863f95b53c8398fb0217f89e8d7d3c858c65 -- it'll be part of the next release.
