### ISSUE TITLE
[privacy] why do you use trackers?

### ISSUE THREAD

**Issue by miku86** [clangen/musikcube#402]
Hey Casey,

thanks for your awesome app,
I really like it :slightly_smiling_face: 

A scan with [Warden](https://gitlab.com/AuroraOSS/AppWarden) brings up 3 trackers in the musikdroid application:
- Google Firebase Analytics
- Google AdMob
- Google CrashLytics

I would love to know why you use these trackers,
because I can't find any information about that on [https://musikcube.com](https://musikcube.com/).

Best,
Michael

**Comment by clangen** [comment]
Hello! These are used to monitor crashes and understand how many people are using the app. The good news is that if this concerns you, you can always grab the sources, rip out Firebase, and build the app yourself. If that interests you, and you have any additional questions, I'm happy to help you through it.

**Comment by miku86** [comment]
Hey Casey,

thanks for your kind reply, I managed to remove the Google services, Firebase and the auto update.

Now the application is tracker-free and doesn't ping musikcube.com.

If someone wants to see the differences, have a [look at the diff](https://github.com/miku86/musikcube/commit/ec2b7ff3301173886beb0645e1eafb97392266f3), it's pretty straight-forward.

Keep up the great work :+1:

Greetings
Michael
