### ISSUE TITLE
How to playback and displaying wav file? 

### ISSUE THREAD

**Issue by Extr3m4R4710** [clangen/musikcube#405]
- Platform: Fedora33
- Desktop: i3wm and GNOME
- Terminal: st, gnome-terminal, tilix

## case
In one my case, musikcube is not reading directory and  into the wav files.
![Screenshot from 2021-01-16 22-03-14](https://user-images.githubusercontent.com/48596072/104813231-3af72900-584b-11eb-96ab-16d5f986f447.png)
This image shows me loading my `$HOME/Music` into musikcube. 
As you can see, there is no wav file in the Music directory that I am blousing. 

In case you're wondering, it works fine on Windows 10.

I am sorry that I have nothing to report. However, as far as I know, there was no debug option available, so I reported it.

**Comment by clangen** [comment]
Are you running the `snap` version of the app?

**Comment by clangen** [comment]
Snaps will no longer be distributed due to problems like the one mentioned in this issue. https://github.com/clangen/musikcube/commit/2ad8c17461188f74bd219e40eef96e970e14bc38
