### ISSUE TITLE
[request] show total album duration

### ISSUE THREAD

**Issue by orestescm76** [clangen/musikcube#410]
I've been using this player for a couple of days, great work, but i'm missing the album duration like in cmus style.

**Comment by clangen** [comment]
Nice suggestion -- this is something I've also wanted for a while. I went ahead and added duration to all headers, so you should see them for albums, artists, genres, and search results as well in the next release:

![image](https://user-images.githubusercontent.com/2031666/105939566-54982d80-600e-11eb-914a-cb54acb5db33.png)

**Comment by orestescm76** [comment]
that looks awesome, just like I wanted!
