### ISSUE TITLE
Allow for lock on files to be released for HDD to enter sleep mode

### ISSUE THREAD

**Issue by HLPJasiri** [clangen/musikcube#411]
Hello there!

I'm enjoying musikcube quite a bit, thanks for this great piece of software.

I'm not using it on a Raspi with flash storage, but instead installed it on my (headless, openmediavault-powered) NAS so I could feed my AV receiver with music using a Toslink connection.

The thing is, my music collection resides on an HDD RAID, so if I "pause" musikcube's playback, the lock on the currently "active" file never gets released and the system doesn't allow the drives to enter sleep mode.

Is there any way for me to "stop" playback completely and not have it basically paused all the time when it's not playing? The only solution I have so far is to kill the musikcube instance. I would prefer it running in the background so it can just spin the drives up as soon as I want it to play again as long as it allows the drives to go to sleep, as killing the instance requires me to manually restart the program from the console every time I want to play something.

Thanks!

**Comment by clangen** [comment]
Yep, you can use `Ctrl+X` to stop playback and unload all open files.
