### ISSUE TITLE
Snap and filesystem.

### ISSUE THREAD

**Issue by 237dmitry** [clangen/musikcube#413]
The snap version does not view mounted partitions or binded directories. Empty /home/user/Music directory as result.

**Comment by clangen** [comment]
yeah...

i'm starting to think the snap is a bad idea because of the default filesystem restrictions... you can give it access to the filesystem if you "connect" it or something

**Comment by clangen** [comment]
Snap support has been removed for future versions. https://github.com/clangen/musikcube/commit/2ad8c17461188f74bd219e40eef96e970e14bc38
