### ISSUE TITLE
ncurses detection fails when ncurses is built w/out suffixes

### ISSUE THREAD

**Issue by yurivict** [clangen/musikcube#415]
```ncurses``` has the configure option ```--disable-lib-suffixes``` that drops ```"w"``` suffixes.

Please consider making your configuration more flexible and detect such situation.

In the FreeBSD port for ```ncurses``` the above option was added and ```musikcube``` now fails to find ```ncurses```.

**Comment by clangen** [comment]
Thanks for the heads up. I recently setup a dedicated FreeBSD box but I'm very much a novice. Can I reproduce the problem by fetching the latest ports and trying to build musikcube from `/usr/ports`?

**Comment by yurivict** [comment]
> Can I reproduce the problem by fetching the latest ports and trying to build musikcube from /usr/ports?

Yes, ```musikcube``` from current ports would fail if you would remove the specific patch that I've added today to fix this problem.

**Comment by clangen** [comment]
Got it. Even after reading some documentation I'm not quite sure how to detect whether or not the existing library on the system was compiled with the `--disable-lib-suffixes` switch, so I'm not sure how to automatically detect this configuration.

In the meantime, however, I added a custom cmake flag called `NCURSES_DISABLE_LIB_SUFFIXES` that can be specified manually to link against the non-suffixed libraries; while maybe not completely ideal, you won't have to have a custom patch any longer. 

You should just be able to add the following to the port `Makefile`:

`CMAKE_ARGS=     -DNCURSES_DISABLE_LIB_SUFFIXES=true`

Reference commit: https://github.com/clangen/musikcube/commit/d35d8d31f7d1f0a26442b211e25d8633452d77ac

Oh, unrelated, I noticed the `LICENSE` in the musikcube port's `Makefile` is incorrect, musikcube uses a standard 3-clause BSD license, not GPLv2. https://github.com/clangen/musikcube/blob/master/LICENSE.txt

**Comment by yurivict** [comment]
You could also call ```find_package``` twice with and without "w" and then require for at least one to be present.

**Comment by clangen** [comment]
> You could also call find_package twice with and without "w" and then require for at least one to be present.

I'll need to do a bit more research, but I think there may be issues doing this; musikcube doesn't support the "non-wide" version of ncurses -- or at the very least is highly untested. If we unconditionally link against non-suffixed libraries (in the absence of ones suffixed with "w") the app may not function properly. Ideally we'd be able to determine whether or not a non-suffixed library is actually a wide-character version.

**Comment by yurivict** [comment]
If removal of the "w" suffix also removes any part of functionality of ```ncurses``` - this was an erroneous change in the ```ncurses``` port.

**Comment by clangen** [comment]
I am by no means an `ncurses` expert, and know various Linux distributions (e.g. Arch, Manjaro and likely others) only provide non-suffixed versions that always support the "wide-character" functionality. The wide-version, from my understanding, is a superset of the non-wide version.

This is one of my references: https://invisible-island.net/ncurses/ncurses.faq.html

>The normal ncurses libraries support 8-bit characters. The ncurses library can also be configured (--enable-widec) to support wide-characters (for instance Unicode and the UTF-8 encoding). The corresponding wide-character ncursesw libraries are source-compatible with the normal applications. That is, applications must be compiled and linked against the ncursesw library.

...

> The ncurses and ncursesw libraries are reasonably source-compatible. That is, an application written for "ncurses" will build with "ncursesw". But it will behave differently in response to your locale settings. (Some distributors, who do not care about the differences, have chosen to merge the names together as "ncurses").

So, applications built with historical, non-"w" versions of `ncurses` should be compatible (most of the time) with the "w" versions, but almost certainly not the other way around. 

Specifically, my past experimentation has shown that the non-wide version may not render non ASCII symbols properly. `musikcube` uses a handful of different Unicode characters to draw more complicated parts of the terminal UI.

For operating systems / distributions that only provide non-suffixed, "wide" versions of ncurses I've added special cases in the CMake files to not include the "w" suffix. If `FreeBSD` is heading in that direction, I can do it for that as well.

**Comment by clangen** [comment]
I think we worked this one out, but I can't remember. If there's something left to be done, let me know. Closing for now to clean up stale issues I'm not looking at.
