### ISSUE TITLE
musikcube cannot "find" files with full path's length exceeding 259 characters

### ISSUE THREAD

**Issue by PythonTryHard** [clangen/musikcube#418]
**Affected version**: Release `0.96.4 #3c77c21e`, Windows x64, issue is speculated to extend to other Windows releases as well.

**Operating system context**: Windows 10 2004 (build `19041.746`), Registry key `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` data type `REG_DWORD` set to `1`. Reboot has been performed.

**Steps to reproduction**:
1. Have a file in such a way that the combined path exceeds 259 char, eg. `F:\MEGA\Staging\!Testttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt\Kobaryo & Matatabi Sound System + DJ NECOJITA + Shinonome I-F + blaxervant - Precious Song Dedicated to the Stars - 01 Precious Song Dedicated to the Stars.flac`. 
2. Try to look for it in directory view and library

**Actual behavior**: The file is not found.
**Expected behavior**: The file is found.

**Comment by clangen** [comment]
Sorry, real life has been quite busy lately. This seems like a bad bug, I'll try to get it fixed for the next release.

**Comment by clangen** [comment]
This should take care of it: https://github.com/clangen/musikcube/commit/de660b8f513a954dd34838f301161f6c3d3af87b

**Comment by PythonTryHard** [comment]
> Sorry, real life has been quite busy lately

No problem man, real life comes first. I'll try to compile tonight to verify.

**Comment by PythonTryHard** [comment]
Confirmed to be fixed.
