### ISSUE TITLE
Building fails even though cmake passed it's checks.

### ISSUE THREAD

**Issue by acidtonic** [clangen/musikcube#420]
I'm on Gentoo and manually building from source. After running cmake successfully I have been encountering various build failures which normally I'd expect cmake to catch. Normally if cmake completes I'd expect all the dependencies to have been correctly enumerated.

#include <ev++.h> (part of libev which I didn't have installed)
#include <pulse/sample.h> (not found, needed pulseaudio but I don't want to use it)

I installed libev and got past the first error, but I ended up manually going into CMakeLists.txt and removing the add_subdirectory() for the pulseout plugin since I didn't want to use pulseaudio. I don't run any "Poettering" software and it was stopping the build at that plugin.

I'd expect cmake to either check for alsa/pulse's existence and only add the subdirectory for those plugins when present. If both are missing I'd presume it should stop. For libev it should have stopped as well and not written makefiles.

**Comment by clangen** [comment]
Thanks for raising this. It's been something in the back of my mind for a while. I added some checks to the CMake scripts to fail fast if it can't find required libraries: https://github.com/clangen/musikcube/commit/229b282aecc3f6518a678a4ded0275d5094a497c

I'm not sure if this is the best way to do it, but it seems to work fine. Please re-open this issue if you have further problems.
