### ISSUE TITLE
Difficulty using "system" taglib-1.12

### ISSUE THREAD

**Issue by lfam** [clangen/musikcube#425]
Hello,

I'm working on packaging musikcube for [GNU Guix](http://guix.gnu.org/en/about/).

I noticed that musikcube includes a copy of taglib to work around the long period without an upstream taglib release.

But in Guix, we have the new taglib 1.12, so I tried to use it with musikcube by making it available in the musikcube build environment and passing ```-DUSE_BUNDLED_TAGLIB=false``` to CMake.

However, the build seems to have used the bundled taglib anyways. The RUNPATH of the component that directly refers to taglib, ```libtaglibreader.so```, did not include the full path of the system taglib library, and thus would not have been able to find it at runtime on Guix.

What worked was to both delete the bundled taglib from the musikcube source code and remove the line ```set(USE_BUNDLED_TAGLIB "true")``` from ```CMakelists.txt```.

Is this expected? Please let me know if I can provide any more information or assist with debugging.

**Comment by lfam** [comment]
Here are the RUNPATHs of the "good" and "bad" builds:

Good:

```
$ readelf -d share/musikcube/plugins/libtaglibreader.so | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:/gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib:/gnu/store/01b4w3m6mp55y531kyi1g8shh722kwqm-gcc-7.5.0-lib/lib:/gnu/store/kxabg9r2wnb4inc5lvh7r4wxnpj5f8kr-boost-1.72.0/lib:/gnu/store/3rgna22p3qpphp7bdc8qf0p4q4rp7zay-taglib-1.12/lib:/gnu/store/rykm237xkmq7rl1p0nwass01p090p88x-zlib-1.2.11/lib:/gnu/store/01b4w3m6mp55y531kyi1g8shh722kwqm-gcc-7.5.0-lib/lib/gcc/x86_64-unknown-linux-gnu/7.5.0/../../..]
```

Bad:
```
$ readelf -d share/musikcube/plugins/libtaglibreader.so | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:/gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib:/gnu/store/01b4w3m6mp55y531kyi1g8shh722kwqm-gcc-7.5.0-lib/lib:/gnu/store/kxabg9r2wnb4inc5lvh7r4wxnpj5f8kr-boost-1.72.0/lib:/gnu/store/rykm237xkmq7rl1p0nwass01p090p88x-zlib-1.2.11/lib:/gnu/store/01b4w3m6mp55y531kyi1g8shh722kwqm-gcc-7.5.0-lib/lib/gcc/x86_64-unknown-linux-gnu/7.5.0/../../..]
```

**Comment by clangen** [comment]
Yep, looks like a bug. I _think_ I fixed it here https://github.com/clangen/musikcube/commit/15134e9a80be253b4c9c4dd65eb003d952f97eef, but it'd be cool if you could confirm.

Please run:
  1. `./scripts/clean-nix.sh` (shouldn't be necessary, but just in case...)
  2. `cmake -DENABLE_BUNDLED_TAGLIB=false .`
  3. `make -j6`

Also note I renamed the variable from `USE_BUNDLED_TAGLIB` to `ENABLE_BUNDLED_TAGLIB` so the naming is consistent with other variables used in the build process!

**Comment by lfam** [comment]
I confirm this fixes it. Thanks a lot!
