### ISSUE TITLE
Cannot find libcurl.lib when building

### ISSUE THREAD

**Issue by Alfredfeng** [clangen/musikcube#426]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'libcurl.lib'	cddadecoder	C:\workfolder\musikcube\src\plugins\cddadecoder\LINK	1

**Comment by clangen** [comment]
`.lib` and `.dll` files are provided by the [musikcube-bin](https://github.com/clangen/musikcube-bin) `git` submodule. Make sure you do a `git submodule update --init --recursive` in the `musikcube` directorly followed by a `git pull --recursive` (the second probably isn't necessary), then rebuild.

Please re-open if you still have issues!
