### ISSUE TITLE
[Wiki] Clarification on Windows build instruction

### ISSUE THREAD

**Issue by PythonTryHard** [clangen/musikcube#427]
I have encountered some issues while following the [wiki's build instruction for Windows](https://github.com/clangen/musikcube/wiki/building#windows) to test out certain commits:

1. Visual Studio doesn't have to be VS Community 2017 as stated. I built successfully on VS Community 2019, so perhaps dropping "2017" would be good?
2. Is it mandatory and enough to install just `Boost 1.68 x32`? Various projects are shown to be using `Boost 1.74`, there is build option for x64 architecture, and I have successfully built with 64-bit option against `Boost 1.75 x64` but couldn't build the 32-bit counterpart due to lack of 32-bit object file library which is understandable. 
3. Ambiguous instruction on where to place `boost_x_xx_x` as `musikcube` can refer to both the repo and the project. This issue is further made worse by the example `c:\src\musikcube` and `c:\src\boost_1_68_0`. Only after reading through the solution file for the projects showing `..\..\..\boost_1_74_0` as the path for Boost that I was able to resolve this issue by putting Boost on the same level as the repo folder eg. `F:\Developement\boost_1_74_0` and `F:\Development\musikcube_repo` . Clarification might be needed here to prevent confusion.

**Comment by clangen** [comment]
Done!
