### ISSUE TITLE
Question marks instead of characters in the terminal

### ISSUE THREAD

**Issue by yurivict** [clangen/musikcube#435]
I installed musikcube-0.96.6 into a freshly installed FreeBSD 13.0 VM and got to this screen:

![image](https://user-images.githubusercontent.com/271906/115504901-81369c80-a22d-11eb-8527-92d94323c1c3.png)

Environment:
![image](https://user-images.githubusercontent.com/271906/115505129-d83c7180-a22d-11eb-824e-9042ef97a712.png)

**Comment by clangen** [comment]
Thanks for the report -- I have not yet tested on FreeBSD 13. Do you see this in other parts of the app as well? Or only in this particular dialog? 

I'll try to get a VM setup with FreeBSD 13 soon.

**Comment by yurivict** [comment]
I only randomly clicked on a few items.

**Comment by clangen** [comment]
Super weird, I don't see the issue on my end. Here's a couple screenshots:

![Screen Shot 2021-04-22 at 7 38 55 PM](https://user-images.githubusercontent.com/2031666/115810223-75201b80-a3a2-11eb-978b-1fc44961ca27.png)

My `env` also looks similar:

```
USER=root
LOGNAME=root
HOME=/root
MAIL=/var/mail/root
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
TERM=xterm-256color
BLOCKSIZE=K
MM_CHARSET=UTF-8
LANG=C.UTF-8
SHELL=/bin/csh
SSH_CLIENT=192.168.1.24 59747 22
SSH_CONNECTION=192.168.1.24 59747 192.168.1.34 22
SSH_TTY=/dev/pts/0
HOSTTYPE=FreeBSD
VENDOR=amd
OSTYPE=FreeBSD
MACHTYPE=x86_64
SHLVL=1
PWD=/root/src/musikcube
GROUP=wheel
HOST=osboxes
REMOTEHOST=192.168.1.24
EDITOR=vi
```

**Comment by yurivict** [comment]
TERM is different though.

You should try in the VBox VM window.

**Comment by clangen** [comment]
Ah, I do see the same thing when trying to display non-Latin characters in the built-in terminal. Here's a screenshot from VirtualBox:

![image](https://user-images.githubusercontent.com/2031666/115810584-02637000-a3a3-11eb-9fd7-db163e0bb400.png)

However, it is fine when shelling in and using `iTerm` on my Mac:

![image](https://user-images.githubusercontent.com/2031666/115810648-20c96b80-a3a3-11eb-9f7b-552ecf6b1fcc.png)

I'm a bit out of my depth here, as I'm not sure how to configure the built-in terminal to display non-Latin characters.

**Comment by yurivict** [comment]
Maybe this simply isn't possible and should be left like this.
Not a bug.

**Comment by clangen** [comment]
Yeah, it seems like it's not supported out of the box, at least. I just grabbed a string with non-Latin characters from the Japanese translation, and created a directory with it: `mkdir 言語`

You can see it shows up fine when shelled in via iTerm:

![image](https://user-images.githubusercontent.com/2031666/115820030-e668ca00-a3b4-11eb-91ba-4363b322b895.png)

However, it shows up as question marks on the standard console running in VirtualBox:

![image](https://user-images.githubusercontent.com/2031666/115820059-f385b900-a3b4-11eb-8c5f-1549f786f037.png)

**Comment by clangen** [comment]
Closing this because it seems to be working as expected. Please re-open if that's not the case and there's something that can be done on my side.
