### ISSUE TITLE
Win32/Uwamson.A!ml Found by windows defender 

### ISSUE THREAD

**Issue by TheBrwnPatron** [clangen/musikcube#436]
As soon as I downloaded the musikcube_win64_0.96.6.zip file windows defender went crazy with alerts for Win32/Uwamson.A!ml and asked me to quarantine or delete musikcube.exe

I am unsure if this is a false positive or not but I thought I should mention it.

**Comment by clangen** [comment]
Yikes, thanks for the heads up. I'm pretty sure this is a false positive, as the computer I use to build the Windows binaries is generally offline, and really only used for creating releases. I also always ensure I have the latest updates installed on it before creating new builds for distribution.

I booted up the machine and ran a Windows Defender scan on the executable, and it reported nothing. I then ran Windows Update (it had a few minor updates to install, as it hasn't been on for a couple weeks), rebooted, and ran a scan again -- this time it detected `Win32/Uwamson.A!ml` like yours.

Afterwards, I updated Visual Studio and recompiled the app to generate a new executable; now Windows Defender seems happy with it (i.e, it's no longer detected as a virus).

There is probably some sort of pattern in the original executable that is tripping the heuristics of the antivirus scanner. I'm struggling to find reliable information about the real `Uwamson.A!ml`, but it appears to be a trojan and not some sort of self-replicating virus. I did find a couple very recent mentions of it in a couple message boards, though:
* https://www.windowsphoneinfo.com/threads/any-info-on-program-win32-uwasson-a-ml-and-the-similarly-named-uwamson-a-ml.330431/
* https://mybot.run/forums/index.php?/topic/59747-trojanwin32fuerboosbcl-and-win32uwamsonaml-from-792/

Out of an abundance of caution I'm currently running full antivirus scans on all of my Windows machines in the house. Once complete, assuming nothing is found, I'll upload some fresh builds with a new version number, and add a note to the release page.

**Comment by TheBrwnPatron** [comment]
I had trouble finding info about it as well. Other than a reddit post that said "Win32/Uwasson.A!m" was a false positive, that "Win32/Uwamson.A!ml" was the real deal, and that I should search the registry for either one of those terms to confirm. 

I came up with nothing *Shrugs. 
I too am running a scan just in case. I don't think its high risk but never say never.

Thank you for looking into this so quickly.
Musikcube is my favourite.

**Comment by clangen** [comment]
Thanks again for bringing this to my attention. Full antivirus scans on all of my Windows machines completed and didn't turn up any problems. I just released new binaries for Windows that don't trip Windows Defender: https://github.com/clangen/musikcube/releases/0.96.7

If you (or anyone else reading this thread) have any further concerns, please feel free to re-open this ticket and attach any additional details.

**Comment by bleuge** [comment]
hi, tested 64bits version exes in virustotal, 2 detections from 69 antiviruses, specifically Kaspersky and other minor antivirus, 32bits are clean 0/69. 
As you said some pattern is triggering some silly stuff.
