### ISSUE TITLE
CMAKE_C_COMPILER-NOTFOUND

### ISSUE THREAD

**Issue by MKwareContributions** [clangen/musikcube#443]
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: CMAKE_C_COMPILER-NOTFOUND 
Build flags: 
Id flags:  

The output was:
No such file or directory

OS: OpenSUSE Tumbleweed 5.12.9

**Comment by clangen** [comment]
Sounds like you don't have a C compiler installed. You can install g/g++ with `sudo zypper install gcc-c++` and try to compile again.
