### ISSUE TITLE
Error after updating boost and libboost

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#444]
> ./musikcube: error while loading shared libraries: libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory

**Comment by knminhaz** [comment]
Same with me. Cant use musikcube.

**Comment by clangen** [comment]
What operating system are you running on? If macOS, try a `brew reinstall musikcube`

**Comment by UM-Li** [comment]
Hi @clangen, I've encountered this too and musikcube cannot start.  I run Arch Linux where `boost-libs` is currently v1.76.0-1.

**Comment by clangen** [comment]
boost can be a pretty major pain. I'm slowly working on removing it from the code base.

Until then, sometimes when boost updates, musikcube needs to be re-linked. The easiest way to do that is to just ask your package manager to reinstall musikcube; it'll do a fresh build and link against the new libraries.

Going to close the issue, but if that doesn't solve the problem, please re-open.

**Comment by UM-Li** [comment]
Thanks, reinstalling / recompiling works for me.
