### ISSUE TITLE
Music durations display incorrect.

### ISSUE THREAD

**Issue by nidbCN** [clangen/musikcube#448]
> musikcube version 0.96.7 #fea06d96, windows 10 x64.

Look at the picture, the length of second song is "0:00", but it should be "04:01". Windows can correct show the length of this music.

![pic](https://z3.ax1x.com/2021/07/03/R2YEOe.png)

When playing this song, duration can display correct in the time bar:

![pic3](https://z3.ax1x.com/2021/07/03/R2NePI.png)

Details info shows in windows properties page:

![pic2](https://z3.ax1x.com/2021/07/03/R2t2Dg.png)

**Comment by PythonTryHard** [comment]
Can you upload the file in question to aid debugging?

**Comment by nidbCN** [comment]
I upload it to [MEGA](https://mega.nz/file/aFgUQSRT#yYSr1g80fhiHzVbVu-pd-SOYOb-yX6vxmJRLMBhgbWc)

**Comment by clangen** [comment]
This will be fixed in subsequent releases. https://github.com/clangen/musikcube/commit/332e8c25d10d0b4e3e093b78630ab1300f127c73

**Comment by nidbCN** [comment]
> This will be fixed in subsequent releases. [332e8c2](https://github.com/clangen/musikcube/commit/332e8c25d10d0b4e3e093b78630ab1300f127c73)

Thanks you very muck
