### ISSUE TITLE
OpenBSD 6.8 cmake error

### ISSUE THREAD

**Issue by dsotm1** [clangen/musikcube#449]
Hi, trying to build musikcube on OpenBSD 6.8.

After the command: cmake -G "Unix Makefiles" .

`CMake Error at /usr/local/share/cmake/Modules/FindPkgConfig.cmake:467 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPkgConfig.cmake:647 (_pkg_check_modules_internal)
  src/musikcube/CMakeLists.txt:109 (pkg_check_modules)
`
CMakeOutput.log

`The system is: OpenBSD - 6.8 - amd64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc 
Build flags: 
Id flags:  

The output was:
0

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is Clang, found in "/root/musikcube/CMakeFiles/3.17.2/CompilerIdC/a.out"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/c++ 
Build flags: 
Id flags:  

The output was:
0

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"

The CXX compiler identification is Clang, found in "/root/musikcube/CMakeFiles/3.17.2/CompilerIdCXX/a.out"

Determining if the C compiler works passed with the following output:
Change Dir: /root/musikcube/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_4d31e/fast && /usr/bin/make  -f CMakeFiles/cmTC_4d31e.dir/build.make CMakeFiles/cmTC_4d31e.dir/build
Building C object CMakeFiles/cmTC_4d31e.dir/testCCompiler.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_4d31e.dir/testCCompiler.c.o   -c /root/musikcube/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_4d31e
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4d31e.dir/link.txt --verbose=1
/usr/bin/cc      CMakeFiles/cmTC_4d31e.dir/testCCompiler.c.o  -o cmTC_4d31e  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib 

Detecting C compiler ABI info compiled with the following output:
Change Dir: /root/musikcube/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_5ab4e/fast && /usr/bin/make  -f CMakeFiles/cmTC_5ab4e.dir/build.make CMakeFiles/cmTC_5ab4e.dir/build
Building C object CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o
/usr/bin/cc   -v -o CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o   -c /usr/local/share/cmake/Modules/CMakeCCompilerABI.c
OpenBSD clang version 10.0.1 
Target: amd64-unknown-openbsd6.8
Thread model: posix
InstalledDir: /usr/bin
 (in-process)
 "/usr/bin/cc" -cc1 -triple amd64-unknown-openbsd6.8 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 1 -pic-is-pie -mthread-model posix -mframe-pointer=all -relaxed-aliasing -fno-rounding-math -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -target-feature +retpoline-indirect-calls -target-feature +retpoline-indirect-branches -dwarf-column-info -fno-split-dwarf-inlining -debugger-tuning=gdb -v -resource-dir /usr/lib/clang/10.0.1 -fdebug-compilation-dir /root/musikcube/CMakeFiles/CMakeTmp -ferror-limit 19 -fmessage-length 0 -fwrapv -D_RET_PROTECTOR -ret-protector -fgnuc-version=4.2.1 -fobjc-runtime=gnustep -fdiagnostics-show-option -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-valloc -fno-builtin-free -fno-builtin-strdup -fno-builtin-strndup -faddrsig -o CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o -x c /usr/local/share/cmake/Modules/CMakeCCompilerABI.c
clang -cc1 version 10.0.1 based upon LLVM 10.0.1 default target amd64-unknown-openbsd6.8
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/clang/10.0.1/include
 /usr/include
End of search list.
Linking C executable cmTC_5ab4e
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5ab4e.dir/link.txt --verbose=1
/usr/bin/cc     -v CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o  -o cmTC_5ab4e  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib 
OpenBSD clang version 10.0.1 
Target: amd64-unknown-openbsd6.8
Thread model: posix
InstalledDir: /usr/bin
 "/usr/bin/ld" -e __start --eh-frame-hdr -Bdynamic -dynamic-linker /usr/libexec/ld.so -o cmTC_5ab4e /usr/bin/../lib/crt0.o /usr/bin/../lib/crtbegin.o -L/usr/bin/../lib -L/usr/lib CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o -rpath-link /usr/X11R6/lib:/usr/local/lib -lcompiler_rt -lc -lcompiler_rt /usr/bin/../lib/crtend.o

Parsed C implicit include dir info from above output: rv=done
  found start of include info
  found start of implicit include info
    add: [/usr/lib/clang/10.0.1/include]
    add: [/usr/include]
  end of search list found
  collapse include dir [/usr/lib/clang/10.0.1/include] ==> [/usr/lib/clang/10.0.1/include]
  collapse include dir [/usr/include] ==> [/usr/include]
  implicit include dirs: [/usr/lib/clang/10.0.1/include;/usr/include]

Parsed C implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /root/musikcube/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command(s):/usr/bin/make cmTC_5ab4e/fast && /usr/bin/make  -f CMakeFiles/cmTC_5ab4e.dir/build.make CMakeFiles/cmTC_5ab4e.dir/build]
  ignore line: [Building C object CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o]
  ignore line: [/usr/bin/cc   -v -o CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o   -c /usr/local/share/cmake/Modules/CMakeCCompilerABI.c]
  ignore line: [OpenBSD clang version 10.0.1 ]
  ignore line: [Target: amd64-unknown-openbsd6.8]
  ignore line: [Thread model: posix]
  ignore line: [InstalledDir: /usr/bin]
  ignore line: [ (in-process)]
  ignore line: [ "/usr/bin/cc" -cc1 -triple amd64-unknown-openbsd6.8 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 1 -pic-is-pie -mthread-model posix -mframe-pointer=all -relaxed-aliasing -fno-rounding-math -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -target-feature +retpoline-indirect-calls -target-feature +retpoline-indirect-branches -dwarf-column-info -fno-split-dwarf-inlining -debugger-tuning=gdb -v -resource-dir /usr/lib/clang/10.0.1 -fdebug-compilation-dir /root/musikcube/CMakeFiles/CMakeTmp -ferror-limit 19 -fmessage-length 0 -fwrapv -D_RET_PROTECTOR -ret-protector -fgnuc-version=4.2.1 -fobjc-runtime=gnustep -fdiagnostics-show-option -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-valloc -fno-builtin-free -fno-builtin-strdup -fno-builtin-strndup -faddrsig -o CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o -x c /usr/local/share/cmake/Modules/CMakeCCompilerABI.c]
  ignore line: [clang -cc1 version 10.0.1 based upon LLVM 10.0.1 default target amd64-unknown-openbsd6.8]
  ignore line: [#include "..." search starts here:]
  ignore line: [#include <...> search starts here:]
  ignore line: [ /usr/lib/clang/10.0.1/include]
  ignore line: [ /usr/include]
  ignore line: [End of search list.]
  ignore line: [Linking C executable cmTC_5ab4e]
  ignore line: [/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5ab4e.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/cc     -v CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o  -o cmTC_5ab4e  -Wl -rpath-link /usr/X11R6/lib:/usr/local/lib ]
  ignore line: [OpenBSD clang version 10.0.1 ]
  ignore line: [Target: amd64-unknown-openbsd6.8]
  ignore line: [Thread model: posix]
  ignore line: [InstalledDir: /usr/bin]
  link line: [ "/usr/bin/ld" -e __start --eh-frame-hdr -Bdynamic -dynamic-linker /usr/libexec/ld.so -o cmTC_5ab4e /usr/bin/../lib/crt0.o /usr/bin/../lib/crtbegin.o -L/usr/bin/../lib -L/usr/lib CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o -rpath-link /usr/X11R6/lib:/usr/local/lib -lcompiler_rt -lc -lcompiler_rt /usr/bin/../lib/crtend.o]
    arg [/usr/bin/ld] ==> ignore
    arg [-e] ==> ignore
    arg [__start] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [-Bdynamic] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/usr/libexec/ld.so] ==> ignore
    arg [-o] ==> ignore
    arg [cmTC_5ab4e] ==> ignore
    arg [/usr/bin/../lib/crt0.o] ==> ignore
    arg [/usr/bin/../lib/crtbegin.o] ==> ignore
    arg [-L/usr/bin/../lib] ==> dir [/usr/bin/../lib]
    arg [-L/usr/lib] ==> dir [/usr/lib]
    arg [CMakeFiles/cmTC_5ab4e.dir/CMakeCCompilerABI.c.o] ==> ignore
    arg [-rpath-link] ==> ignore
    arg [/usr/X11R6/lib:/usr/local/lib] ==> ignore
    arg [-lcompiler_rt] ==> lib [compiler_rt]
    arg [-lc] ==> lib [c]
    arg [-lcompiler_rt] ==> lib [compiler_rt]
    arg [/usr/bin/../lib/crtend.o] ==> ignore
  collapse library dir [/usr/bin/../lib] ==> [/usr/lib]
  collapse library dir [/usr/lib] ==> [/usr/lib]
  implicit libs: [compiler_rt;c;compiler_rt]
  implicit dirs: [/usr/lib]
  implicit fwks: []

Determining if the CXX compiler works passed with the following output:
Change Dir: /root/musikcube/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_7ad1d/fast && /usr/bin/make  -f CMakeFiles/cmTC_7ad1d.dir/build.make CMakeFiles/cmTC_7ad1d.dir/build
Building CXX object CMakeFiles/cmTC_7ad1d.dir/testCXXCompiler.cxx.o
/usr/bin/c++     -o CMakeFiles/cmTC_7ad1d.dir/testCXXCompiler.cxx.o -c /root/musikcube/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
Linking CXX executable cmTC_7ad1d
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7ad1d.dir/link.txt --verbose=1
/usr/bin/c++       CMakeFiles/cmTC_7ad1d.dir/testCXXCompiler.cxx.o  -o cmTC_7ad1d  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib 

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: /root/musikcube/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_ecd37/fast && /usr/bin/make  -f CMakeFiles/cmTC_ecd37.dir/build.make CMakeFiles/cmTC_ecd37.dir/build
Building CXX object CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o
/usr/bin/c++    -v -o CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o -c /usr/local/share/cmake/Modules/CMakeCXXCompilerABI.cpp
OpenBSD clang version 10.0.1 
Target: amd64-unknown-openbsd6.8
Thread model: posix
InstalledDir: /usr/bin
 (in-process)
 "/usr/bin/c++" -cc1 -triple amd64-unknown-openbsd6.8 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -mrelocation-model pic -pic-level 1 -pic-is-pie -mthread-model posix -mframe-pointer=all -relaxed-aliasing -fno-rounding-math -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -target-feature +retpoline-indirect-calls -target-feature +retpoline-indirect-branches -dwarf-column-info -fno-split-dwarf-inlining -debugger-tuning=gdb -v -resource-dir /usr/lib/clang/10.0.1 -internal-isystem /usr/include/c++/v1 -fdeprecated-macro -fdebug-compilation-dir /root/musikcube/CMakeFiles/CMakeTmp -ferror-limit 19 -fmessage-length 0 -fwrapv -D_RET_PROTECTOR -ret-protector -fgnuc-version=4.2.1 -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-valloc -fno-builtin-free -fno-builtin-strdup -fno-builtin-strndup -faddrsig -o CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o -x c++ /usr/local/share/cmake/Modules/CMakeCXXCompilerABI.cpp
clang -cc1 version 10.0.1 based upon LLVM 10.0.1 default target amd64-unknown-openbsd6.8
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/v1
 /usr/lib/clang/10.0.1/include
 /usr/include
End of search list.
Linking CXX executable cmTC_ecd37
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ecd37.dir/link.txt --verbose=1
/usr/bin/c++      -v CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o  -o cmTC_ecd37  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib 
OpenBSD clang version 10.0.1 
Target: amd64-unknown-openbsd6.8
Thread model: posix
InstalledDir: /usr/bin
 "/usr/bin/ld" -e __start --eh-frame-hdr -Bdynamic -dynamic-linker /usr/libexec/ld.so -o cmTC_ecd37 /usr/bin/../lib/crt0.o /usr/bin/../lib/crtbegin.o -L/usr/bin/../lib -L/usr/lib CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o -rpath-link /usr/X11R6/lib:/usr/local/lib -lc++ -lc++abi -lpthread -lm -lcompiler_rt -lc -lcompiler_rt /usr/bin/../lib/crtend.o

Parsed CXX implicit include dir info from above output: rv=done
  found start of include info
  found start of implicit include info
    add: [/usr/include/c++/v1]
    add: [/usr/lib/clang/10.0.1/include]
    add: [/usr/include]
  end of search list found
  collapse include dir [/usr/include/c++/v1] ==> [/usr/include/c++/v1]
  collapse include dir [/usr/lib/clang/10.0.1/include] ==> [/usr/lib/clang/10.0.1/include]
  collapse include dir [/usr/include] ==> [/usr/include]
  implicit include dirs: [/usr/include/c++/v1;/usr/lib/clang/10.0.1/include;/usr/include]

Parsed CXX implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /root/musikcube/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command(s):/usr/bin/make cmTC_ecd37/fast && /usr/bin/make  -f CMakeFiles/cmTC_ecd37.dir/build.make CMakeFiles/cmTC_ecd37.dir/build]
  ignore line: [Building CXX object CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o]
  ignore line: [/usr/bin/c++    -v -o CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o -c /usr/local/share/cmake/Modules/CMakeCXXCompilerABI.cpp]
  ignore line: [OpenBSD clang version 10.0.1 ]
  ignore line: [Target: amd64-unknown-openbsd6.8]
  ignore line: [Thread model: posix]
  ignore line: [InstalledDir: /usr/bin]
  ignore line: [ (in-process)]
  ignore line: [ "/usr/bin/c++" -cc1 -triple amd64-unknown-openbsd6.8 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -mrelocation-model pic -pic-level 1 -pic-is-pie -mthread-model posix -mframe-pointer=all -relaxed-aliasing -fno-rounding-math -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -target-feature +retpoline-indirect-calls -target-feature +retpoline-indirect-branches -dwarf-column-info -fno-split-dwarf-inlining -debugger-tuning=gdb -v -resource-dir /usr/lib/clang/10.0.1 -internal-isystem /usr/include/c++/v1 -fdeprecated-macro -fdebug-compilation-dir /root/musikcube/CMakeFiles/CMakeTmp -ferror-limit 19 -fmessage-length 0 -fwrapv -D_RET_PROTECTOR -ret-protector -fgnuc-version=4.2.1 -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-valloc -fno-builtin-free -fno-builtin-strdup -fno-builtin-strndup -faddrsig -o CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o -x c++ /usr/local/share/cmake/Modules/CMakeCXXCompilerABI.cpp]
  ignore line: [clang -cc1 version 10.0.1 based upon LLVM 10.0.1 default target amd64-unknown-openbsd6.8]
  ignore line: [#include "..." search starts here:]
  ignore line: [#include <...> search starts here:]
  ignore line: [ /usr/include/c++/v1]
  ignore line: [ /usr/lib/clang/10.0.1/include]
  ignore line: [ /usr/include]
  ignore line: [End of search list.]
  ignore line: [Linking CXX executable cmTC_ecd37]
  ignore line: [/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ecd37.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/c++      -v CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o  -o cmTC_ecd37  -Wl -rpath-link /usr/X11R6/lib:/usr/local/lib ]
  ignore line: [OpenBSD clang version 10.0.1 ]
  ignore line: [Target: amd64-unknown-openbsd6.8]
  ignore line: [Thread model: posix]
  ignore line: [InstalledDir: /usr/bin]
  link line: [ "/usr/bin/ld" -e __start --eh-frame-hdr -Bdynamic -dynamic-linker /usr/libexec/ld.so -o cmTC_ecd37 /usr/bin/../lib/crt0.o /usr/bin/../lib/crtbegin.o -L/usr/bin/../lib -L/usr/lib CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o -rpath-link /usr/X11R6/lib:/usr/local/lib -lc++ -lc++abi -lpthread -lm -lcompiler_rt -lc -lcompiler_rt /usr/bin/../lib/crtend.o]
    arg [/usr/bin/ld] ==> ignore
    arg [-e] ==> ignore
    arg [__start] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [-Bdynamic] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/usr/libexec/ld.so] ==> ignore
    arg [-o] ==> ignore
    arg [cmTC_ecd37] ==> ignore
    arg [/usr/bin/../lib/crt0.o] ==> ignore
    arg [/usr/bin/../lib/crtbegin.o] ==> ignore
    arg [-L/usr/bin/../lib] ==> dir [/usr/bin/../lib]
    arg [-L/usr/lib] ==> dir [/usr/lib]
    arg [CMakeFiles/cmTC_ecd37.dir/CMakeCXXCompilerABI.cpp.o] ==> ignore
    arg [-rpath-link] ==> ignore
    arg [/usr/X11R6/lib:/usr/local/lib] ==> ignore
    arg [-lc++] ==> lib [c++]
    arg [-lc++abi] ==> lib [c++abi]
    arg [-lpthread] ==> lib [pthread]
    arg [-lm] ==> lib [m]
    arg [-lcompiler_rt] ==> lib [compiler_rt]
    arg [-lc] ==> lib [c]
    arg [-lcompiler_rt] ==> lib [compiler_rt]
    arg [/usr/bin/../lib/crtend.o] ==> ignore
  collapse library dir [/usr/bin/../lib] ==> [/usr/lib]
  collapse library dir [/usr/lib] ==> [/usr/lib]
  implicit libs: [c++;c++abi;pthread;m;compiler_rt;c;compiler_rt]
  implicit dirs: [/usr/lib]
  implicit fwks: []

Performing C++ SOURCE FILE Test HAVE_CXX_ATOMICS64_WITHOUT_LIB succeeded with the following output:
Change Dir: /root/musikcube/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_429b0/fast && /usr/bin/make  -f CMakeFiles/cmTC_429b0.dir/build.make CMakeFiles/cmTC_429b0.dir/build
Building CXX object CMakeFiles/cmTC_429b0.dir/src.cxx.o
/usr/bin/c++    -DHAVE_CXX_ATOMICS64_WITHOUT_LIB -std=c++11   -o CMakeFiles/cmTC_429b0.dir/src.cxx.o -c /root/musikcube/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_429b0
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_429b0.dir/link.txt --verbose=1
/usr/bin/c++   -DHAVE_CXX_ATOMICS64_WITHOUT_LIB -std=c++11    CMakeFiles/cmTC_429b0.dir/src.cxx.o  -o cmTC_429b0  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib 

Source file was:

#include <atomic>
#include <cstdint>
std::atomic<uint64_t> x (0);
int main() {
  uint64_t i = x.load(std::memory_order_relaxed);
  return 0;
}

Performing C++ SOURCE FILE Test LLVM_HAS_ATOMICS succeeded with the following output:
Change Dir: /root/musikcube/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_c5a43/fast && /usr/bin/make  -f CMakeFiles/cmTC_c5a43.dir/build.make CMakeFiles/cmTC_c5a43.dir/build
Building CXX object CMakeFiles/cmTC_c5a43.dir/src.cxx.o
/usr/bin/c++    -DLLVM_HAS_ATOMICS   -o CMakeFiles/cmTC_c5a43.dir/src.cxx.o -c /root/musikcube/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_c5a43
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c5a43.dir/link.txt --verbose=1
/usr/bin/c++   -DLLVM_HAS_ATOMICS    CMakeFiles/cmTC_c5a43.dir/src.cxx.o  -o cmTC_c5a43  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib 

Source file was:

#ifdef _MSC_VER
#include <windows.h>
#endif
int main() {
#ifdef _MSC_VER
        volatile LONG val = 1;
        MemoryBarrier();
        InterlockedCompareExchange(&val, 0, 1);
        InterlockedIncrement(&val);
        InterlockedDecrement(&val);
#else
        volatile unsigned long val = 1;
        __sync_synchronize();
        __sync_val_compare_and_swap(&val, 1, 0);
        __sync_add_and_fetch(&val, 1);
        __sync_sub_and_fetch(&val, 1);
#endif
        return 0;
      }

Determining if the include file pthread.h exists passed with the following output:
Change Dir: /root/musikcube/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_8070d/fast && /usr/bin/make  -f CMakeFiles/cmTC_8070d.dir/build.make CMakeFiles/cmTC_8070d.dir/build
Building C object CMakeFiles/cmTC_8070d.dir/CheckIncludeFile.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_8070d.dir/CheckIncludeFile.c.o   -c /root/musikcube/CMakeFiles/CMakeTmp/CheckIncludeFile.c
Linking C executable cmTC_8070d
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8070d.dir/link.txt --verbose=1
/usr/bin/cc      CMakeFiles/cmTC_8070d.dir/CheckIncludeFile.c.o  -o cmTC_8070d  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib 

Determining if the function pthread_create exists in the pthread passed with the following output:
Change Dir: /root/musikcube/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_91cc6/fast && /usr/bin/make  -f CMakeFiles/cmTC_91cc6.dir/build.make CMakeFiles/cmTC_91cc6.dir/build
Building C object CMakeFiles/cmTC_91cc6.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_91cc6.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_91cc6
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_91cc6.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_91cc6.dir/CheckFunctionExists.c.o  -o cmTC_91cc6  -lpthread -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib `

CMakeError.log

`Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /root/musikcube/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_598eb/fast && /usr/bin/make  -f CMakeFiles/cmTC_598eb.dir/build.make CMakeFiles/cmTC_598eb.dir/build
Building C object CMakeFiles/cmTC_598eb.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_598eb.dir/src.c.o   -c /root/musikcube/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_598eb
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_598eb.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_598eb.dir/src.c.o  -o cmTC_598eb  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib 
ld: error: undefined symbol: pthread_create
>>> referenced by src.c
>>>               CMakeFiles/cmTC_598eb.dir/src.c.o:(main)

ld: error: undefined symbol: pthread_detach
>>> referenced by src.c
>>>               CMakeFiles/cmTC_598eb.dir/src.c.o:(main)

ld: error: undefined symbol: pthread_cancel
>>> referenced by src.c
>>>               CMakeFiles/cmTC_598eb.dir/src.c.o:(main)

ld: error: undefined symbol: pthread_join
>>> referenced by src.c
>>>               CMakeFiles/cmTC_598eb.dir/src.c.o:(main)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error 1 in . (CMakeFiles/cmTC_598eb.dir/build.make:107 'cmTC_598eb')
*** Error 2 in /root/musikcube/CMakeFiles/CMakeTmp (Makefile:141 'cmTC_598eb/fast')

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /root/musikcube/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_cf172/fast && /usr/bin/make  -f CMakeFiles/cmTC_cf172.dir/build.make CMakeFiles/cmTC_cf172.dir/build
Building C object CMakeFiles/cmTC_cf172.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_cf172.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_cf172
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cf172.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_cf172.dir/CheckFunctionExists.c.o  -o cmTC_cf172  -lpthreads -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib 
ld: error: unable to find library -lpthreads
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error 1 in . (CMakeFiles/cmTC_cf172.dir/build.make:107 'cmTC_cf172')
*** Error 2 in /root/musikcube/CMakeFiles/CMakeTmp (Makefile:141 'cmTC_cf172/fast')`

Missing lpthreads library?

Thank you for your support.

**Comment by clangen** [comment]
Weird, yeah, looks like it can't find pthreads; I want to say I've seen this problem before and the missing pthreads was a red-herring. Unfortunately I had a computer crash recently and lost all of my virtual machines. I have recently replaced it and will try to get a new OpenBSD VM up and running soon to see if I can figure out what's going on.

**Comment by dsotm1** [comment]
Thank you for your reply.
I'll try to run the last openbsd release on a vm too, to see if there is the same problem. Actually it's a 6.8 version on a mac mini 3,1.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by clangen** [comment]
I installed an OpenBSD 6.9 VM and did have some problems compiling and running the app, although it looked a bit different from the ones you posted. I just pushed a couple of fixes into the `master` branch. I'd say `git pull` and try again. Let me know if you still have any issues!

**Comment by dsotm1** [comment]
Thank you, I'll try asap and let you know.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by dsotm1** [comment]
Thank you very much, it works now.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rapenne-s** [comment]
There is a port for musikcube in OpenBSD since August 2021 https://github.com/openbsd/ports/tree/master/audio/musikcube , a binary package is available since OpenBSD 7.0
