### ISSUE TITLE
Systemd free distros?

### ISSUE THREAD

**Issue by hard-tek** [clangen/musikcube#456]
Hello,
so I wanted to install this, used to use on Manjaro and Arch all the time. 
Now I _upgraded_ to Artix which does not have systemd bloat and i get this : fatal error: systemd/sd-bus.h: No such file or directory

How can I install this in Artix?

Thanks.

**Comment by hard-tek** [comment]
Time to move to another player. 
No support here.

**Comment by PythonTryHard** [comment]
Seems to be related to #365

**Comment by hard-tek** [comment]
Managed to fix it.
Thank you.
