### ISSUE TITLE
Allow other D-Bus backends for the MPRIS plugin

### ISSUE THREAD

**Issue by ismaell** [clangen/musikcube#457]
It would be nice to enable other backends for the plugin, like the original libdbus.

BTW, the dependency is duplicated; it is stated in the main `CMakeLists.txt` and on the MPRIS plugin directory
- https://github.com/clangen/musikcube/blob/825adfcf2f4afc5006fcccb144f837524b836a26/CMakeLists.txt#L160
- https://github.com/clangen/musikcube/blob/fea06d9674bbe0a060c7d6c6cdad18353e7fa594/src/plugins/mpris/CMakeLists.txt#L6

**Comment by clangen** [comment]
This functionality was eventually added: https://github.com/clangen/musikcube/blob/master/src/plugins/mpris/CMakeLists.txt
