### ISSUE TITLE
Plugins Not Appearinjg

### ISSUE THREAD

**Issue by worldpe** [clangen/musikcube#462]
The MilkDrop 2 plugin is in the folder but does not appear in the configure plugins section, in addition it doesn't seem to be installed, in the latest version.
![image](https://user-images.githubusercontent.com/82988612/133014860-fc9c8ec9-96fe-4b62-a0be-1070179205eb.png)

**Comment by PythonTryHard** [comment]
What version of musikcube are you using? Because as far as I know Milkdrop is not supported on 64-bit releases.

**Comment by clangen** [comment]
Had to take a bit of a hiatus from working on musikcube, but I haven't seen this particular issue before.

To PythonTryHard's point, milkdrop does not work on 64-bit installations.

Closing this due to lack of correspondence, re-open if necessary!
