### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by Stefan-Yang93** [clangen/musikcube#467]
Hello.When I try to build the program, i got these errors, do you have some sugesstions for me. THANK YOU.

![屏幕截图 2021-09-29 204044](https://user-images.githubusercontent.com/83937998/135270857-4252190f-57f5-46d3-b083-c28cf2c1719e.png)

LNK1181:CAN NOT OPEN INPUT FILE "XXX.LIB"

**Comment by PythonTryHard** [comment]
When building on Windows, clone recursively first (`git clone --recursive https://github.com/clangen/musikcube` or `git clone --recursive ssh://git@github.com/clangen/musikcube`) as the missing `.lib`s are provided in a submodule located at `{repo_root}/src/3rdparty/bin`

**Comment by clangen** [comment]
Yep, what PythonTryHard said! :)
