### ISSUE TITLE
MusikDroid notification sometimes out of sync

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#482]
When listening to music with musikdroid, the notification with the currently playing song shows the previously playing song in some circumstances. I've observed the following:

- If the next song starts playing automatically (by reaching the end of the previous song), the song in the notification is the previous song. everything from the album art, title, colour of the notification etc are of the previous song.
- If the next song starts playing by pressing the next song button (either in the notification, in the musikdroid app, or with a hardware button), the correct song is shown
- If the next song starts playing by choosing a song in musikdroid, the correct song is shown
- Pressing pause (either in the notification, in the musikdroid app, or with a hardware button) causes the correct song to display.
- Bizarrely, the notification shown on the lock screen shows the correct song, even when the unlocked notification is wrong. Keeping the lock screen open while the song changes automatically shows the song updating as expected.
- Similarly, in my device's "Media" menu, the correct song is shown, even when the notification is wrong.

Tested on musikdroid 0.96.6, and android 11, on a samsung galaxy tab a7; let me know if any extra information is needed :)

Some screenshots to help illustrate the issue: in both of these, "REMEMBERTHEM" was the previous song, and "sweep me away" is the currently playing song, and the song changed automatically.

![media_view](https://user-images.githubusercontent.com/60542090/147375442-68137432-d7f1-4a95-a518-30171a8e7cc2.png)
![app_view](https://user-images.githubusercontent.com/60542090/147375443-eeafc297-4dac-40fd-ad9f-16b2e5002e1d.jpg)

**Comment by clangen** [comment]
I just put in what I believe to be a fix for this issue: https://github.com/clangen/musikcube/commit/d278728e01502489819e903ccd2647b88607c9a2

Hopefully we'll get a new release out within the next couple days.

**Comment by clangen** [comment]
New version released that should hopefully address this issue. https://github.com/clangen/musikcube/releases/tag/0.96.10

Please re-open this issue if the problem persists.
