### ISSUE TITLE
Library not loaded: @rpath/libmusikcore.dylib

### ISSUE THREAD

**Issue by sirlaurie** [clangen/musikcube#483]
version: 0.96.9 from brew
OS: macOS 12.1, M1 Max

error:

  Referenced from: /opt/homebrew/Cellar/musikcube/0.96.9/share/musikcube/musikcube
  Reason: tried: '$ORIGIN/libmusikcore.dylib' (no such file), '/tmp/musikcube-20211228-14092-6jr5kh/musikcube-0.96.9/bin/plugins/libmusikcore.dylib' (no such file), '/opt/openssl/lib/libmusikcore.dylib' (no such file), '/opt/ncurses/lib/libmusikcore.dylib' (no such file), '/tmp/musikcube-20211228-14092-6jr5kh/musikcube-0.96.9/bin/libmusikcore.dylib' (no such file), '$ORIGIN/libmusikcore.dylib' (no such file), '/tmp/musikcube-20211228-14092-6jr5kh/musikcube-0.96.9/bin/plugins/libmusikcore.dylib' (no such file), '/opt/openssl/lib/libmusikcore.dylib' (no such file), '/opt/ncurses/lib/libmusikcore.dylib' (no such file), '/tmp/musikcube-20211228-14092-6jr5kh/musikcube-0.96.9/bin/libmusikcore.dylib' (no such file), '/usr/local/lib/libmusikcore.dylib' (no such file), '/usr/lib/libmusikcore.dylib' (no such file)

**Comment by rikchilvers** [comment]
I also had this problem but building from source worked. I'm not familiar enough with homebrew to understand what might be the problem.

**Comment by clangen** [comment]
Yeah, sorry about this. I just released `0.96.10`, which should correct the issue. Please let me know if it resolves things on your end!

Just do a `brew update` and `brew reinstall musikcube`.

**Comment by sirlaurie** [comment]
> Yeah, sorry about this. I just released `0.96.10`, which should correct the issue. Please let me know if it resolves things on your end!
> 
> Just do a `brew update` and `brew reinstall musikcube`.

0.96.10 works! thanks!😃

**Comment by clangen** [comment]
Nice! Closing this ticket for now, but I encourage anyone with similar issues to re-open it.
