### ISSUE TITLE
Just a question about the releases

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#484]
I'm currently still on Mint 19.3 (based on bionic, going to upgrade soon).

I noticed that your newer releases now have a separate build for Mint.

For what reason? How is it different?

**Comment by clangen** [comment]
Hello! The `Mint` specific `deb` provided in the releases is for Mint 20.2 (`uma`), which is based on `focal` -- however we had a couple users complaining the standard `focal` build wasn't working properly, so we provided one custom build for `uma`.

Please re-open if issue if you have any additional questions!
