### ISSUE TITLE
musikcube freezes when trying to play anything

### ISSUE THREAD

**Issue by Freddson** [clangen/musikcube#488]
After just installing musikcube, I tried to try it out with some of the songs I had. But whenever I press enter to play anything, the app freezes completely. 
I think it might be because I don't have mpd installed, but I can't install it because it makes PulseAudio not work on my main driver. 
Is there any way I can fix this?

**Comment by clangen** [comment]
I've not heard of anyone having this problem, so I will probably need a bit more information to try to help you figure out what's going on.

First, keep in mind that `musikcube` does not rely on `mpd`, as it is a completely self-contained client and server with its own metadata indexer and playback engine... to that end, not having `mpd` will not be your problem.

Can you tell me:
1. What distribution of Linux you're using, and the version?
2. Which version of `musikcube` are you trying?
2. How you installed `musikcube` -- did you use pre-compiled binaries or build from source?
3. What type of files are you trying to play (e.g. `mp3`, `flac`, or something else)?
4. Which `output driver` are you using? It's configurable in the `settings` page. `musikcube` uses `PulseAudio` by default, but also supports `ALSA`, `PipeWire`, and a special `null` driver.
5. If you switch the `output driver` to `null` in settings, does it still freeze? Note no sound will come out your speakers, as it will play back to a "dummy" sound card to bypass driver issues.

**Comment by Freddson** [comment]
I am so sorry, it seems I did not set up the output device. After setting it to my monitor's speakers it works perfectly. Really sorry for taking your time.
