### ISSUE TITLE
Cannot Install in Ubuntu 20.04 (Focal)

### ISSUE THREAD

**Issue by xbais** [clangen/musikcube#494]
**Error** 
Cannot install 'libavcodec-extra'

**Steps to replicate:**
1. Install Gdebi Package installer in Ubuntu 20.04.3 LTS
2. Use the above to install the following file :https://github.com/clangen/musikcube/releases/download/0.96.10/musikcube_0.96.10_ubuntu_focal_amd64.deb

**Comment by clangen** [comment]
Dang, apologies for the issues here. I'll see about getting some updated packages built in the next day or two.

**Comment by clangen** [comment]
Actually, according to Ubuntu's website, `libcodec-extra` does exist: https://packages.ubuntu.com/focal/libavcodec-extra

I guess maybe you have to enable the `universe` deb repository in your `sources.list`?

**Comment by clangen** [comment]
This should also be solved by using a new "standalone" build introduced in the 0.96.11 release here: https://github.com/clangen/musikcube/releases/tag/0.96.11.
