### ISSUE TITLE
compile error in artix linux with openrc

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#498]
On the Artix Linux with OpenRC does not compile because asking Systemd - something can be done in this regard? 

`artix:[cristian]:~/Git/musikcube$ make
[  0%] Building CXX object src/plugins/mpris/CMakeFiles/mpris.dir/mpris.cpp.o
In file included from /home/cristian/Git/musikcube/src/plugins/mpris/mpris.cpp:2:
/home/cristian/Git/musikcube/src/plugins/mpris/mpris.h:11:14: fatal error: systemd/sd-bus.h: No such file or directory
   11 |     #include <systemd/sd-bus.h>
      |              ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/plugins/mpris/CMakeFiles/mpris.dir/build.make:76: src/plugins/mpris/CMakeFiles/mpris.dir/mpris.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:823: src/plugins/mpris/CMakeFiles/mpris.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`

**Comment by clangen** [comment]
You should be able to compile with: `cmake -DENABLE_MPRIS=false .` followed by your standard `make` and `make install`
