### ISSUE TITLE
Broken track order between formats

### ISSUE THREAD

**Issue by Pharaoh47** [clangen/musikcube#517]
I have an music library. I use Musikcube as it very beauty and powerful instrument.

Yet i found one bug. I will illustrate it.

When one album contains several formats (mp3 and flac for example) the order of tracks is broken.

On the images buggy library listing. Name and order of files (Dolphin). And ID tags in editor (Kid3).

![01](https://user-images.githubusercontent.com/61421807/165674193-1a2cfed5-63f1-4ed2-a66d-a9631a8574f8.png)
![02](https://user-images.githubusercontent.com/61421807/165674195-8be8f194-7888-453c-9ffb-4910d543d6b9.png)
![03](https://user-images.githubusercontent.com/61421807/165674198-4c04ad59-2660-4ab3-a538-766757d39a40.png)
![04](https://user-images.githubusercontent.com/61421807/165674201-303f50b4-609b-4ef6-a1a8-a36c88f1b042.png)
.

**Comment by clangen** [comment]
Thanks for the report, this bug has been fixed and will be part of the next release: https://github.com/clangen/musikcube/commit/2f76c61ea3cbacabccf78f882120465cd7121a7b

**Comment by clangen** [comment]
Fix has been released: https://github.com/clangen/musikcube/releases/
