### ISSUE TITLE
Incompatibility with Older RasPi models

### ISSUE THREAD

**Issue by EmmettW** [clangen/musikcube#518]
After successfully installing the latest standalone .deb package, 
Running `musikcube` returns `Illegal instruction` and does not start. 

This is on a 2013 Raspberry Pi Model B, 
Running the latest Raspberry Pi OS - v11 Bullseye. 

Previously musikcube was working with v0.96.7 
The same Pi board was running Raspberry Pi OS v10 - Buster

**Comment by cruzzoe** [comment]
I have the same issue running a RaspberryPi Zero running latest version of Pi OS (32bit)

**Comment by clangen** [comment]
I found an issue with the way we packaged the most previous couple releases for Raspberry Pi, so this may be fixed now. I'm planning to release 0.99.0 soon, which should hopefully address the issue.

**Comment by clangen** [comment]
Possibly fixed in https://github.com/clangen/musikcube/releases/0.99.0 ... let me know if you are still seeing the issue.

**Comment by EmmettW** [comment]
Still seeing the issue.
Did some research and found it's most likely because musikcube is using ARMv7 or later, and the Pi A/B/B+/Zero only support ARMv6. Oh well. :(

**Comment by sans-c** [comment]
I know this issue was closed, I still have to ask: is there a potential fix? The instructions do not mention that musikcube wont run on older raspberrys. I am running into exactly the same issue on an old Pi B (armv6).

**Comment by peterhavener** [comment]
Same issue here on a Raspberry Pi Zero W (2017) on Raspbian 12 Bookworm. Tried 0.99 package as well as latest 3.0.1 package, same issue get **Illegal instruction**.

Output of **cat /etc/os-release**
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
