### ISSUE TITLE
ape file not supported

### ISSUE THREAD

**Issue by hkloudou** [clangen/musikcube#527]
log:
ffmpegdecoder: invalid packet detected,discarding

**Comment by hkloudou** [comment]
[ffmpegdecoder]resolved codec: Monkey's Audio

**Comment by hkloudou** [comment]
and,what about show bit rate on the dashboard

**Comment by hkloudou** [comment]
i try play ape use ffplay,it worked,  but musikcuke not work

**Comment by clangen** [comment]
Thank you, I've just found a work around for the problem: https://github.com/clangen/musikcube/commit/64c7521a9de2a403640c60be6ee4f3c87e23674a

APE files should be playable again in the next release, which I'll hopefully get out soon.

**Comment by hkloudou** [comment]
thanks,waiting for your release :)

**Comment by clangen** [comment]
Fix has been released. https://github.com/clangen/musikcube/releases/
