### ISSUE TITLE
Cannot build musikcube 0.98 under macOS with PulseAudio installed

### ISSUE THREAD

**Issue by lugia-kun** [clangen/musikcube#530]
I could not build musikcube 0.98 under macOS 12.4 on x86_64 using Homebrew.

```
[  4%] Building CXX object src/plugins/gmedecoder/CMakeFiles/gmedecoder.dir/GmeDataStream.cpp.o
In file included from /tmp/musikcube-20220707-20832-77eqsa/musikcube-0.98.0/src/plugins/pulseout/pulseout_plugin.cpp:35:
/tmp/musikcube-20220707-20832-77eqsa/musikcube-0.98.0/src/plugins/pulseout/pch.h:41:10: fatal error: 'alsa/asoundlib.h' file not found
#include <alsa/asoundlib.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
```

Complete log: [homebrew-logs.zip](https://github.com/clangen/musikcube/files/9063920/homebrew-logs.zip)

I noticed that the pluseout plugin had been enabled. So I removed PulseAudio. After that, it was compiled fine.

I'm using PulseAudio to communicate to a server, and it's not related to musikcube. So, I'm OK with disabling pulseout on macOS. Just note that PulseAudio can be installed without ALSA, especially in non-Linux OSs.

**Comment by clangen** [comment]
Yep, looks like the ALSA header file was being erroneously included in the PulseAudio output plugin. I just pushed a fix to `master`. Please re-open if you still have issues.
