### ISSUE TITLE
musikcube 0.98.0 aborts when installed using nixpkgs on Darwin

### ISSUE THREAD

**Issue by afh** [clangen/musikcube#538]
```sh
% musikcube
dyld[15146]: Library not loaded: '@rpath/libmusikcore.dylib'
  Referenced from: '/nix/store/ps30cd8hjdcvfkkaw7zlxq4jirriydd6-musikcube-0.98.0/share/musikcube/musikcube'
  Reason: tried: '/tmp/nix-build-musikcube-0.98.0.drv-0/source/bin/plugins/libmusikcore.dylib' (no such file), \
  '/tmp/nix-build-musikcube-0.98.0.drv-0/source/bin/libmusikcore.dylib' (no such file), \
  '/nix/store/dqys7wakpcglls1l3khlncvgr1rc94b0-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/libmusikcore.dylib' (no such file), \
  '/tmp/nix-build-musikcube-0.98.0.drv-0/source/bin/plugins/libmusikcore.dylib' (no such file), \
  '/tmp/nix-build-musikcube-0.98.0.drv-0/source/bin/libmusikcore.dylib' (no such file), \
  '/nix/store/dqys7wakpcglls1l3khlncvgr1rc94b0-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/libmusikcore.dylib' (no such file), \
  '/usr/local/lib/libmusikcore.dylib' (no such file), \
  '/usr/lib/libmusikcore.dylib' (no such file)
zsh: abort      musikcube
```

It's possible for me to run musikcube by setting:
`DYLD_LIBRARY_PATH=$(dirname $(dirname $(readlink $(readlink $(which musikcube)))))/share/musikcube` 

Version 0.97.0 of musikcube ran without issues when installed via nixpkgs on Darwin; looking at the [changes introduced with 0.98.00](https://github.com/clangen/musikcube/compare/0.97.0...0.98.0) there seem to be several changes to `cmake` related files, which may have tampered with `@rpath`.
The changes in the [nixpkgs related file are minimal](https://github.com/NixOS/nixpkgs/pull/181107), though something may have changed in nixpkgs in general, that may be responsible here.

Please find below a directory tree of what is installed via nixpkgs.
Something I'm curious about is what the wrapper in `bin/musikcube` (built from [musikcube.in](https://github.com/clangen/musikcube/blob/master/src/musikcube/musikcube.in)) is for? What is the motivation to install the musikcube binary in share and cd into it before exec?

<details><summary><code>% tree $(readlink $(readlink $(which musikcube)))/../../</code></summary>

```sh

/nix/store/ps30cd8hjdcvfkkaw7zlxq4jirriydd6-musikcube-0.98.0
├── bin
│   ├── musikcube
│   └── musikcubed
├── include
│   └── musikcube
│       └── musikcore
│           └── sdk
│               ├── DataBuffer.h
│               ├── Filesystem.h
│               ├── HttpClient.h
│               ├── IAllocator.h
│               ├── IAnalyzer.h
│               ├── IBlockingEncoder.h
│               ├── IBuffer.h
│               ├── IBufferProvider.h
│               ├── IDSP.h
│               ├── IDataStream.h
│               ├── IDataStreamFactory.h
│               ├── IDebug.h
│               ├── IDecoder.h
│               ├── IDecoderFactory.h
│               ├── IDevice.h
│               ├── IEncoder.h
│               ├── IEncoderFactory.h
│               ├── IEnvironment.h
│               ├── IIndexerNotifier.h
│               ├── IIndexerSource.h
│               ├── IIndexerWriter.h
│               ├── IMap.h
│               ├── IMapList.h
│               ├── IMetadataProxy.h
│               ├── IOutput.h
│               ├── IPcmVisualizer.h
│               ├── IPlaybackRemote.h
│               ├── IPlaybackService.h
│               ├── IPlugin.h
│               ├── IPreferences.h
│               ├── IResource.h
│               ├── ISchema.h
│               ├── ISpectrumVisualizer.h
│               ├── IStreamingEncoder.h
│               ├── ITagReader.h
│               ├── ITagStore.h
│               ├── ITrack.h
│               ├── ITrackList.h
│               ├── ITrackListEditor.h
│               ├── IValue.h
│               ├── IValueList.h
│               ├── IVisualizer.h
│               ├── ReplayGain.h
│               ├── String.h
│               └── constants.h
└── share
    └── musikcube
        ├── libmusikcore.dylib
        ├── locales
        │   ├── de_DE.json
        │   ├── en_US.json
        │   ├── es_ES.json
        │   ├── fr_FR.json
        │   ├── it_IT.json
        │   ├── ja_JP.json
        │   ├── ru_RU.json
        │   └── zh_CN.json
        ├── musikcube
        ├── musikcubed
        ├── plugins
        │   ├── libcoreaudioout.dylib
        │   ├── libffmpegdecoder.dylib
        │   ├── libgmedecoder.dylib
        │   ├── libhttpdatastream.dylib
        │   ├── libmacosmediakeys.dylib
        │   ├── libnullout.dylib
        │   ├── libopenmptdecoder.dylib
        │   ├── libserver.dylib
        │   ├── libstockencoders.dylib
        │   ├── libsupereqdsp.dylib
        │   └── libtaglibreader.dylib
        └── themes
            ├── gruvbox_dark.json
            ├── solarized_dark.json
            └── solarized_light.json

10 directories, 72 files
```

</details>

**Comment by afh** [comment]
I'm seeing the following in the nixpkgs build output:
```sh
  -- Build files have been written to: /tmp/nix-build-musikcube-0.98.0.drv-0/source/build
  error: /nix/store/cqld0cli2q9ghdq14y2j3i360a40c60d-cctools-binutils-darwin-949.0.1/bin/install_name_tool: can't open file: bin/musikcube (No such file or directory)
  error: /nix/store/cqld0cli2q9ghdq14y2j3i360a40c60d-cctools-binutils-darwin-949.0.1/bin/install_name_tool: can't open file: bin/musikcube (No such file or directory)
  error: /nix/store/cqld0cli2q9ghdq14y2j3i360a40c60d-cctools-binutils-darwin-949.0.1/bin/install_name_tool: can't open file: bin/musikcubed (No such file or directory)
  error: /nix/store/cqld0cli2q9ghdq14y2j3i360a40c60d-cctools-binutils-darwin-949.0.1/bin/install_name_tool: can't open file: bin/musikcubed (No such file or directory)
```

which may hint at an issue the path of where `script/patch-macos-rpath.sh` is invoked. I'll keep digging…

[nixpkgs build output](https://github.com/clangen/musikcube/files/9189817/build.log)

**Comment by afh** [comment]
I tried changing `.cmake/PostBuild.cmake`, so that it passes `${CMAKE_CURRENT_BINARY_DIR}` to `patch-macos-rpath.sh` and that script then uses the passed argument to locate the files, unfortunately that fails with the following error: 🤔 

```sh
option "-add_rpath @executable_path/lib" would duplicate path, file already has LC_RPATH for: @executable_path/lib
```

**Comment by clangen** [comment]
Unfortunately I don't know anything about nixpkgs, so I'm not sure how much help I can be :(

> Something I'm curious about is what the wrapper in bin/musikcube (built from [musikcube.in](https://github.com/clangen/musikcube/blob/master/src/musikcube/musikcube.in)) is for? What is the motivation to install the musikcube binary in share and cd into it before exec?

Yeah -- musikcube loads its plugins based on relative path; it'll automatically discover dynamic libraries in the `plugins/` sub-directory relative to wherever the executable is (i.e. `/path/to/musikcube/plugins/`. I did this so the installation directory can be relocated easily without recompiling. So, basically, all of the musikcube files are generally installed to `<prefix>/share/musikcube/`, then there's a small shell script installed to `<prefix>/bin/` that changes directory to to the `<prefix>/share/musikcube/` directory and starts the app.

**Comment by afh** [comment]
Thanks for the quick response, @clangen.

As I'm also just learning more about Nix and nixpkgs I believe for the time being the pragmatic path forward here is to address this in nixpkgs as the issue surfaces there (for proposed workaround see [NixOS/nixpkgs#182867](https://github.com/NixOS/nixpkgs/pull/182867)).

Apart from that I think it would be good to keeping an eye out for rpath related issues on Darwin and remember this issue to see if it can be address here.

The use of relative paths `patch-macos-rpath.sh` seems like a bit of a code smell to me, so I might continue to look into this, just to learn more about musikcube, Nix, CMake, rpath, etc. and back to you on this if I have a better understanding of even fix :)
