### ISSUE TITLE
Question: How to rescan when running as daemon 

### ISSUE THREAD

**Issue by jondoe1337** [clangen/musikcube#540]
What is the way to go when running as daemon and adding new content? `musikcubed` doesn't have any docs about triggering a rescan. Is it possible to trigger that via SIGUSR1 or other signals? I guess currently we have to restart the daemon right?

**Comment by clangen** [comment]
Great idea. This isn't currently possible we'll get this into the next release.

**Comment by clangen** [comment]
https://github.com/clangen/musikcube/commit/3998b759f75b3f58654c27686513e0b314e52043

**Comment by clangen** [comment]
https://github.com/clangen/musikcube/releases/0.99.0
