### ISSUE TITLE
Playback is clipping when using PipeWire ouput driver

### ISSUE THREAD

**Issue by Fuzzy-Math** [clangen/musikcube#544]
Intervalic clipping during playback when using PipeWire backened. Issue not present when using PulseAudio or ALSA backened. Occurs across output devices (BT or wired headphones). Occurs across multiple encodings, bitrates, and bitdepths.

Musikcube version: 0.98.0 #6a440c69
OS: openSUSE Tumbleweed 5.19.8
pulseaudio: not installed
pulseaudio-utils: 16.1
pipewire/pipewire-pulseaudio: 0.3.58

**Comment by clangen** [comment]
Added some new settings in the 0.98.1 release to allow the user to adjust PipeWire buffer sizes. They are available in `settings` >`configure plugins` > `PipeWire IOutput` > `enter`

![image](https://user-images.githubusercontent.com/2031666/205806751-bb91b061-a5a8-44c8-b59d-40f866bb521a.png)
