### ISSUE TITLE
musikcube can't to find boost-libs 1.80.0

### ISSUE THREAD

**Issue by ZhengweiHou** [clangen/musikcube#548]
➜  musikcube
./musikcube: error while loading shared libraries: libboost_filesystem.so.1.79.0: cannot open shared object file: No such file or directory
➜  yay -Qs libboost_filesystem
local/boost-libs 1.80.0-2
    Free peer-reviewed portable C++ source libraries (runtime libraries)

**Comment by clangen** [comment]
Yeah, boost is the largest thorn in our side -- every time a new version drops and distros upgrade to it, musikcube breaks and needs to be recompiled/reinstalled. This is one of the main reasons we have started distributing binaries in our release page; the binaries we provide ship with their own version of boost and are not subject to operating system / distribution upgrades.

So, you can recompile to work around the issue, but if you don't want to mess with it I suggest installing the latest release binaries from here: https://github.com/clangen/musikcube/releases

Hopefully in the future we can get rid of boost entirely, but it'll be a non-trivial amount of work.
