### ISSUE TITLE
Twice tracks names

### ISSUE THREAD

**Issue by 237dmitry** [clangen/musikcube#550]
In playlist every track repeated and full playtime in header is incorrect:

![Screenshot 2022-10-27 120740](https://user-images.githubusercontent.com/78153320/198243320-d4afedf2-8df6-40af-afdb-a09afc43b57f.png)

Win 11 22H2
musikcube.exe & musikcube-cmd.exe: 0.98.1

**Comment by 237dmitry** [comment]
Workaround:
1. Delete by hand old database in `$env:AppData\musikcube\1\*`
2. Launch musikcube and choose library.
3. After rescan all is fine.
4. Profit

**Comment by clangen** [comment]
That's really weird. If you can figure out how to reproduce the issue moving forward, please provide steps. Closing for now...

**Comment by 237dmitry** [comment]
In 0.99 the problem is not reproduced.
