### ISSUE TITLE
v0.8.1 | Audio dropouts | Pulseaudio, Pipewire

### ISSUE THREAD

**Issue by 38github** [clangen/musikcube#553]
I experience dropouts every now and then. I have increased the buffer size for Pipewire but it continues to behave the same way. Even when using Pulseaudio. Can it be a low caching of files that creates this issue? I have no problem at all using Pipewire or Pulseaudio other than in Musikcube.

I use Void Linux x86_64 (Glibc) on a capable computer.

**Comment by 38github** [comment]
I tried to play a 96/24 FLAC and it sounds like I have activated a tremolo effect when I use Pipewire but not with Pulseaudio.

**Comment by 38github** [comment]
It seems that I have solved it by increasing Pipewire's output_buffer_count 16 to 32 and output_buffer_size_in_samples from 1024 to 4096.

**Comment by 38github** [comment]
I still had issues with opus files created with --framesize 5 and had to increase output_buffer_size_in_samples to 8192 for dropouts to stop occuring. At least I have not heard one in ten minutes.

**Comment by clangen** [comment]
Sorry, I've been busy with other things recently. It sounds like this issue has been resolved by adjusting buffer sizes, so I'm going to go ahead and close it :)

Please re-open if you are still having issues.
