### ISSUE TITLE
any plugin documentation?

### ISSUE THREAD

**Issue by Sakooooo** [clangen/musikcube#554]
would like to try to make something for musikcube

**Comment by clangen** [comment]
Unfortunately there's not really -- I really need to add some. There is some ancient documentation that describes how things work at a high level here: https://github.com/clangen/musikcube/blob/wiki/PluginAPI.md

All interfaces available to plugins can be found in the `sdk` directory here: https://github.com/clangen/musikcube/tree/master/src/musikcore/sdk

It should be relatively easy to pattern match existing plugins, though. I'm happy to help with specific questions if you have any. What type of plugin are you interesting in developing?

**Comment by Sakooooo** [comment]
> Unfortunately there's not really -- I really need to add some. There is some ancient documentation that describes how things work at a high level here: https://github.com/clangen/musikcube/blob/wiki/PluginAPI.md
> 
> 
> 
> All interfaces available to plugins can be found in the `sdk` directory here: https://github.com/clangen/musikcube/tree/master/src/musikcore/sdk
> 
> 
> 
> It should be relatively easy to pattern match existing plugins, though. I'm happy to help with specific questions if you have any. What type of plugin are you interesting in developing?

thinking of developing a really quick and fast discord rpc thing for musikcube because it would be a waste of time to directly integrate it into musikcube

**Comment by Sakooooo** [comment]
closing cause inactive and got answer
