### ISSUE TITLE
Not all directories showing up when adding.

### ISSUE THREAD

**Issue by AbramHansen** [clangen/musikcube#555]
I'm using musikcube on the Ubuntu for WSL. When I enter the home directory of my windows install (/mnt/c) only 6 directories are listed.

**Comment by clangen** [comment]
musikcube will only show directories for which it has found and indexed music -- do any of the missing directories contain audio files? :)

**Comment by AbramHansen** [comment]
Yes. The reason im looking for the folder is to index it

**Comment by clangen** [comment]
Oh, I see, this is while adding music, not when browsing already-added stuff by directory. Interesting. I was able to reproduce the issue -- I'll see if I can figure out what's going on...

**Comment by clangen** [comment]
Thanks for reporting this, the issue has been fixed and will be part of the next release.

**Comment by clangen** [comment]
Fixed in https://github.com/clangen/musikcube/releases/0.99.0
