### ISSUE TITLE
Portable / Haiku audio output support

### ISSUE THREAD

**Issue by extrowerk** [clangen/musikcube#561]
Hi,

i'd liek to use musikcube on Haiku, but there is no supported audio output module exists for Haiku. Please consider to either:
- add native Haiku mediakit support
- add PortAudio output support
- add SDL audio output

0.98 builds on Haiku, and even works as a streaming server, but no local playback is possible for now.

Thank You very much!

**Comment by clangen** [comment]
Good idea! I just checked in some changes so it should build without modifying CMakeLists on Haiku, which is a good first step. I'll see about adding a PortAudio output driver in the near future!

**Comment by clangen** [comment]
OK, I've added a `PortAudio` output plugin that should work in Haiku. I've tested the plugin in Linux and macOS and it seems fine -- I also briefly tested on Haiku in a VM and it seemed OK, but it was a bit hard to tell if audio quality was fine. 

I tried Haiku on some physical hardware, but I was unable to get it to connect to the network, so I wasn't able to pull down and build musikcube. @extrowerk: If you'd like, give it a try on your end and let me know what you find.

**Comment by extrowerk** [comment]
Thanks, i will builld it and report back.

**Comment by extrowerk** [comment]
Latest master builds and work OK on Haiku. Audio quality seems to be OK.

![screenshot295](https://user-images.githubusercontent.com/5569059/210139103-f8df50b1-62e8-4d5b-a1d2-260397117a05.png)

Thank You very much!

**Comment by clangen** [comment]
Awesome, this will go into the next release! Thanks for testing!

**Comment by extrowerk** [comment]
I just made a recipe for musikcube to be built and packaged automatically for Haiku. I had to adjust the install paths, consider to implement my changes upstream:

https://github.com/haikuports/haikuports/pull/7716
