### ISSUE TITLE
Bashism breaks build on OBSD

### ISSUE THREAD

**Issue by extrowerk** [clangen/musikcube#571]
The /script/post-build.sh file is invoked during the build phase. It's hashbang asks to be interpreted by bash, but bash is not necessarily available on BSD systems.

Modifying the hashbang to ```#!/bin/sh``` seems to be working on OpenBSD. Please consider to not use bashism in the script.

**Comment by clangen** [comment]
Thanks for the heads up -- I converted the script (and a couple others that are essential to the regular build process) from `bash` to `sh`. https://github.com/clangen/musikcube/commit/1f60f7c1d82481b45894f2763aeb7f090171d554

Closing this issue -- if you still see problems please re-open and tag me.

**Comment by extrowerk** [comment]
Thanks a lot!
