### ISSUE TITLE
How do I confirm musikcube is using alsa?

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#577]
I don't think my musikcube install is using alsa.

How do I know? Well, I installed strawberry and have configured it to use alsa (+ using my DAC + hw 0:0). If I play youtube on the browser and then try playing on strawberry , I'll get a message that goes like "playback device is busy right now". I have to stop the Youtube playback first before strawberry starts playing music. If I play on strawberry first and then try to play a Youtube video, the Youtube video is silent.

If I do same with musikcube, I can hear sound from both musikcube and Youtube.

Any ideas? Thanks

(card 0 is my DAC)

[myuser@fedora ~]$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Series [Mini-i Series], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 8: HDMI 2 [Dell AW3821DW]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 11: HDMI 5 [HDMI 5]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
  
-------------
Output driver: alsaout
Output device:  I've tried everything you can see on the screenshot. (there's a few more HDMI ones but I think those refer to my AMD video card. Also, "front:CARD=series,dev=0" up to "iec958:CARD=series,dev=0" only shows up if I turn on the DAC)

![Screenshot from 2023-02-12 22-55-51](https://user-images.githubusercontent.com/5241882/218311425-439de6e1-4976-485b-8e77-de67dc6b0173.png)

**Comment by clangen** [comment]
I can see from the screenshot that you're using alsa -- the `output driver` is set to `AlsaOut` -- but I see that your alsa configuration can seemingly render to `pipewire`. I'm not exactly sure how that works, though.

All that said, I'm a little confused by the problem. The issue is you only one want app to be able to play music at the same time? In other words, you don't want to hear musikcube playing while youtube does?
