### ISSUE TITLE
missing libavcodec.so.59/Update to libavcodec.so.60

### ISSUE THREAD

**Issue by Argonlifesee** [clangen/musikcube#589]
### Discussed in https://github.com/clangen/musikcube/discussions/587

<div type='discussions-op-text'>

<sup>Originally posted by **Argonlifesee** March 12, 2023</sup>
With the update to the libvacodec.so.60 Musikcube does not find libavcodec.so.59, which makes perfect sense as it has been replaced with the newer version, so my question is there away to get musikcube to use libavcodec.so.60. I downloaded it from the Aur and am on version 0.99.5
</div>

**Comment by clangen** [comment]
Yeah, this is annoying. You'll either need to (1) reinstall `musikcube` from AUR to force a re-link against the new library names, or (2) install `musikcube-bin` that will use pre-compiled/pre-bundled versions of the libraries.
