### ISSUE TITLE
is there any command-line features (or docs about) ? is there a way to write `musikcube play ./smth.flac` ?

### ISSUE THREAD

**Issue by Arniiiii** [clangen/musikcube#595]
I would be pleased to know if i can type smth like that and get it playing it? 
And if yes, can it be, that if the player shows smth in directory mode, it shows in left side audios from the folder where it is?

It would be really great. Because right now i can go to a folder in my file explorer, then send an audio to the musikcube, but musikcube does nothing, just uses the last audios it played. If this would be implemented in any way, Musikcube would be a great replacement even for Windows's foobar2000.

I tried `musikcube --help` or `man musikcube` but there's nothing. Here at wiki there's nothing about too.

**Comment by clangen** [comment]
`musikcube` doesn't currently support terminal-based playback of files outside the context of the main app, and I don't think I'll be adding that functionality any time soon; lots of other apps, e.g. `ffplay` (which is part of `ffmpeg` and usually readily available) do this quite well.
