### ISSUE TITLE
Volume and progress slider do not render properly in SteamOS (Arch)

### ISSUE THREAD

**Issue by m3talslug** [clangen/musikcube#596]
I have encoding set to Unicode.  This happens in Konsole or Fish.  I tried searching the terms "rendering musikcube ascii" and did not find anything helpful. This build: musikcube_linux_x86_64_0.99.5.tar.bz2 

![Screenshot_20230412_093951](https://user-images.githubusercontent.com/48932579/231476299-7dc01da6-1dcf-4bff-9f89-237cfc270bb0.png)

**Comment by clangen** [comment]
What is the value of the `LANG` environment variable in your shell? `env | grep LANG`

Does it work if you set `LANG` environment variable to something like `C.UTF8`? For example: `LANG=C.UTF-8 musikcube`

**Comment by m3talslug** [comment]
> env |grep LANG
LANGUAGE=
LANG=en_CA.UTF-8

It is on UTF8.  Let me see whether changing it to US from CA would work.  The strange thing is the line character they use for the volume and progress look very similar to the borders around the windows within musikcube.  And those borders seem to render properly.

**Comment by m3talslug** [comment]
> What is the value of the `LANG` environment variable in your shell? `env | grep LANG`
> 
> Does it work if you set `LANG` environment variable to something like `C.UTF8`? For example: `LANG=C.UTF-8 musikcube`

I changed the language to C and for some reason it is now working:

> env |grep LANG
LANGUAGE=C
LANG=C

Thanks a lot for your help!

![Screenshot_20230412_191112](https://user-images.githubusercontent.com/48932579/231605773-fe2da06b-8d20-402b-a8ff-78482ce47d21.png)
