### ISSUE TITLE
Cyrillic input is broken since 0.99.8

### ISSUE THREAD

**Issue by adem4ik** [clangen/musikcube#597]
Version: win64_0.99.8
OS: Windows 10 x64

1. Start musikcube
2. Open `filter` tab
3. Switch to Russian keyboard layout
4. Start typing

Result: broken non-cyrillic text
![image](https://user-images.githubusercontent.com/4707112/231955409-bbe7bb81-974f-472d-9852-e393cc92c0cc.png)

Expected result: as it was in 0.99.5
![image](https://user-images.githubusercontent.com/4707112/231955556-097fd440-1634-4924-9799-85a8ca2029b2.png)

**Comment by clangen** [comment]
Yikes. Thanks for the report. I'll try to look into this tomorrow.

**Comment by 237dmitry** [comment]
I could reproduce in windows version but not in linux:

![ArcoLinux_2023-04-14_16-24-54](https://user-images.githubusercontent.com/78153320/232056211-7972134d-0cb0-4b81-b51e-95e9eebf1c7f.png)

**Comment by clangen** [comment]
OK, I think I found the issue. Can you confirm the following build fixes the problem?

* [musikcube_win32_0.99.9.zip](https://github.com/clangen/musikcube/files/11236649/musikcube_win32_0.99.9.zip)
* [musikcube_win64_0.99.9.zip](https://github.com/clangen/musikcube/files/11236651/musikcube_win64_0.99.9.zip)

**Comment by adem4ik** [comment]
@clangen Yes, it is fixed in both builds.
