### ISSUE TITLE
When caps lock is on input letters do not work

### ISSUE THREAD

**Issue by cbugk** [clangen/musikcube#599]
On windows release 0.99.8

I have just come across this bit of software, and within the minute I was baffled not being able to have command over it via shortcuts listed on the bottom pane (with and without CTRL (^) or ALT). Turns out Caps Lock was on.

I believe input should not distinguish between capital and lowercase letters unless otherwise necessary.

**Comment by clangen** [comment]
Terminal apps don't have the ability to query the state of Caps Lock -- at least in a reliable, platform agnostic way. There may be some super hacky ways to do it, but I don't see myself doing it anytime soon. :/
