### ISSUE TITLE
[Bug][3.0.0] Special/foreign characters in artist names messed up on Musikdroid

### ISSUE THREAD

**Issue by Travisyard** [clangen/musikcube#602]
Just updated to Musikdroid 3.0.0. Some artists names are messed up. In the below screenshot, the artist below Yelle is in Cyrillic characters, then the two artists below that are in Japanese characters. Strangely, the bottom Japanese one seems unaffected.

![Screenshot_20230422-234006_1](https://user-images.githubusercontent.com/32996640/233820323-7e8129c7-36a8-4073-b570-be32ef06dc2d.png)

Here is an example of it happening with accents on Latin characters (expecting ö in both cases).

![Mdissue5](https://user-images.githubusercontent.com/32996640/233820464-5026a011-a29e-4869-b0d5-ae57545ddb1c.png)

Strangely, this only appears to affect artist names. It does not affect album titles...

![Screenshot_20230422-234313_1](https://user-images.githubusercontent.com/32996640/233820489-db1eccac-e2ac-4547-a07c-d368dae63a2c.png)

...or song titles.

![Mdissue2](https://user-images.githubusercontent.com/32996640/233820492-0622ae17-cf0a-46bb-a973-fcd2b34a02af.png)

Before upgrading from 0.99.0 this issue did not exist.

In case it matters, this is a Google Pixel 6 running Android 13.

**Comment by Travisyard** [comment]
Adding a quick note: this bug is also reproducible in the desktop client (linux-amd64).

Edit: oops, did not mean to close and re-open

**Comment by clangen** [comment]
Interesting. While we did have a minor Unicode handling issue recently, it was strictly related to text _input_ on Windows builds caused by an external dependency -- otherwise nothing has been (intentionally) changed for years. Also, the fact that _some_ non-Latin characters are rendering fine but others aren't makes me think there may be an issue with the tags in your files.

Is it possible the metadata in the affected files was updated recently? Does downgrading to an older build of musikcube fix the issue?

Can you attach one of the problematic files to this ticket? I can give it a test on my end.

**Comment by Travisyard** [comment]
@clangen I did some more digging. The metadata on the files appears to be correct. The files all show last modified dates that are long ago, so the metadata shouldn't have changed.

Interestingly, downgrading from 3.0.0 to 0.99.8 does not cause the issue to go away. I am certain that this issue appeared immediately after upgrading to 3.0.0, so this is confusing me.

I am hesitant to attach these music files here as it is copyrighted music and I don't want to get myself or you in trouble for distribution of it. Could I send some files to you privately?

**Comment by clangen** [comment]
@Travisyard apologies, I've been out of town. Yeah, you can email it to me at `casey dot langen at gmail dot com` and I can take a look.

**Comment by Travisyard** [comment]
@clangen sent you a sample

**Comment by clangen** [comment]
@Travisyard got it, thank you! This commit should fix the bug: https://github.com/clangen/musikcube/commit/d81f82559abd9209f247e1e23826a597333bd586

I'm planning to release 3.0.1 sometime within the next couple days.

**Comment by clangen** [comment]
Apologies for the delay, real life got busy. 3.0.1 has been released, and should fix the issue. You'll need to force musikcube to rebuild your library... you can do this by pressing `CTRL+R` then selecting `rebuild library`. Playlists and other metadata will **not** be lost; this operation simply forces a rescan of all files.
