### ISSUE TITLE
Wont find music

### ISSUE THREAD

**Issue by Mircas001** [clangen/musikcube#609]
Musikcube wont find music im running on Windows via the Windows Terminal,it wont work on the exe either,it just cant find music from any path
Edit:It also cant save the path

**Comment by 237dmitry** [comment]
Did you add path where you are searching for music to the musikcube's library?

![Screenshot 2023-05-10 131347](https://github.com/clangen/musikcube/assets/78153320/7dbc29ed-67c7-4065-b73a-bb3d531e9fde)

**Comment by Mircas001** [comment]
Yes i did try and it did not find anything

**Comment by Mircas001** [comment]
![image](https://github.com/clangen/musikcube/assets/79532341/83c1fb38-e7bd-445d-b0b7-e901711c2324)
logs of me trying to add a path 
![image](https://github.com/clangen/musikcube/assets/79532341/a84e8b8d-ad1d-49ea-ab2c-f6a48a81a69a)
Logs of when I tried to rebuild library, I'm sorry I don't know how to copy and paste them

**Comment by jirpok** [comment]
I had exactly the same issue on my second laptop running macOS High Sierra.

**Comment by clangen** [comment]
Interesting, this is an issue I haven't seen reported before. What format are the files you're trying to import?

**Comment by jirpok** [comment]
In my case most of it are MP3, I think I also have some .flac.

**Comment by Mircas001** [comment]
They are MP3 files for the most part

**Comment by Mircas001** [comment]
Recently i did a clean reinstall of windows, and now it works.
