### ISSUE TITLE
.deb file is not recognized as a "Debian format archive"

### ISSUE THREAD

**Issue by spstrongco** [clangen/musikcube#618]
Obviously a noob.

I'm using Ubuntu 22.04.2 LTS.
I uninstalled 0.98.0 and was trying to install 3.0 using the dpkg install process and received the error in the subject.
Keep up the good work!
Thanks for your help.
Stephen

**Comment by clangen** [comment]
Can you let me know which deb you downloaded? Is it possible you downloaded the ARM version?

**Comment by spstrongco** [comment]
Thanks Casey. I used curl and it only downloaded ~200k of the binary. I was able to the get the downloaded version onto the server and now all is well. Thanks again.
