### ISSUE TITLE
Feature request: import rating from mediafiles

### ISSUE THREAD

**Issue by 237dmitry** [clangen/musikcube#619]
It would be easier to view the ratings of added tracks, and users wouldn't have to use sqlite3 to update the player's media database.

I was forced to write a script that exports the rating from files to the media base:

```powershell
#!/usr/bin/env -S pwsh -nop

param ( [Parameter()] [IO.DirectoryInfo] $Directory = "$HOME/Music")

$files = Get-Childitem $directory/*.flac -Recurse

foreach ($file in $files)
{
    if ($rating = metaflac --show-tag=RATING $file) { $rating = $rating.Split('=')[1] }
    else { $rating = 0 }

    $track = "'" + $($file.FullName -replace "'","''") + "'"

    "update tracks set rating = $rating where filename = $track;" | sqlite3 ~/.config/musikcube/1/musik.db
}
```
But this is not the best solution and can break the database.

**Comment by clangen** [comment]
I've seen this come up a couple times, so I just added this to `master` and it will be part of the 3.0.2 release. This turned out to be trickier than expected for ID3V2 files, and I'm not sure it'll always work as expected (although it seems to be fine with my test files).

**Comment by clangen** [comment]
In theory this should be fixed, but as noted it was a pretty gnarly change in practice. You'll need to do the following:
1. Download 3.0.2 (or newer), here: https://github.com/clangen/musikcube/releases/tag/3.0.2
2. Force a library rebuild by pressing `CTRL+R` then selecting `rebuild library` (don't worry, it won't destroy playlists, playcounts, etc -- it simply forces a rescan of every file).
