### ISSUE TITLE
Package musikcube-3.0.1-1.amd64 from @commandline does not have a compatible architecture

### ISSUE THREAD

**Issue by sgtnasty** [clangen/musikcube#623]
Trying to install [3.0.1](https://github.com/clangen/musikcube/releases/tag/3.0.1) on my AMD system and I get this error:

```
# sudo dnf install ./musikcube_linux_3.0.1_amd64.rpm                                                                                Last metadata expiration check: 0:52:31 ago on Mon 03 Jul 2023 08:02:53 AM EDT.
Error: 
 Problem: conflicting requests
  - package musikcube-3.0.1-1.amd64 from @commandline does not have a compatible architecture
(try to add '--skip-broken' to skip uninstallable packages)
```

I reached out to Fedora discussions and they asked me to notify upstream that:

> Please report that to Musikcube upstream, I’m sure they’d like to know. The arch in the rpm should be `x86_64` not `amd64`.

**Comment by sgtnasty** [comment]
This is on Fedora Sway 38

```
# cat /etc/fedora-release                                                                                                           
Fedora release 38 (Thirty Eight)
# uname -a
Linux phobos 6.3.8-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 15 02:15:40 UTC 2023 x86_64 GNU/Linux
```

**Comment by gojun077** [comment]
I'm on Fedora Sway 38 as well and the following worked for me:

```sh
sudo rpm -U musikcube_linux_3.0.1_amd64.rpm
```

Same as you, trying to install with dnf gave me the architecture error although `amd64` is the correct architecture.

**Comment by clangen** [comment]
Thanks for letting me know about this. I've been quite busy with other things recently, but will try to get this fixed in the next release -- it should be relatively straight forward.

**Comment by clangen** [comment]
OK, this has been fixed and will be included in the next release (which should hopefully go out soonish)

**Comment by dj3hac** [comment]
I just had this same issue installing on my Nobara (Fedora) 38 machine. I was able to successfully install the .deb version using dpkg however.

**Comment by clangen** [comment]
Should be fixed in this release: https://github.com/clangen/musikcube/releases/tag/3.0.2

Please let me know if this continues to be an issue.
