### ISSUE TITLE
Raspberry Pi "Illegal instruction" error still an issue

### ISSUE THREAD

**Issue by peterhavener** [clangen/musikcube#632]
This was talked about previously in https://github.com/clangen/musikcube/issues/518 but wasn't actually ever resolved. Any chance we can get a solution to this? I have the same issue on a Raspberry Pi Zero W (2017) on Raspbian 12 Bookworm with any package from 0.99 - 3.0.1.

Summary of issue:
 After installing musikcube package for ARM (raspberry pi) and trying to run, musikcube does not start and gives **"Illegal instruction"** error.

**Comment by clangen** [comment]
It's hard for me to support hardware that I don't have access to. Back when I was originally looking into this there was a shortage of Raspberry Pi Zeros, but it looks like they are generally available again. I'm going to try to get my hands on one and see if I can generate builds that work with it.

**Comment by clangen** [comment]
OK, I've managed to get the app running on RPi Zero devices, so builds will be available in subsequent releases.

Relevant commit: https://github.com/clangen/musikcube/commit/4f44829cda11071bd310592c1f5ff04f7a558863

**Comment by clangen** [comment]
Alright, there are now `armv6` builds that work on Raspberry Pi Zero devices here: https://github.com/clangen/musikcube/releases/tag/3.0.2

**Comment by clangen** [comment]
Feel free to re-open if these builds don't work for you.
