### ISSUE TITLE
The amd64.rpm file raises errors ( I cant find x86 version of the rpm file )

### ISSUE THREAD

**Issue by Vjay15** [clangen/musikcube#635]
While checking the documentation i was instructed to download the x86 version of the rpm for fedora but there was only amd64 version for fedora and even after i downloaded it and run it through the dnf package manager, it says that the given file does not have a compatible architecture :sob:

**Comment by clangen** [comment]
We weren't previously supplying x86 builds, but I added them to the most recent release here: https://github.com/clangen/musikcube/releases/tag/3.0.2

**Comment by Vjay15** [comment]
thank you so much clangen!
