### ISSUE TITLE
Binaries aren't linked with libFLAC.so, libogg.so, libvorbis.so but script/build-vendor-libraries.sh lists them

### ISSUE THREAD

**Issue by yurivict** [clangen/musikcube#638]
These libraries are only listed in the shell script, and configure doesn't look for them, and build doesn't link binaries with them.

Are these libraries real dependencies of musikube?

These libraries were flagged by the FreeBSD ports framework as potentially unused dependencies:
```
Warning: you might not need LIB_DEPENDS on libboost_system.so
Warning: you might not need LIB_DEPENDS on libFLAC.so
Warning: you might not need LIB_DEPENDS on libogg.so
Warning: you might not need LIB_DEPENDS on libvorbis.so
```

**Comment by clangen** [comment]
Yep, good call-out. These libraries _used to be_ required, but are not any longer. You should be able to remove them from the dependency list without issues.

**Comment by clangen** [comment]
Closing this ticket, please re-open if you have any additional questions. :)
